
-module(cards_project_app).
-behaviour(application).

-export([start/2, stop/1]).

start(_Type, _Args) ->
    case mnesia:create_schema([node()]) of
        ok -> ok;
        {error, {_, {already_exists, _}}} -> ok
    end,
    ok = mnesia:start(),
    ok = cards_project_schema:create_tables(),

    Dispatch = cowboy_router:compile([
        {'_', [
    {"/api/cards",      card_handler, #{}},
    {"/api/cards/:id",  card_handler, #{}},
    {"/api/card_sets",      card_set_handler, #{}},
    {"/api/card_sets/:id",  card_set_handler, #{}},
    {"/api/card_rulings",      card_ruling_handler, #{}},
    {"/api/card_rulings/:id",  card_ruling_handler, #{}},
    {"/api/card_abilities",      card_ability_handler, #{}},
    {"/api/card_abilities/:id",  card_ability_handler, #{}},
    {"/api/decks",      deck_handler, #{}},
    {"/api/decks/:id",  deck_handler, #{}},
    {"/api/deck_cards",      deck_card_handler, #{}},
    {"/api/deck_cards/:id",  deck_card_handler, #{}},
    {"/api/deck_sideboard_cards",      deck_sideboard_card_handler, #{}},
    {"/api/deck_sideboard_cards/:id",  deck_sideboard_card_handler, #{}},
    {"/api/deck_tags",      deck_tag_handler, #{}},
    {"/api/deck_tags/:id",  deck_tag_handler, #{}},
    {"/api/deck_tag_assignments",      deck_tag_assignment_handler, #{}},
    {"/api/deck_tag_assignments/:id",  deck_tag_assignment_handler, #{}},
    {"/api/players",      player_handler, #{}},
    {"/api/players/:id",  player_handler, #{}},
    {"/api/player_season_statses",      player_season_stats_handler, #{}},
    {"/api/player_season_statses/:id",  player_season_stats_handler, #{}},
    {"/api/player_collections",      player_collection_handler, #{}},
    {"/api/player_collections/:id",  player_collection_handler, #{}},
    {"/api/friendships",      friendship_handler, #{}},
    {"/api/friendships/:id",  friendship_handler, #{}},
    {"/api/achievements",      achievement_handler, #{}},
    {"/api/achievements/:id",  achievement_handler, #{}},
    {"/api/player_achievements",      player_achievement_handler, #{}},
    {"/api/player_achievements/:id",  player_achievement_handler, #{}},
    {"/api/crafting_recipes",      crafting_recipe_handler, #{}},
    {"/api/crafting_recipes/:id",  crafting_recipe_handler, #{}},
    {"/api/crafting_ingredients",      crafting_ingredient_handler, #{}},
    {"/api/crafting_ingredients/:id",  crafting_ingredient_handler, #{}},
    {"/api/seasons",      season_handler, #{}},
    {"/api/seasons/:id",  season_handler, #{}},
    {"/api/tournaments",      tournament_handler, #{}},
    {"/api/tournaments/:id",  tournament_handler, #{}},
    {"/api/tournaments/:id/transition/draft-to-registration", tournament_handler, #{transition => <<"draft-to-registration">>}},
    {"/api/tournaments/:id/transition/registration-to-ongoing", tournament_handler, #{transition => <<"registration-to-ongoing">>}},
    {"/api/tournaments/:id/transition/registration-to-cancelled", tournament_handler, #{transition => <<"registration-to-cancelled">>}},
    {"/api/tournaments/:id/transition/ongoing-to-completed", tournament_handler, #{transition => <<"ongoing-to-completed">>}},
    {"/api/tournaments/:id/transition/ongoing-to-cancelled", tournament_handler, #{transition => <<"ongoing-to-cancelled">>}},
    {"/api/tournament_judges",      tournament_judge_handler, #{}},
    {"/api/tournament_judges/:id",  tournament_judge_handler, #{}},
    {"/api/tournament_registrations",      tournament_registration_handler, #{}},
    {"/api/tournament_registrations/:id",  tournament_registration_handler, #{}},
    {"/api/tournament_rounds",      tournament_round_handler, #{}},
    {"/api/tournament_rounds/:id",  tournament_round_handler, #{}},
    {"/api/matches",      match_handler, #{}},
    {"/api/matches/:id",  match_handler, #{}},
    {"/api/matches/:id/transition/pending-to-active", match_handler, #{transition => <<"pending-to-active">>}},
    {"/api/matches/:id/transition/active-to-completed", match_handler, #{transition => <<"active-to-completed">>}},
    {"/api/matches/:id/transition/active-to-draw", match_handler, #{transition => <<"active-to-draw">>}},
    {"/api/matches/:id/transition/pending-to-b_y_e", match_handler, #{transition => <<"pending-to-b_y_e">>}},
    {"/api/games",      game_handler, #{}},
    {"/api/games/:id",  game_handler, #{}},
    {"/api/tournament_prizes",      tournament_prize_handler, #{}},
    {"/api/tournament_prizes/:id",  tournament_prize_handler, #{}},
    {"/api/awarded_prizes",      awarded_prize_handler, #{}},
    {"/api/awarded_prizes/:id",  awarded_prize_handler, #{}},
    {"/api/products",      product_handler, #{}},
    {"/api/products/:id",  product_handler, #{}},
    {"/api/orders",      order_handler, #{}},
    {"/api/orders/:id",  order_handler, #{}},
    {"/api/orders/:id/transition/pending-to-paid", order_handler, #{transition => <<"pending-to-paid">>}},
    {"/api/orders/:id/transition/paid-to-processing", order_handler, #{transition => <<"paid-to-processing">>}},
    {"/api/orders/:id/transition/processing-to-shipped", order_handler, #{transition => <<"processing-to-shipped">>}},
    {"/api/orders/:id/transition/shipped-to-completed", order_handler, #{transition => <<"shipped-to-completed">>}},
    {"/api/orders/:id/transition/pending-to-cancelled", order_handler, #{transition => <<"pending-to-cancelled">>}},
    {"/api/orders/:id/transition/paid-to-cancelled", order_handler, #{transition => <<"paid-to-cancelled">>}},
    {"/api/orders/:id/transition/completed-to-refunded", order_handler, #{transition => <<"completed-to-refunded">>}},
    {"/api/order_items",      order_item_handler, #{}},
    {"/api/order_items/:id",  order_item_handler, #{}},
    {"/api/coupons",      coupon_handler, #{}},
    {"/api/coupons/:id",  coupon_handler, #{}},
    {"/api/trade_listings",      trade_listing_handler, #{}},
    {"/api/trade_listings/:id",  trade_listing_handler, #{}},
    {"/api/trade_listings/:id/transition/pending-to-active", trade_listing_handler, #{transition => <<"pending-to-active">>}},
    {"/api/trade_listings/:id/transition/active-to-sold", trade_listing_handler, #{transition => <<"active-to-sold">>}},
    {"/api/trade_listings/:id/transition/active-to-expired", trade_listing_handler, #{transition => <<"active-to-expired">>}},
    {"/api/trade_listings/:id/transition/active-to-cancelled", trade_listing_handler, #{transition => <<"active-to-cancelled">>}},
    {"/api/trade_bids",      trade_bid_handler, #{}},
    {"/api/trade_bids/:id",  trade_bid_handler, #{}},
    {"/api/trade_transactions",      trade_transaction_handler, #{}},
    {"/api/trade_transactions/:id",  trade_transaction_handler, #{}},
    {"/api/card_price_histories",      card_price_history_handler, #{}},
    {"/api/card_price_histories/:id",  card_price_history_handler, #{}},
    {"/api/trade_disputes",      trade_dispute_handler, #{}},
    {"/api/trade_disputes/:id",  trade_dispute_handler, #{}},
    {"/api/trade_disputes/:id/transition/open-to-under_review", trade_dispute_handler, #{transition => <<"open-to-under_review">>}},
    {"/api/trade_disputes/:id/transition/under_review-to-resolved", trade_dispute_handler, #{transition => <<"under_review-to-resolved">>}},
    {"/api/trade_disputes/:id/transition/under_review-to-escalated", trade_dispute_handler, #{transition => <<"under_review-to-escalated">>}},
    {"/api/trade_disputes/:id/transition/escalated-to-resolved", trade_dispute_handler, #{transition => <<"escalated-to-resolved">>}},
    {"/api/draft_sessions",      draft_session_handler, #{}},
    {"/api/draft_sessions/:id",  draft_session_handler, #{}},
    {"/api/draft_sessions/:id/transition/waiting_for_players-to-drafting", draft_session_handler, #{transition => <<"waiting_for_players-to-drafting">>}},
    {"/api/draft_sessions/:id/transition/drafting-to-completed", draft_session_handler, #{transition => <<"drafting-to-completed">>}},
    {"/api/draft_sessions/:id/transition/drafting-to-abandoned", draft_session_handler, #{transition => <<"drafting-to-abandoned">>}},
    {"/api/draft_sessions/:id/transition/waiting_for_players-to-abandoned", draft_session_handler, #{transition => <<"waiting_for_players-to-abandoned">>}},
    {"/api/draft_participants",      draft_participant_handler, #{}},
    {"/api/draft_participants/:id",  draft_participant_handler, #{}},
    {"/api/draft_picks",      draft_pick_handler, #{}},
    {"/api/draft_picks/:id",  draft_pick_handler, #{}},
    {"/api/articles",      article_handler, #{}},
    {"/api/articles/:id",  article_handler, #{}},
    {"/api/articles/:id/transition/draft-to-published", article_handler, #{transition => <<"draft-to-published">>}},
    {"/api/articles/:id/transition/published-to-archived", article_handler, #{transition => <<"published-to-archived">>}},
    {"/api/articles/:id/transition/archived-to-draft", article_handler, #{transition => <<"archived-to-draft">>}},
    {"/api/article_tags",      article_tag_handler, #{}},
    {"/api/article_tags/:id",  article_tag_handler, #{}},
    {"/api/article_tag_assignments",      article_tag_assignment_handler, #{}},
    {"/api/article_tag_assignments/:id",  article_tag_assignment_handler, #{}},
    {"/api/article_comments",      article_comment_handler, #{}},
    {"/api/article_comments/:id",  article_comment_handler, #{}},
    {"/api/streams",      stream_handler, #{}},
    {"/api/streams/:id",  stream_handler, #{}},
    {"/api/streams/:id/transition/scheduled-to-live", stream_handler, #{transition => <<"scheduled-to-live">>}},
    {"/api/streams/:id/transition/live-to-ended", stream_handler, #{transition => <<"live-to-ended">>}}
        ]}
    ]),
    {ok, _} = cowboy:start_clear(http_listener,
        [{port, 8080}],
        #{env => #{dispatch => Dispatch}}
    ),
    cards_project_sup:start_link().

stop(_State) ->
    ok = cowboy:stop_listener(http_listener).
