<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Api\Cards\CardController;
use App\Http\Controllers\Api\Cards\CardSetController;
use App\Http\Controllers\Api\Cards\CardRulingController;
use App\Http\Controllers\Api\Cards\CardAbilityController;
use App\Http\Controllers\Api\Cards\DeckController;
use App\Http\Controllers\Api\Cards\DeckCardController;
use App\Http\Controllers\Api\Cards\DeckSideboardCardController;
use App\Http\Controllers\Api\Cards\DeckTagController;
use App\Http\Controllers\Api\Cards\DeckTagAssignmentController;
use App\Http\Controllers\Api\Players\PlayerController;
use App\Http\Controllers\Api\Players\PlayerSeasonStatsController;
use App\Http\Controllers\Api\Players\PlayerCollectionController;
use App\Http\Controllers\Api\Players\FriendshipController;
use App\Http\Controllers\Api\Players\AchievementController;
use App\Http\Controllers\Api\Players\PlayerAchievementController;
use App\Http\Controllers\Api\Players\CraftingRecipeController;
use App\Http\Controllers\Api\Players\CraftingIngredientController;
use App\Http\Controllers\Api\Tournaments\SeasonController;
use App\Http\Controllers\Api\Tournaments\TournamentController;
use App\Http\Controllers\Api\Tournaments\TournamentJudgeController;
use App\Http\Controllers\Api\Tournaments\TournamentRegistrationController;
use App\Http\Controllers\Api\Tournaments\TournamentRoundController;
use App\Http\Controllers\Api\Tournaments\MatchRecordController;
use App\Http\Controllers\Api\Tournaments\GameController;
use App\Http\Controllers\Api\Tournaments\TournamentPrizeController;
use App\Http\Controllers\Api\Tournaments\AwardedPrizeController;
use App\Http\Controllers\Api\Marketplace\ProductController;
use App\Http\Controllers\Api\Marketplace\OrderController;
use App\Http\Controllers\Api\Marketplace\OrderItemController;
use App\Http\Controllers\Api\Marketplace\CouponController;
use App\Http\Controllers\Api\Marketplace\TradeListingController;
use App\Http\Controllers\Api\Marketplace\TradeBidController;
use App\Http\Controllers\Api\Marketplace\TradeTransactionController;
use App\Http\Controllers\Api\Marketplace\CardPriceHistoryController;
use App\Http\Controllers\Api\Marketplace\TradeDisputeController;
use App\Http\Controllers\Api\Content\DraftSessionController;
use App\Http\Controllers\Api\Content\DraftParticipantController;
use App\Http\Controllers\Api\Content\DraftPickController;
use App\Http\Controllers\Api\Content\ArticleController;
use App\Http\Controllers\Api\Content\ArticleTagController;
use App\Http\Controllers\Api\Content\ArticleTagAssignmentController;
use App\Http\Controllers\Api\Content\ArticleCommentController;
use App\Http\Controllers\Api\Content\StreamController;

Route::apiResource('cards', CardController::class)->only(['index', 'show', 'store', 'update']);
Route::post('cards/{card}/ban', [CardController::class, 'ban']);
Route::post('cards/{card}/unban', [CardController::class, 'unban']);
Route::post('cards/{card}/restrict', [CardController::class, 'restrict']);
Route::post('cards/{card}/unrestrict', [CardController::class, 'unrestrict']);
Route::put('cards/{card}/replace', [CardController::class, 'replace']);
Route::get('cards/{card}/value', [CardController::class, 'calculateValue']);
Route::post('cards/{card}/rarity-bonus', [CardController::class, 'applyRarityBonus']);
Route::get('cards/{card}/legal', [CardController::class, 'isLegalInFormat']);
Route::apiResource('card_sets', CardSetController::class)->only(['index', 'show', 'store', 'update']);
Route::get('card_sets/{cardSet}/standard-legal', [CardSetController::class, 'isLegalInStandard']);
Route::get('card_sets/{cardSet}/legal', [CardSetController::class, 'isLegalInFormat']);
Route::get('card_sets/{cardSet}/rarity-count', [CardSetController::class, 'cardCountByRarity']);
Route::post('card_sets/{cardSet}/rotate', [CardSetController::class, 'rotateOut']);
Route::apiResource('card_rulings', CardRulingController::class)->only(['index', 'show', 'store', 'destroy']);
Route::get('card_rulings/{cardRuling}/current', [CardRulingController::class, 'isCurrent']);
Route::get('card_rulings/{cardRuling}/supersedes', [CardRulingController::class, 'supersedesPrevious']);
Route::apiResource('card_abilities', CardAbilityController::class);
Route::get('card_abilities/{cardAbility}/usable', [CardAbilityController::class, 'isUsableAt']);
Route::get('card_abilities/{cardAbility}/describe', [CardAbilityController::class, 'describe']);
Route::apiResource('decks', DeckController::class);
Route::get('decks/{deck}/validate', [DeckController::class, 'validateSize']);
Route::post('decks/{deck}/cards', [DeckController::class, 'addCard']);
Route::delete('decks/{deck}/cards/{card_id}', [DeckController::class, 'removeCard']);
Route::get('decks/{deck}/win-rate', [DeckController::class, 'winRate']);
Route::post('decks/{deck}/clone', [DeckController::class, 'clone']);
Route::post('decks/{deck}/publish', [DeckController::class, 'publish']);
Route::post('decks/{deck}/unpublish', [DeckController::class, 'unpublish']);
Route::post('decks/{deck}/certify', [DeckController::class, 'certifyTournamentLegal']);
Route::apiResource('deck_cards', DeckCardController::class)->only(['index', 'show', 'store', 'update', 'destroy']);
Route::patch('deck_cards/{deckCard}/increment', [DeckCardController::class, 'incrementAction']);
Route::patch('deck_cards/{deckCard}/decrement', [DeckCardController::class, 'decrementAction']);
Route::apiResource('deck_sideboard_cards', DeckSideboardCardController::class)->only(['index', 'show', 'store', 'update', 'destroy']);
Route::patch('deck_sideboard_cards/{deckSideboardCard}/increment', [DeckSideboardCardController::class, 'incrementAction']);
Route::patch('deck_sideboard_cards/{deckSideboardCard}/decrement', [DeckSideboardCardController::class, 'decrementAction']);
Route::apiResource('deck_tags', DeckTagController::class)->only(['index', 'show', 'store', 'update', 'destroy']);
Route::patch('deck_tags/{deckTag}/rename', [DeckTagController::class, 'rename']);
Route::post('deck_tags/{deckTag}/merge', [DeckTagController::class, 'mergeInto']);
Route::apiResource('deck_tag_assignments', DeckTagAssignmentController::class)->only(['index', 'show', 'store', 'destroy']);
Route::apiResource('players', PlayerController::class)->only(['index', 'show', 'store', 'update']);
Route::post('players/{player}/promote', [PlayerController::class, 'promote']);
Route::post('players/{player}/demote', [PlayerController::class, 'demote']);
Route::post('players/{player}/win', [PlayerController::class, 'recordWin']);
Route::post('players/{player}/loss', [PlayerController::class, 'recordLoss']);
Route::get('players/{player}/win-rate', [PlayerController::class, 'winRate']);
Route::post('players/{player}/verify', [PlayerController::class, 'verify']);
Route::patch('players/{player}/rating', [PlayerController::class, 'updateRating']);
Route::apiResource('player_season_statses', PlayerSeasonStatsController::class)->only(['index', 'show']);
Route::get('player_season_statses/{playerSeasonStats}/win-rate', [PlayerSeasonStatsController::class, 'winRate']);
Route::patch('player_season_statses/{playerSeasonStats}/points', [PlayerSeasonStatsController::class, 'addPoints']);
Route::post('player_season_statses/{playerSeasonStats}/tournament-win', [PlayerSeasonStatsController::class, 'recordTournamentWin']);
Route::apiResource('player_collections', PlayerCollectionController::class)->only(['index', 'show', 'store', 'update', 'destroy']);
Route::post('player_collections/{playerCollection}/add', [PlayerCollectionController::class, 'add']);
Route::post('player_collections/{playerCollection}/remove', [PlayerCollectionController::class, 'remove']);
Route::get('player_collections/{playerCollection}/value', [PlayerCollectionController::class, 'estimatedValue']);
Route::apiResource('friendships', FriendshipController::class)->only(['index', 'show', 'store', 'destroy']);
Route::post('friendships/{friendship}/accept', [FriendshipController::class, 'accept']);
Route::post('friendships/{friendship}/decline', [FriendshipController::class, 'decline']);
Route::post('friendships/{friendship}/block', [FriendshipController::class, 'block']);
Route::apiResource('achievements', AchievementController::class)->only(['index', 'show', 'store', 'update']);
Route::get('achievements/{achievement}/point-value', [AchievementController::class, 'pointValue']);
Route::post('achievements/{achievement}/reveal', [AchievementController::class, 'reveal']);
Route::apiResource('player_achievements', PlayerAchievementController::class)->only(['index', 'show']);
Route::patch('player_achievements/{playerAchievement}/progress', [PlayerAchievementController::class, 'incrementProgress']);
Route::post('player_achievements/{playerAchievement}/complete', [PlayerAchievementController::class, 'complete']);
Route::apiResource('crafting_recipes', CraftingRecipeController::class)->only(['index', 'show', 'store', 'update']);
Route::get('crafting_recipes/{craftingRecipe}/can-craft', [CraftingRecipeController::class, 'canCraft']);
Route::post('crafting_recipes/{craftingRecipe}/craft', [CraftingRecipeController::class, 'executeCraft']);
Route::post('crafting_recipes/{craftingRecipe}/disable', [CraftingRecipeController::class, 'disable']);
Route::post('crafting_recipes/{craftingRecipe}/enable', [CraftingRecipeController::class, 'enable']);
Route::apiResource('crafting_ingredients', CraftingIngredientController::class)->only(['index', 'show', 'store', 'destroy']);
Route::apiResource('seasons', SeasonController::class)->only(['index', 'show', 'store', 'update']);
Route::post('seasons/{season}/activate', [SeasonController::class, 'activate']);
Route::post('seasons/{season}/deactivate', [SeasonController::class, 'deactivate']);
Route::post('seasons/{season}/finalize', [SeasonController::class, 'finalizeRewards']);
Route::get('seasons/{season}/ongoing', [SeasonController::class, 'isOngoing']);
Route::apiResource('tournaments', TournamentController::class)->only(['index', 'show', 'store', 'update']);
Route::post('tournaments/{tournament}/start', [TournamentController::class, 'start']);
Route::post('tournaments/{tournament}/cancel', [TournamentController::class, 'cancel']);
Route::post('tournaments/{tournament}/complete', [TournamentController::class, 'complete']);
Route::post('tournaments/{tournament}/rounds', [TournamentController::class, 'generateRound']);
Route::get('tournaments/{tournament}/prizes', [TournamentController::class, 'calculatePrizeDistribution']);
Route::post('tournaments/{tournament}/register', [TournamentController::class, 'registerPlayer']);
Route::get('tournaments/{tournament}/full', [TournamentController::class, 'isFull']);
Route::patch('tournaments/{tournament}/transitions/draft-to-registration', [TournamentController::class, 'transitionDraftToRegistration']);
Route::patch('tournaments/{tournament}/transitions/registration-to-ongoing', [TournamentController::class, 'transitionRegistrationToOngoing']);
Route::patch('tournaments/{tournament}/transitions/registration-to-cancelled', [TournamentController::class, 'transitionRegistrationToCancelled']);
Route::patch('tournaments/{tournament}/transitions/ongoing-to-completed', [TournamentController::class, 'transitionOngoingToCompleted']);
Route::patch('tournaments/{tournament}/transitions/ongoing-to-cancelled', [TournamentController::class, 'transitionOngoingToCancelled']);
Route::patch('tournaments/{tournament}/transitions/completed-to-draft', [TournamentController::class, 'transitionCompletedToDraft']);
Route::patch('tournaments/{tournament}/transitions/cancelled-to-draft', [TournamentController::class, 'transitionCancelledToDraft']);
Route::apiResource('tournament_judges', TournamentJudgeController::class)->only(['index', 'show', 'store', 'destroy']);
Route::post('tournament_judges/{tournamentJudge}/promote', [TournamentJudgeController::class, 'promoteToHead']);
Route::delete('tournament_judges/{tournamentJudge}/remove', [TournamentJudgeController::class, 'remove']);
Route::apiResource('tournament_registrations', TournamentRegistrationController::class)->only(['index', 'show', 'store']);
Route::post('tournament_registrations/{tournamentRegistration}/withdraw', [TournamentRegistrationController::class, 'withdraw']);
Route::post('tournament_registrations/{tournamentRegistration}/disqualify', [TournamentRegistrationController::class, 'disqualify']);
Route::post('tournament_registrations/{tournamentRegistration}/promote', [TournamentRegistrationController::class, 'promoteFromWaitlist']);
Route::apiResource('tournament_rounds', TournamentRoundController::class)->only(['index', 'show', 'store']);
Route::post('tournament_rounds/{tournamentRound}/start', [TournamentRoundController::class, 'start']);
Route::post('tournament_rounds/{tournamentRound}/complete', [TournamentRoundController::class, 'complete']);
Route::post('tournament_rounds/{tournamentRound}/pairings', [TournamentRoundController::class, 'generatePairings']);
Route::get('tournament_rounds/{tournamentRound}/time-expired', [TournamentRoundController::class, 'isTimeExpired']);
Route::apiResource('matches', MatchRecordController::class)->only(['index', 'show', 'store']);
Route::post('matches/{matchRecord}/record', [MatchRecordController::class, 'recordResult']);
Route::post('matches/{matchRecord}/finalize', [MatchRecordController::class, 'finalizeResult']);
Route::get('matches/{matchRecord}/winner', [MatchRecordController::class, 'determineWinner']);
Route::post('matches/{matchRecord}/concede', [MatchRecordController::class, 'concede']);
Route::post('matches/{matchRecord}/draw', [MatchRecordController::class, 'draw']);
Route::patch('matches/{matchRecord}/transitions/pending-to-active', [MatchRecordController::class, 'transitionPendingToActive']);
Route::patch('matches/{matchRecord}/transitions/active-to-completed', [MatchRecordController::class, 'transitionActiveToCompleted']);
Route::patch('matches/{matchRecord}/transitions/active-to-draw', [MatchRecordController::class, 'transitionActiveToDraw']);
Route::patch('matches/{matchRecord}/transitions/pending-to-bye', [MatchRecordController::class, 'transitionPendingToBYE']);
Route::patch('matches/{matchRecord}/transitions/completed-to-active', [MatchRecordController::class, 'transitionCompletedToActive']);
Route::patch('matches/{matchRecord}/transitions/draw-to-active', [MatchRecordController::class, 'transitionDrawToActive']);
Route::patch('matches/{matchRecord}/transitions/bye-to-active', [MatchRecordController::class, 'transitionBYEToActive']);
Route::apiResource('games', GameController::class)->only(['index', 'show', 'store']);
Route::post('games/{game}/winner', [GameController::class, 'recordWinner']);
Route::get('games/{game}/duration', [GameController::class, 'durationMinutes']);
Route::apiResource('tournament_prizes', TournamentPrizeController::class);
Route::get('tournament_prizes/{tournamentPrize}/applies', [TournamentPrizeController::class, 'appliesToPlacement']);
Route::post('tournament_prizes/{tournamentPrize}/award', [TournamentPrizeController::class, 'awardToPlayer']);
Route::apiResource('awarded_prizes', AwardedPrizeController::class)->only(['index', 'show']);
Route::post('awarded_prizes/{awardedPrize}/claim', [AwardedPrizeController::class, 'claim']);
Route::apiResource('products', ProductController::class)->only(['index', 'show', 'store', 'update']);
Route::post('products/{product}/activate', [ProductController::class, 'activate']);
Route::post('products/{product}/deactivate', [ProductController::class, 'deactivate']);
Route::patch('products/{product}/discount', [ProductController::class, 'applyDiscount']);
Route::post('products/{product}/restock', [ProductController::class, 'restock']);
Route::get('products/{product}/effective-price', [ProductController::class, 'effectivePrice']);
Route::get('products/{product}/in-stock', [ProductController::class, 'isInStock']);
Route::apiResource('orders', OrderController::class)->only(['index', 'show', 'store']);
Route::delete('orders/{order}/cancel', [OrderController::class, 'cancel']);
Route::post('orders/{order}/pay', [OrderController::class, 'pay']);
Route::post('orders/{order}/process-payment', [OrderController::class, 'processPayment']);
Route::get('orders/{order}/total', [OrderController::class, 'calculateTotal']);
Route::patch('orders/{order}/discount', [OrderController::class, 'applyDiscount']);
Route::post('orders/{order}/refund', [OrderController::class, 'refund']);
Route::patch('orders/{order}/transitions/pending-to-paid', [OrderController::class, 'transitionPendingToPaid']);
Route::patch('orders/{order}/transitions/paid-to-processing', [OrderController::class, 'transitionPaidToProcessing']);
Route::patch('orders/{order}/transitions/processing-to-shipped', [OrderController::class, 'transitionProcessingToShipped']);
Route::patch('orders/{order}/transitions/shipped-to-completed', [OrderController::class, 'transitionShippedToCompleted']);
Route::patch('orders/{order}/transitions/pending-to-cancelled', [OrderController::class, 'transitionPendingToCancelled']);
Route::patch('orders/{order}/transitions/paid-to-cancelled', [OrderController::class, 'transitionPaidToCancelled']);
Route::patch('orders/{order}/transitions/completed-to-refunded', [OrderController::class, 'transitionCompletedToRefunded']);
Route::patch('orders/{order}/transitions/refunded-to-completed', [OrderController::class, 'transitionRefundedToCompleted']);
Route::patch('orders/{order}/transitions/completed-to-cancelled', [OrderController::class, 'transitionCompletedToCancelled']);
Route::apiResource('order_items', OrderItemController::class)->only(['index', 'show', 'store', 'destroy']);
Route::get('order_items/{orderItem}/total', [OrderItemController::class, 'lineTotal']);
Route::apiResource('coupons', CouponController::class)->only(['index', 'show', 'store', 'update']);
Route::get('coupons/{coupon}/valid', [CouponController::class, 'isValid']);
Route::get('coupons/{coupon}/applicable', [CouponController::class, 'isApplicableToOrder']);
Route::post('coupons/{coupon}/redeem', [CouponController::class, 'redeem']);
Route::post('coupons/{coupon}/deactivate', [CouponController::class, 'deactivate']);
Route::apiResource('trade_listings', TradeListingController::class)->only(['index', 'show', 'store', 'update']);
Route::post('trade_listings/{tradeListing}/close', [TradeListingController::class, 'close']);
Route::patch('trade_listings/{tradeListing}/extend', [TradeListingController::class, 'extend']);
Route::delete('trade_listings/{tradeListing}/cancel', [TradeListingController::class, 'cancel']);
Route::get('trade_listings/{tradeListing}/expired', [TradeListingController::class, 'isExpired']);
Route::post('trade_listings/{tradeListing}/finalize', [TradeListingController::class, 'finalizeAuction']);
Route::patch('trade_listings/{tradeListing}/transitions/pending-to-active', [TradeListingController::class, 'transitionPendingToActive']);
Route::patch('trade_listings/{tradeListing}/transitions/active-to-sold', [TradeListingController::class, 'transitionActiveToSold']);
Route::patch('trade_listings/{tradeListing}/transitions/active-to-expired', [TradeListingController::class, 'transitionActiveToExpired']);
Route::patch('trade_listings/{tradeListing}/transitions/active-to-cancelled', [TradeListingController::class, 'transitionActiveToCancelled']);
Route::patch('trade_listings/{tradeListing}/transitions/sold-to-active', [TradeListingController::class, 'transitionSoldToActive']);
Route::patch('trade_listings/{tradeListing}/transitions/expired-to-active', [TradeListingController::class, 'transitionExpiredToActive']);
Route::apiResource('trade_bids', TradeBidController::class)->only(['index', 'show', 'store']);
Route::get('trade_bids/{tradeBid}/outbid', [TradeBidController::class, 'outbidBy']);
Route::delete('trade_bids/{tradeBid}/retract', [TradeBidController::class, 'retract']);
Route::apiResource('trade_transactions', TradeTransactionController::class)->only(['index', 'show']);
Route::post('trade_transactions/{tradeTransaction}/complete', [TradeTransactionController::class, 'complete']);
Route::post('trade_transactions/{tradeTransaction}/refund', [TradeTransactionController::class, 'refund']);
Route::post('trade_transactions/{tradeTransaction}/dispute', [TradeTransactionController::class, 'openDispute']);
Route::get('trade_transactions/{tradeTransaction}/seller-net', [TradeTransactionController::class, 'sellerNet']);
Route::apiResource('card_price_histories', CardPriceHistoryController::class)->only(['index', 'show']);
Route::get('card_price_histories/{cardPriceHistory}/change', [CardPriceHistoryController::class, 'priceChangePercent']);
Route::get('card_price_histories/{cardPriceHistory}/spike', [CardPriceHistoryController::class, 'isPriceSpike']);
Route::apiResource('trade_disputes', TradeDisputeController::class)->only(['index', 'show', 'store']);
Route::post('trade_disputes/{tradeDispute}/escalate', [TradeDisputeController::class, 'escalate']);
Route::post('trade_disputes/{tradeDispute}/resolve', [TradeDisputeController::class, 'resolve']);
Route::post('trade_disputes/{tradeDispute}/close', [TradeDisputeController::class, 'closeResolved']);
Route::post('trade_disputes/{tradeDispute}/review', [TradeDisputeController::class, 'review']);
Route::patch('trade_disputes/{tradeDispute}/transitions/open-to-underreview', [TradeDisputeController::class, 'transitionOpenToUnderReview']);
Route::patch('trade_disputes/{tradeDispute}/transitions/underreview-to-resolved', [TradeDisputeController::class, 'transitionUnderReviewToResolved']);
Route::patch('trade_disputes/{tradeDispute}/transitions/underreview-to-escalated', [TradeDisputeController::class, 'transitionUnderReviewToEscalated']);
Route::patch('trade_disputes/{tradeDispute}/transitions/escalated-to-resolved', [TradeDisputeController::class, 'transitionEscalatedToResolved']);
Route::patch('trade_disputes/{tradeDispute}/transitions/resolved-to-open', [TradeDisputeController::class, 'transitionResolvedToOpen']);
Route::apiResource('draft_sessions', DraftSessionController::class)->only(['index', 'show', 'store']);
Route::post('draft_sessions/{draftSession}/start', [DraftSessionController::class, 'start']);
Route::post('draft_sessions/{draftSession}/abandon', [DraftSessionController::class, 'abandon']);
Route::post('draft_sessions/{draftSession}/complete', [DraftSessionController::class, 'complete']);
Route::get('draft_sessions/{draftSession}/full', [DraftSessionController::class, 'isFull']);
Route::patch('draft_sessions/{draftSession}/transitions/waitingforplayers-to-drafting', [DraftSessionController::class, 'transitionWaitingForPlayersToDrafting']);
Route::patch('draft_sessions/{draftSession}/transitions/drafting-to-completed', [DraftSessionController::class, 'transitionDraftingToCompleted']);
Route::patch('draft_sessions/{draftSession}/transitions/drafting-to-abandoned', [DraftSessionController::class, 'transitionDraftingToAbandoned']);
Route::patch('draft_sessions/{draftSession}/transitions/waitingforplayers-to-abandoned', [DraftSessionController::class, 'transitionWaitingForPlayersToAbandoned']);
Route::patch('draft_sessions/{draftSession}/transitions/completed-to-drafting', [DraftSessionController::class, 'transitionCompletedToDrafting']);
Route::patch('draft_sessions/{draftSession}/transitions/abandoned-to-drafting', [DraftSessionController::class, 'transitionAbandonedToDrafting']);
Route::apiResource('draft_participants', DraftParticipantController::class)->only(['index', 'show', 'store']);
Route::post('draft_participants/{draftParticipant}/pick', [DraftParticipantController::class, 'pickCard']);
Route::get('draft_participants/{draftParticipant}/card-count', [DraftParticipantController::class, 'draftedCardCount']);
Route::apiResource('draft_picks', DraftPickController::class)->only(['index', 'show']);
Route::get('draft_picks/{draftPick}/first-pick', [DraftPickController::class, 'isFirstPick']);
Route::apiResource('articles', ArticleController::class)->only(['index', 'show', 'store', 'update']);
Route::post('articles/{article}/publish', [ArticleController::class, 'publish']);
Route::post('articles/{article}/archive', [ArticleController::class, 'archive']);
Route::put('articles/{article}/replace', [ArticleController::class, 'replace']);
Route::post('articles/{article}/view', [ArticleController::class, 'incrementView']);
Route::post('articles/{article}/like', [ArticleController::class, 'like']);
Route::delete('articles/{article}/like', [ArticleController::class, 'unlike']);
Route::get('articles/{article}/reading-time', [ArticleController::class, 'readingTimeMinutes']);
Route::patch('articles/{article}/transitions/draft-to-published', [ArticleController::class, 'transitionDraftToPublished']);
Route::patch('articles/{article}/transitions/published-to-archived', [ArticleController::class, 'transitionPublishedToArchived']);
Route::patch('articles/{article}/transitions/archived-to-draft', [ArticleController::class, 'transitionArchivedToDraft']);
Route::patch('articles/{article}/transitions/published-to-draft', [ArticleController::class, 'transitionPublishedToDraft']);
Route::apiResource('article_tags', ArticleTagController::class)->only(['index', 'show', 'store', 'update', 'destroy']);
Route::patch('article_tags/{articleTag}/rename', [ArticleTagController::class, 'rename']);
Route::get('article_tags/{articleTag}/article-count', [ArticleTagController::class, 'articleCount']);
Route::apiResource('article_tag_assignments', ArticleTagAssignmentController::class)->only(['index', 'show', 'store', 'destroy']);
Route::apiResource('article_comments', ArticleCommentController::class)->only(['index', 'show', 'store', 'destroy']);
Route::post('article_comments/{articleComment}/hide', [ArticleCommentController::class, 'hide']);
Route::post('article_comments/{articleComment}/unhide', [ArticleCommentController::class, 'unhide']);
Route::get('article_comments/{articleComment}/is-reply', [ArticleCommentController::class, 'isReply']);
Route::apiResource('streams', StreamController::class)->only(['index', 'show', 'store', 'update']);
Route::post('streams/{stream}/live', [StreamController::class, 'goLive']);
Route::post('streams/{stream}/end', [StreamController::class, 'end']);
Route::patch('streams/{stream}/viewers', [StreamController::class, 'updateViewerPeak']);
Route::get('streams/{stream}/duration', [StreamController::class, 'durationMinutes']);
Route::patch('streams/{stream}/transitions/scheduled-to-live', [StreamController::class, 'transitionScheduledToLive']);
Route::patch('streams/{stream}/transitions/live-to-ended', [StreamController::class, 'transitionLiveToEnded']);
Route::patch('streams/{stream}/transitions/ended-to-live', [StreamController::class, 'transitionEndedToLive']);
