<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Api\Cards\CardController;
use App\Http\Controllers\Api\Cards\CardSetController;
use App\Http\Controllers\Api\Cards\CardRulingController;
use App\Http\Controllers\Api\Cards\CardAbilityController;
use App\Http\Controllers\Api\Cards\DeckController;
use App\Http\Controllers\Api\Cards\DeckCardController;
use App\Http\Controllers\Api\Cards\DeckSideboardCardController;
use App\Http\Controllers\Api\Cards\DeckTagController;
use App\Http\Controllers\Api\Cards\DeckTagAssignmentController;
use App\Http\Controllers\Api\Players\PlayerController;
use App\Http\Controllers\Api\Players\PlayerSeasonStatsController;
use App\Http\Controllers\Api\Players\PlayerCollectionController;
use App\Http\Controllers\Api\Players\FriendshipController;
use App\Http\Controllers\Api\Players\AchievementController;
use App\Http\Controllers\Api\Players\PlayerAchievementController;
use App\Http\Controllers\Api\Players\CraftingRecipeController;
use App\Http\Controllers\Api\Players\CraftingIngredientController;
use App\Http\Controllers\Api\Tournaments\SeasonController;
use App\Http\Controllers\Api\Tournaments\TournamentController;
use App\Http\Controllers\Api\Tournaments\TournamentJudgeController;
use App\Http\Controllers\Api\Tournaments\TournamentRegistrationController;
use App\Http\Controllers\Api\Tournaments\TournamentRoundController;
use App\Http\Controllers\Api\Tournaments\MatchRecordController;
use App\Http\Controllers\Api\Tournaments\GameController;
use App\Http\Controllers\Api\Tournaments\TournamentPrizeController;
use App\Http\Controllers\Api\Tournaments\AwardedPrizeController;
use App\Http\Controllers\Api\Marketplace\ProductController;
use App\Http\Controllers\Api\Marketplace\OrderController;
use App\Http\Controllers\Api\Marketplace\OrderItemController;
use App\Http\Controllers\Api\Marketplace\CouponController;
use App\Http\Controllers\Api\Marketplace\TradelistingController;
use App\Http\Controllers\Api\Marketplace\TradeBidController;
use App\Http\Controllers\Api\Marketplace\TradeTransactionController;
use App\Http\Controllers\Api\Marketplace\CardPriceHistoryController;
use App\Http\Controllers\Api\Marketplace\TradeDisputeController;
use App\Http\Controllers\Api\Content\DraftSessionController;
use App\Http\Controllers\Api\Content\DraftParticipantController;
use App\Http\Controllers\Api\Content\DraftPickController;
use App\Http\Controllers\Api\Content\ArticleController;
use App\Http\Controllers\Api\Content\ArticleTagController;
use App\Http\Controllers\Api\Content\ArticleTagAssignmentController;
use App\Http\Controllers\Api\Content\ArticleCommentController;
use App\Http\Controllers\Api\Content\StreamController;

Route::apiResource('cards', CardController::class);
Route::post('cards/{card}/ban', [CardController::class, 'ban']);
Route::post('cards/{card}/unban', [CardController::class, 'unban']);
Route::post('cards/{card}/restrict', [CardController::class, 'restrict']);
Route::post('cards/{card}/unrestrict', [CardController::class, 'unrestrict']);
Route::get('cards/{card}/value', [CardController::class, 'calculateValue']);
Route::apiResource('card_sets', CardSetController::class);
Route::apiResource('card_rulings', CardRulingController::class);
Route::apiResource('card_abilities', CardAbilityController::class);
Route::apiResource('decks', DeckController::class);
Route::get('decks/{deck}/validate', [DeckController::class, 'validateSize']);
Route::post('decks/{deck}/clone', [DeckController::class, 'clone']);
Route::post('decks/{deck}/publish', [DeckController::class, 'publish']);
Route::post('decks/{deck}/unpublish', [DeckController::class, 'unpublish']);
Route::post('decks/{deck}/certify', [DeckController::class, 'certifyTournamentLegal']);
Route::apiResource('deck_cards', DeckCardController::class);
Route::apiResource('deck_sideboard_cards', DeckSideboardCardController::class);
Route::apiResource('deck_tags', DeckTagController::class);
Route::post('deck_tags/{deckTag}/merge', [DeckTagController::class, 'mergeInto']);
Route::apiResource('deck_tag_assignments', DeckTagAssignmentController::class);
Route::apiResource('players', PlayerController::class);
Route::post('players/{player}/promote', [PlayerController::class, 'promote']);
Route::post('players/{player}/demote', [PlayerController::class, 'demote']);
Route::post('players/{player}/win', [PlayerController::class, 'recordWin']);
Route::post('players/{player}/loss', [PlayerController::class, 'recordLoss']);
Route::get('players/{player}/win-rate', [PlayerController::class, 'winRate']);
Route::post('players/{player}/verify', [PlayerController::class, 'verify']);
Route::patch('players/{player}/rating', [PlayerController::class, 'updateRating']);
Route::apiResource('player_season_statses', PlayerSeasonStatsController::class);
Route::apiResource('player_collections', PlayerCollectionController::class);
Route::get('player_collections/{playerCollection}/value', [PlayerCollectionController::class, 'estimatedValue']);
Route::apiResource('friendships', FriendshipController::class);
Route::post('friendships/{friendship}/accept', [FriendshipController::class, 'accept']);
Route::post('friendships/{friendship}/decline', [FriendshipController::class, 'decline']);
Route::post('friendships/{friendship}/block', [FriendshipController::class, 'block']);
Route::apiResource('achievements', AchievementController::class);
Route::apiResource('player_achievements', PlayerAchievementController::class);
Route::apiResource('crafting_recipes', CraftingRecipeController::class);
Route::apiResource('crafting_ingredients', CraftingIngredientController::class);
Route::apiResource('seasons', SeasonController::class);
Route::post('seasons/{season}/activate', [SeasonController::class, 'activate']);
Route::post('seasons/{season}/deactivate', [SeasonController::class, 'deactivate']);
Route::post('seasons/{season}/finalize', [SeasonController::class, 'finalizeRewards']);
Route::apiResource('tournaments', TournamentController::class);
Route::post('tournaments/{tournament}/start', [TournamentController::class, 'start']);
Route::post('tournaments/{tournament}/cancel', [TournamentController::class, 'cancel']);
Route::post('tournaments/{tournament}/complete', [TournamentController::class, 'complete']);
Route::post('tournaments/{tournament}/rounds', [TournamentController::class, 'generateRound']);
Route::get('tournaments/{tournament}/prizes', [TournamentController::class, 'calculatePrizeDistribution']);
Route::apiResource('tournament_judges', TournamentJudgeController::class);
Route::apiResource('tournament_registrations', TournamentRegistrationController::class);
Route::post('tournament_registrations/{tournamentRegistration}/withdraw', [TournamentRegistrationController::class, 'withdraw']);
Route::post('tournament_registrations/{tournamentRegistration}/disqualify', [TournamentRegistrationController::class, 'disqualify']);
Route::post('tournament_registrations/{tournamentRegistration}/promote', [TournamentRegistrationController::class, 'promoteFromWaitlist']);
Route::apiResource('tournament_rounds', TournamentRoundController::class);
Route::post('tournament_rounds/{tournamentRound}/start', [TournamentRoundController::class, 'start']);
Route::post('tournament_rounds/{tournamentRound}/complete', [TournamentRoundController::class, 'complete']);
Route::post('tournament_rounds/{tournamentRound}/pairings', [TournamentRoundController::class, 'generatePairings']);
Route::apiResource('matches', MatchRecordController::class);
Route::post('matches/{matchRecord}/record', [MatchRecordController::class, 'recordResult']);
Route::get('matches/{matchRecord}/winner', [MatchRecordController::class, 'determineWinner']);
Route::post('matches/{matchRecord}/draw', [MatchRecordController::class, 'draw']);
Route::apiResource('games', GameController::class);
Route::post('games/{game}/winner', [GameController::class, 'recordWinner']);
Route::apiResource('tournament_prizes', TournamentPrizeController::class);
Route::apiResource('awarded_prizes', AwardedPrizeController::class);
Route::apiResource('products', ProductController::class);
Route::post('products/{product}/activate', [ProductController::class, 'activate']);
Route::post('products/{product}/deactivate', [ProductController::class, 'deactivate']);
Route::patch('products/{product}/discount', [ProductController::class, 'applyDiscount']);
Route::post('products/{product}/restock', [ProductController::class, 'restock']);
Route::apiResource('orders', OrderController::class);
Route::delete('orders/{order}/cancel', [OrderController::class, 'cancel']);
Route::post('orders/{order}/pay', [OrderController::class, 'pay']);
Route::get('orders/{order}/total', [OrderController::class, 'calculateTotal']);
Route::patch('orders/{order}/discount', [OrderController::class, 'applyDiscount']);
Route::post('orders/{order}/refund', [OrderController::class, 'refund']);
Route::apiResource('order_items', OrderItemController::class);
Route::apiResource('coupons', CouponController::class);
Route::post('coupons/{coupon}/redeem', [CouponController::class, 'redeem']);
Route::post('coupons/{coupon}/deactivate', [CouponController::class, 'deactivate']);
Route::apiResource('tradelistings', TradelistingController::class);
Route::post('tradelistings/{tradelisting}/close', [TradelistingController::class, 'close']);
Route::patch('tradelistings/{tradelisting}/extend', [TradelistingController::class, 'extend']);
Route::delete('tradelistings/{tradelisting}/cancel', [TradelistingController::class, 'cancel']);
Route::apiResource('trade_bids', TradeBidController::class);
Route::apiResource('trade_transactions', TradeTransactionController::class);
Route::post('trade_transactions/{tradeTransaction}/complete', [TradeTransactionController::class, 'complete']);
Route::post('trade_transactions/{tradeTransaction}/refund', [TradeTransactionController::class, 'refund']);
Route::post('trade_transactions/{tradeTransaction}/dispute', [TradeTransactionController::class, 'openDispute']);
Route::apiResource('card_price_histories', CardPriceHistoryController::class);
Route::apiResource('trade_disputes', TradeDisputeController::class);
Route::post('trade_disputes/{tradeDispute}/escalate', [TradeDisputeController::class, 'escalate']);
Route::post('trade_disputes/{tradeDispute}/resolve', [TradeDisputeController::class, 'resolve']);
Route::post('trade_disputes/{tradeDispute}/review', [TradeDisputeController::class, 'review']);
Route::apiResource('draft_sessions', DraftSessionController::class);
Route::post('draft_sessions/{draftSession}/start', [DraftSessionController::class, 'start']);
Route::post('draft_sessions/{draftSession}/abandon', [DraftSessionController::class, 'abandon']);
Route::post('draft_sessions/{draftSession}/complete', [DraftSessionController::class, 'complete']);
Route::apiResource('draft_participants', DraftParticipantController::class);
Route::post('draft_participants/{draftParticipant}/pick', [DraftParticipantController::class, 'pickCard']);
Route::apiResource('draft_picks', DraftPickController::class);
Route::apiResource('articles', ArticleController::class);
Route::post('articles/{article}/publish', [ArticleController::class, 'publish']);
Route::post('articles/{article}/archive', [ArticleController::class, 'archive']);
Route::post('articles/{article}/view', [ArticleController::class, 'incrementView']);
Route::apiResource('article_tags', ArticleTagController::class);
Route::apiResource('article_tag_assignments', ArticleTagAssignmentController::class);
Route::apiResource('article_comments', ArticleCommentController::class);
Route::post('article_comments/{articleComment}/hide', [ArticleCommentController::class, 'hide']);
Route::post('article_comments/{articleComment}/unhide', [ArticleCommentController::class, 'unhide']);
Route::apiResource('streams', StreamController::class);
Route::post('streams/{stream}/live', [StreamController::class, 'goLive']);
Route::post('streams/{stream}/end', [StreamController::class, 'end']);
Route::patch('streams/{stream}/viewers', [StreamController::class, 'updateViewerPeak']);
