<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI282wLJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI282wLJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI282wLJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI282wLJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI282wLJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'I282wLJ',
    'container.build_id' => '8ba94f3a',
    'container.build_time' => 1778167851,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI282wLJ');
