<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBux4PNG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBux4PNG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBux4PNG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBux4PNG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBux4PNG\App_KernelDevDebugContainer([
    'container.build_hash' => 'Bux4PNG',
    'container.build_id' => 'ea3455d1',
    'container.build_time' => 1778165948,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBux4PNG');
