# Generated by Django 5.0.14 on 2026-05-07 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('points', models.IntegerField(default=10)),
                ('rarity', models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Epic', 'Epic'), ('Legendary', 'Legendary')], default='Common', max_length=20)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Blocked', 'Blocked')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Friendship',
                'verbose_name_plural': 'Friendships',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CraftingIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_recipes', to='cards.card')),
            ],
            options={
                'verbose_name': 'Crafting Ingredient',
                'verbose_name_plural': 'Crafting Ingredients',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CraftingRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dust_cost', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('required_cards', models.ManyToManyField(through='players.CraftingIngredient', to='cards.card')),
                ('result_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crafting_recipes', to='cards.card')),
            ],
            options={
                'verbose_name': 'Crafting Recipe',
                'verbose_name_plural': 'Crafting Recipes',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='craftingingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='players.craftingrecipe'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('rank', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Master', 'Master'), ('Grandmaster', 'Grandmaster')], default='Bronze', max_length=20)),
                ('rating', models.IntegerField(default=1000)),
                ('peak_rating', models.IntegerField(default=1000)),
                ('bio', models.TextField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('preferred_format', models.CharField(blank=True, choices=[('Standard', 'Standard'), ('Extended', 'Extended'), ('Legacy', 'Legacy'), ('Vintage', 'Vintage'), ('Commander', 'Commander'), ('Draft', 'Draft')], max_length=20, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('friends', models.ManyToManyField(related_name='friends_of', through='players.Friendship', to='players.player')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='friendship',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to='players.player'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to='players.player'),
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField()),
                ('progress', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_records', to='players.achievement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_records', to='players.player')),
            ],
            options={
                'verbose_name': 'Player Achievement',
                'verbose_name_plural': 'Player Achievements',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='achievements',
            field=models.ManyToManyField(related_name='players', through='players.PlayerAchievement', to='players.achievement'),
        ),
        migrations.CreateModel(
            name='PlayerCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('foil', models.BooleanField(default=False)),
                ('condition', models.CharField(choices=[('Mint', 'Mint'), ('NearMint', 'Nearmint'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Played', 'Played')], default='Mint', max_length=20)),
                ('acquired_at', models.DateTimeField()),
                ('acquired_via', models.CharField(choices=[('Purchase', 'Purchase'), ('Trade', 'Trade'), ('TournamentReward', 'Tournamentreward'), ('Pack', 'Pack'), ('Craft', 'Craft')], default='Purchase', max_length=20)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_collections', to='cards.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='players.player')),
            ],
            options={
                'verbose_name': 'Player Collection',
                'verbose_name_plural': 'Player Collections',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('tournament_wins', models.IntegerField(default=0)),
                ('highest_rank', models.CharField(blank=True, choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Master', 'Master'), ('Grandmaster', 'Grandmaster')], max_length=20, null=True)),
                ('season_points', models.IntegerField(default=0)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
            options={
                'verbose_name': 'Player Season Stats',
                'verbose_name_plural': 'Player Season Statses',
                'ordering': ['-id'],
            },
        ),
    ]
