# Generated by Django 5.0.14 on 2026-05-07 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseasonstats',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='tournaments.season'),
        ),
        migrations.AddField(
            model_name='player',
            name='season_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.playerseasonstats'),
        ),
    ]
