import express from 'express';
import cors from 'cors';
import cardRouter from './routes/Cards/cards.js';
import cardSetRouter from './routes/Cards/card_sets.js';
import cardRulingRouter from './routes/Cards/card_rulings.js';
import cardAbilityRouter from './routes/Cards/card_abilities.js';
import deckRouter from './routes/Cards/decks.js';
import deckCardRouter from './routes/Cards/deck_cards.js';
import deckSideboardCardRouter from './routes/Cards/deck_sideboard_cards.js';
import deckTagRouter from './routes/Cards/deck_tags.js';
import deckTagAssignmentRouter from './routes/Cards/deck_tag_assignments.js';
import playerRouter from './routes/Players/players.js';
import playerSeasonStatsRouter from './routes/Players/player_season_statses.js';
import playerCollectionRouter from './routes/Players/player_collections.js';
import friendshipRouter from './routes/Players/friendships.js';
import achievementRouter from './routes/Players/achievements.js';
import playerAchievementRouter from './routes/Players/player_achievements.js';
import craftingRecipeRouter from './routes/Players/crafting_recipes.js';
import craftingIngredientRouter from './routes/Players/crafting_ingredients.js';
import seasonRouter from './routes/Tournaments/seasons.js';
import tournamentRouter from './routes/Tournaments/tournaments.js';
import tournamentJudgeRouter from './routes/Tournaments/tournament_judges.js';
import tournamentRegistrationRouter from './routes/Tournaments/tournament_registrations.js';
import tournamentRoundRouter from './routes/Tournaments/tournament_rounds.js';
import matchRouter from './routes/Tournaments/matches.js';
import gameRouter from './routes/Tournaments/games.js';
import tournamentPrizeRouter from './routes/Tournaments/tournament_prizes.js';
import awardedPrizeRouter from './routes/Tournaments/awarded_prizes.js';
import productRouter from './routes/Marketplace/products.js';
import orderRouter from './routes/Marketplace/orders.js';
import orderItemRouter from './routes/Marketplace/order_items.js';
import couponRouter from './routes/Marketplace/coupons.js';
import tradeListingRouter from './routes/Marketplace/trade_listings.js';
import tradeBidRouter from './routes/Marketplace/trade_bids.js';
import tradeTransactionRouter from './routes/Marketplace/trade_transactions.js';
import cardPriceHistoryRouter from './routes/Marketplace/card_price_histories.js';
import tradeDisputeRouter from './routes/Marketplace/trade_disputes.js';
import draftSessionRouter from './routes/Content/draft_sessions.js';
import draftParticipantRouter from './routes/Content/draft_participants.js';
import draftPickRouter from './routes/Content/draft_picks.js';
import articleRouter from './routes/Content/articles.js';
import articleTagRouter from './routes/Content/article_tags.js';
import articleTagAssignmentRouter from './routes/Content/article_tag_assignments.js';
import articleCommentRouter from './routes/Content/article_comments.js';
import streamRouter from './routes/Content/streams.js';

export const app = express();

app.use(cors());
app.use(express.json());

app.use('/api/cards', cardRouter);
app.use('/api/card_sets', cardSetRouter);
app.use('/api/card_rulings', cardRulingRouter);
app.use('/api/card_abilities', cardAbilityRouter);
app.use('/api/decks', deckRouter);
app.use('/api/deck_cards', deckCardRouter);
app.use('/api/deck_sideboard_cards', deckSideboardCardRouter);
app.use('/api/deck_tags', deckTagRouter);
app.use('/api/deck_tag_assignments', deckTagAssignmentRouter);
app.use('/api/players', playerRouter);
app.use('/api/player_season_statses', playerSeasonStatsRouter);
app.use('/api/player_collections', playerCollectionRouter);
app.use('/api/friendships', friendshipRouter);
app.use('/api/achievements', achievementRouter);
app.use('/api/player_achievements', playerAchievementRouter);
app.use('/api/crafting_recipes', craftingRecipeRouter);
app.use('/api/crafting_ingredients', craftingIngredientRouter);
app.use('/api/seasons', seasonRouter);
app.use('/api/tournaments', tournamentRouter);
app.use('/api/tournament_judges', tournamentJudgeRouter);
app.use('/api/tournament_registrations', tournamentRegistrationRouter);
app.use('/api/tournament_rounds', tournamentRoundRouter);
app.use('/api/matches', matchRouter);
app.use('/api/games', gameRouter);
app.use('/api/tournament_prizes', tournamentPrizeRouter);
app.use('/api/awarded_prizes', awardedPrizeRouter);
app.use('/api/products', productRouter);
app.use('/api/orders', orderRouter);
app.use('/api/order_items', orderItemRouter);
app.use('/api/coupons', couponRouter);
app.use('/api/trade_listings', tradeListingRouter);
app.use('/api/trade_bids', tradeBidRouter);
app.use('/api/trade_transactions', tradeTransactionRouter);
app.use('/api/card_price_histories', cardPriceHistoryRouter);
app.use('/api/trade_disputes', tradeDisputeRouter);
app.use('/api/draft_sessions', draftSessionRouter);
app.use('/api/draft_participants', draftParticipantRouter);
app.use('/api/draft_picks', draftPickRouter);
app.use('/api/articles', articleRouter);
app.use('/api/article_tags', articleTagRouter);
app.use('/api/article_tag_assignments', articleTagAssignmentRouter);
app.use('/api/article_comments', articleCommentRouter);
app.use('/api/streams', streamRouter);

app.get('/health', (_req, res) => res.json({ status: 'ok' }));
