CREATE TABLE IF NOT EXISTS player_collections (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  quantity INTEGER NOT NULL DEFAULT 1,
  foil BOOLEAN NOT NULL DEFAULT 0,
  condition VARCHAR NOT NULL DEFAULT 'Mint',
  acquired_at DATETIME NOT NULL,
  acquired_via VARCHAR NOT NULL DEFAULT 'Purchase',
  player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE SET NULL,
  card_id INTEGER NOT NULL REFERENCES cards(id) ON DELETE SET NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
