CREATE TABLE IF NOT EXISTS article_comments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  body TEXT NOT NULL,
  is_hidden BOOLEAN NOT NULL DEFAULT 0,
  article_id INTEGER REFERENCES articles(id) ON DELETE SET NULL,
  author_id INTEGER NOT NULL REFERENCES players(id) ON DELETE SET NULL,
  parent_comment_id INTEGER REFERENCES article_comments(id) ON DELETE SET NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
