CREATE TABLE IF NOT EXISTS decks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR NOT NULL,
  description TEXT,
  format VARCHAR NOT NULL DEFAULT 'Standard',
  is_public BOOLEAN NOT NULL DEFAULT 0,
  is_tournament_legal BOOLEAN NOT NULL DEFAULT 0,
  archetype VARCHAR,
  wins INTEGER NOT NULL DEFAULT 0,
  losses INTEGER NOT NULL DEFAULT 0,
  player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE SET NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
