CREATE TABLE IF NOT EXISTS achievements (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR NOT NULL,
  description TEXT NOT NULL,
  icon_url VARCHAR,
  points INTEGER NOT NULL DEFAULT 10,
  rarity VARCHAR NOT NULL DEFAULT 'Common',
  is_hidden BOOLEAN NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
