CREATE TABLE IF NOT EXISTS draft_picks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pick_number INTEGER NOT NULL,
  pack_number INTEGER NOT NULL,
  picked_at DATETIME NOT NULL,
  participant_id INTEGER NOT NULL REFERENCES draft_participants(id) ON DELETE SET NULL,
  card_id INTEGER NOT NULL REFERENCES cards(id) ON DELETE SET NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
