CREATE TABLE IF NOT EXISTS articles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR NOT NULL,
  slug VARCHAR NOT NULL UNIQUE,
  body TEXT NOT NULL,
  excerpt TEXT,
  cover_image_url VARCHAR,
  status VARCHAR NOT NULL DEFAULT 'Draft',
  article_type VARCHAR NOT NULL DEFAULT 'Guide',
  language VARCHAR NOT NULL DEFAULT 'EN',
  view_count INTEGER NOT NULL DEFAULT 0,
  likes_count INTEGER NOT NULL DEFAULT 0,
  is_featured BOOLEAN NOT NULL DEFAULT 0,
  published_at DATETIME,
  author_id INTEGER NOT NULL REFERENCES players(id) ON DELETE RESTRICT,
  featured_deck_id INTEGER REFERENCES decks(id) ON DELETE SET NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
