CREATE TABLE IF NOT EXISTS deck_cards (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  quantity INTEGER NOT NULL DEFAULT 1,
  is_commander BOOLEAN NOT NULL DEFAULT 0,
  deck_id INTEGER NOT NULL REFERENCES decks(id) ON DELETE SET NULL,
  card_id INTEGER NOT NULL REFERENCES cards(id) ON DELETE SET NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
