CREATE TABLE IF NOT EXISTS cards (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR NOT NULL,
  card_type VARCHAR NOT NULL DEFAULT 'Creature',
  rarity VARCHAR NOT NULL DEFAULT 'Common',
  mana_cost INTEGER NOT NULL DEFAULT 0,
  mana_colors VARCHAR NOT NULL,
  attack INTEGER,
  defense INTEGER,
  loyalty INTEGER,
  description TEXT NOT NULL,
  flavor_text TEXT,
  image_url VARCHAR,
  artist_name VARCHAR,
  legal_formats VARCHAR NOT NULL,
  is_banned BOOLEAN NOT NULL DEFAULT 0,
  is_restricted BOOLEAN NOT NULL DEFAULT 0,
  power_level INTEGER NOT NULL DEFAULT 1,
  set_id INTEGER NOT NULL REFERENCES card_sets(id) ON DELETE SET NULL,
  rulings_id INTEGER REFERENCES card_rulings(id) ON DELETE SET NULL,
  abilities_id INTEGER REFERENCES card_abilities(id) ON DELETE SET NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
