CREATE TABLE IF NOT EXISTS tournament_rounds (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  round_number INTEGER NOT NULL,
  status VARCHAR NOT NULL DEFAULT 'Pending',
  started_at DATETIME,
  ended_at DATETIME,
  time_limit_minutes INTEGER NOT NULL DEFAULT 50,
  tournament_id INTEGER NOT NULL REFERENCES tournaments(id) ON DELETE SET NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
