CREATE TABLE IF NOT EXISTS draft_participants (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  seat_number INTEGER NOT NULL,
  joined_at DATETIME NOT NULL,
  session_id INTEGER REFERENCES draft_sessions(id) ON DELETE SET NULL,
  player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE SET NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
