CREATE TABLE IF NOT EXISTS tournament_registrations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  status VARCHAR NOT NULL DEFAULT 'Registered',
  seed INTEGER,
  final_standing INTEGER,
  points_earned INTEGER NOT NULL DEFAULT 0,
  registered_at DATETIME NOT NULL,
  tournament_id INTEGER NOT NULL REFERENCES tournaments(id) ON DELETE SET NULL,
  player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE SET NULL,
  deck_id INTEGER NOT NULL REFERENCES decks(id) ON DELETE SET NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
