CREATE TABLE IF NOT EXISTS trade_bids (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  amount DECIMAL NOT NULL,
  placed_at DATETIME NOT NULL,
  is_winning BOOLEAN NOT NULL DEFAULT 0,
  listing_id INTEGER NOT NULL REFERENCES trade_listings(id) ON DELETE CASCADE,
  bidder_id INTEGER NOT NULL REFERENCES players(id) ON DELETE RESTRICT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
