CREATE TABLE IF NOT EXISTS player_season_statses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  wins INTEGER NOT NULL DEFAULT 0,
  losses INTEGER NOT NULL DEFAULT 0,
  draws INTEGER NOT NULL DEFAULT 0,
  tournament_wins INTEGER NOT NULL DEFAULT 0,
  highest_rank VARCHAR,
  season_points INTEGER NOT NULL DEFAULT 0,
  player_id INTEGER REFERENCES players(id) ON DELETE SET NULL,
  season_id INTEGER NOT NULL REFERENCES seasons(id) ON DELETE SET NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
