CREATE TABLE IF NOT EXISTS awarded_prizes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  final_placement INTEGER NOT NULL,
  awarded_at DATETIME NOT NULL,
  claimed BOOLEAN NOT NULL DEFAULT 0,
  claimed_at DATETIME,
  prize_id INTEGER NOT NULL REFERENCES tournament_prizes(id) ON DELETE SET NULL,
  player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE SET NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
