CREATE TABLE IF NOT EXISTS card_sets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR NOT NULL,
  code VARCHAR NOT NULL,
  release_date DATE NOT NULL,
  set_type VARCHAR NOT NULL DEFAULT 'Expansion',
  total_cards INTEGER NOT NULL,
  description TEXT,
  logo_url VARCHAR,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
