CREATE TABLE IF NOT EXISTS tournament_judges (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  role VARCHAR NOT NULL DEFAULT 'Judge',
  tournament_id INTEGER NOT NULL REFERENCES tournaments(id) ON DELETE SET NULL,
  player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE SET NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
