CREATE TABLE IF NOT EXISTS friendships (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  status VARCHAR NOT NULL DEFAULT 'Pending',
  requester_id INTEGER NOT NULL REFERENCES players(id) ON DELETE SET NULL,
  receiver_id INTEGER NOT NULL REFERENCES players(id) ON DELETE SET NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
