CREATE TABLE IF NOT EXISTS card_abilities (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ability_type VARCHAR NOT NULL DEFAULT 'Keyword',
  keyword VARCHAR,
  ability_text TEXT NOT NULL,
  timing VARCHAR,
  card_id INTEGER NOT NULL REFERENCES cards(id) ON DELETE SET NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
