CREATE TABLE IF NOT EXISTS matches (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  table_number INTEGER,
  status VARCHAR NOT NULL DEFAULT 'Pending',
  player1_wins INTEGER NOT NULL DEFAULT 0,
  player2_wins INTEGER NOT NULL DEFAULT 0,
  started_at DATETIME,
  ended_at DATETIME,
  result_notes TEXT,
  round_id INTEGER REFERENCES tournament_rounds(id) ON DELETE SET NULL,
  player1_id INTEGER NOT NULL REFERENCES players(id) ON DELETE SET NULL,
  player2_id INTEGER REFERENCES players(id) ON DELETE SET NULL,
  games_id INTEGER REFERENCES games(id) ON DELETE SET NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
