CREATE TABLE IF NOT EXISTS products (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR NOT NULL,
  product_type VARCHAR NOT NULL DEFAULT 'SingleCard',
  price DECIMAL NOT NULL,
  stock INTEGER NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT 1,
  discount_percent INTEGER NOT NULL DEFAULT 0,
  description TEXT,
  image_url VARCHAR,
  featured BOOLEAN NOT NULL DEFAULT 0,
  card_id INTEGER REFERENCES cards(id) ON DELETE SET NULL,
  card_set_id INTEGER REFERENCES card_sets(id) ON DELETE SET NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
