CREATE TABLE IF NOT EXISTS card_price_histories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  price_date DATE NOT NULL,
  avg_price DECIMAL NOT NULL,
  min_price DECIMAL NOT NULL,
  max_price DECIMAL NOT NULL,
  volume INTEGER NOT NULL,
  foil BOOLEAN NOT NULL DEFAULT 0,
  card_id INTEGER NOT NULL REFERENCES cards(id) ON DELETE SET NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
