CREATE TABLE IF NOT EXISTS deck_tag_assignments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  deck_id INTEGER NOT NULL REFERENCES decks(id) ON DELETE SET NULL,
  tag_id INTEGER NOT NULL REFERENCES deck_tags(id) ON DELETE SET NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
