CREATE TABLE IF NOT EXISTS trade_transactions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  final_price DECIMAL NOT NULL,
  platform_fee DECIMAL NOT NULL,
  status VARCHAR NOT NULL DEFAULT 'Pending',
  completed_at DATETIME,
  listing_id INTEGER NOT NULL UNIQUE REFERENCES trade_listings(id) ON DELETE RESTRICT,
  buyer_id INTEGER NOT NULL REFERENCES players(id) ON DELETE RESTRICT,
  seller_id INTEGER NOT NULL REFERENCES players(id) ON DELETE RESTRICT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
