CREATE TABLE IF NOT EXISTS card_rulings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ruling_text TEXT NOT NULL,
  published_at DATE NOT NULL,
  source VARCHAR NOT NULL,
  card_id INTEGER NOT NULL REFERENCES cards(id) ON DELETE SET NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
