# Generated by Django 5.0.14 on 2026-05-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], default='Draft', max_length=20)),
                ('article_type', models.CharField(choices=[('Guide', 'Guide'), ('Tierlist', 'Tierlist'), ('Matchup', 'Matchup'), ('News', 'News'), ('Spotlight', 'Spotlight'), ('Decklist', 'Decklist')], default='Guide', max_length=20)),
                ('view_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Article Comment',
                'verbose_name_plural': 'Article Comments',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Article Tag',
                'verbose_name_plural': 'Article Tags',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Article Tag Assignment',
                'verbose_name_plural': 'Article Tag Assignments',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DraftParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('joined_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Draft Participant',
                'verbose_name_plural': 'Draft Participants',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_number', models.IntegerField()),
                ('pack_number', models.IntegerField()),
                ('picked_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Draft Pick',
                'verbose_name_plural': 'Draft Picks',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DraftSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WaitingForPlayers', 'Waitingforplayers'), ('Drafting', 'Drafting'), ('Completed', 'Completed'), ('Abandoned', 'Abandoned')], default='WaitingForPlayers', max_length=20)),
                ('draft_type', models.CharField(choices=[('Booster', 'Booster'), ('Cube', 'Cube'), ('Rochester', 'Rochester')], default='Booster', max_length=20)),
                ('seats', models.IntegerField(default=8)),
                ('created_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Draft Session',
                'verbose_name_plural': 'Draft Sessions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('stream_url', models.URLField()),
                ('platform', models.CharField(choices=[('Twitch', 'Twitch'), ('YouTube', 'Youtube'), ('KickStream', 'Kickstream'), ('Platform', 'Platform')], default='Twitch', max_length=20)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Live', 'Live'), ('Ended', 'Ended')], default='Scheduled', max_length=20)),
                ('viewer_count_peak', models.IntegerField(default=0)),
                ('scheduled_start', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('vod_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Stream',
                'verbose_name_plural': 'Streams',
                'ordering': ['-id'],
            },
        ),
    ]
