# Generated by Django 5.0.14 on 2026-05-07 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0002_initial'),
        ('content', '0001_initial'),
        ('players', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='players.player'),
        ),
        migrations.AddField(
            model_name='article',
            name='featured_deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='cards.deck'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.article'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='players.player'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='content.articlecomment'),
        ),
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.articlecomment'),
        ),
        migrations.AddField(
            model_name='articletagassignment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='content.article'),
        ),
        migrations.AddField(
            model_name='articletagassignment',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_assignments', to='content.articletag'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(through='content.ArticleTagAssignment', to='content.articletag'),
        ),
        migrations.AddField(
            model_name='draftparticipant',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_sessions', to='players.player'),
        ),
        migrations.AddField(
            model_name='draftpick',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='cards.card'),
        ),
        migrations.AddField(
            model_name='draftpick',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='content.draftparticipant'),
        ),
        migrations.AddField(
            model_name='draftparticipant',
            name='drafted_cards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.draftpick'),
        ),
        migrations.AddField(
            model_name='draftsession',
            name='card_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_sessions', to='cards.cardset'),
        ),
        migrations.AddField(
            model_name='draftsession',
            name='participants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.draftparticipant'),
        ),
        migrations.AddField(
            model_name='draftparticipant',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.draftsession'),
        ),
        migrations.AddField(
            model_name='stream',
            name='streamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='players.player'),
        ),
        migrations.AddField(
            model_name='stream',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='tournaments.tournament'),
        ),
    ]
