<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GaCqPI8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GaCqPI8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GaCqPI8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'player' => ['privates', '.errored..service_locator.GaCqPI8.App\\Entity\\Players\\Player', NULL, 'Cannot autowire service ".service_locator.GaCqPI8": it needs an instance of "App\\Entity\\Players\\Player" but this type has been excluded in "config/services.yaml".'],
        ], [
            'player' => 'App\\Entity\\Players\\Player',
        ]);
    }
}
