<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VYnVyKfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vYnVyKf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vYnVyKf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cardPriceHistory' => ['privates', '.errored..service_locator.vYnVyKf.App\\Entity\\Marketplace\\CardPriceHistory', NULL, 'Cannot autowire service ".service_locator.vYnVyKf": it needs an instance of "App\\Entity\\Marketplace\\CardPriceHistory" but this type has been excluded in "config/services.yaml".'],
        ], [
            'cardPriceHistory' => 'App\\Entity\\Marketplace\\CardPriceHistory',
        ]);
    }
}
