<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F1KWirMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F1KWirM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F1KWirM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'season' => ['privates', '.errored..service_locator.F1KWirM.App\\Entity\\Tournaments\\Season', NULL, 'Cannot autowire service ".service_locator.F1KWirM": it needs an instance of "App\\Entity\\Tournaments\\Season" but this type has been excluded in "config/services.yaml".'],
        ], [
            'season' => 'App\\Entity\\Tournaments\\Season',
        ]);
    }
}
