<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VCzFVpfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vCzFVpf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vCzFVpf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cardSet' => ['privates', '.errored..service_locator.vCzFVpf.App\\Entity\\Cards\\CardSet', NULL, 'Cannot autowire service ".service_locator.vCzFVpf": it needs an instance of "App\\Entity\\Cards\\CardSet" but this type has been excluded in "config/services.yaml".'],
        ], [
            'cardSet' => 'App\\Entity\\Cards\\CardSet',
        ]);
    }
}
