<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4qIwCKDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4qIwCKD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4qIwCKD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tournamentJudge' => ['privates', '.errored..service_locator.4qIwCKD.App\\Entity\\Tournaments\\TournamentJudge', NULL, 'Cannot autowire service ".service_locator.4qIwCKD": it needs an instance of "App\\Entity\\Tournaments\\TournamentJudge" but this type has been excluded in "config/services.yaml".'],
        ], [
            'tournamentJudge' => 'App\\Entity\\Tournaments\\TournamentJudge',
        ]);
    }
}
