<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4lt7yIwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4lt7yIw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4lt7yIw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tournamentRegistration' => ['privates', '.errored..service_locator.4lt7yIw.App\\Entity\\Tournaments\\TournamentRegistration', NULL, 'Cannot autowire service ".service_locator.4lt7yIw": it needs an instance of "App\\Entity\\Tournaments\\TournamentRegistration" but this type has been excluded in "config/services.yaml".'],
        ], [
            'tournamentRegistration' => 'App\\Entity\\Tournaments\\TournamentRegistration',
        ]);
    }
}
