<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__7xBimdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..7xBimd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..7xBimd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'draftParticipant' => ['privates', '.errored..service_locator..7xBimd.App\\Entity\\Content\\DraftParticipant', NULL, 'Cannot autowire service ".service_locator..7xBimd": it needs an instance of "App\\Entity\\Content\\DraftParticipant" but this type has been excluded in "config/services.yaml".'],
        ], [
            'draftParticipant' => 'App\\Entity\\Content\\DraftParticipant',
        ]);
    }
}
