<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YlPAFu6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ylPAFu6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ylPAFu6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coupon' => ['privates', '.errored..service_locator.ylPAFu6.App\\Entity\\Marketplace\\Coupon', NULL, 'Cannot autowire service ".service_locator.ylPAFu6": it needs an instance of "App\\Entity\\Marketplace\\Coupon" but this type has been excluded in "config/services.yaml".'],
        ], [
            'coupon' => 'App\\Entity\\Marketplace\\Coupon',
        ]);
    }
}
