<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SzWXwXJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SzWXwXJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SzWXwXJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'stream' => ['privates', '.errored..service_locator.SzWXwXJ.App\\Entity\\Content\\Stream', NULL, 'Cannot autowire service ".service_locator.SzWXwXJ": it needs an instance of "App\\Entity\\Content\\Stream" but this type has been excluded in "config/services.yaml".'],
        ], [
            'stream' => 'App\\Entity\\Content\\Stream',
        ]);
    }
}
