<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OS6i8aRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OS6i8aR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OS6i8aR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'achievement' => ['privates', '.errored..service_locator.OS6i8aR.App\\Entity\\Players\\Achievement', NULL, 'Cannot autowire service ".service_locator.OS6i8aR": it needs an instance of "App\\Entity\\Players\\Achievement" but this type has been excluded in "config/services.yaml".'],
        ], [
            'achievement' => 'App\\Entity\\Players\\Achievement',
        ]);
    }
}
