<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZqunVNrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZqunVNr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZqunVNr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'playerCollection' => ['privates', '.errored..service_locator.ZqunVNr.App\\Entity\\Players\\PlayerCollection', NULL, 'Cannot autowire service ".service_locator.ZqunVNr": it needs an instance of "App\\Entity\\Players\\PlayerCollection" but this type has been excluded in "config/services.yaml".'],
        ], [
            'playerCollection' => 'App\\Entity\\Players\\PlayerCollection',
        ]);
    }
}
