<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AoBjn_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ao_Bjn.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ao_Bjn.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'deckCard' => ['privates', '.errored..service_locator.ao_Bjn..App\\Entity\\Cards\\DeckCard', NULL, 'Cannot autowire service ".service_locator.ao_Bjn.": it needs an instance of "App\\Entity\\Cards\\DeckCard" but this type has been excluded in "config/services.yaml".'],
        ], [
            'deckCard' => 'App\\Entity\\Cards\\DeckCard',
        ]);
    }
}
