<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5F6mFwtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5F6mFwt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5F6mFwt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'awardedPrize' => ['privates', '.errored..service_locator.5F6mFwt.App\\Entity\\Tournaments\\AwardedPrize', NULL, 'Cannot autowire service ".service_locator.5F6mFwt": it needs an instance of "App\\Entity\\Tournaments\\AwardedPrize" but this type has been excluded in "config/services.yaml".'],
        ], [
            'awardedPrize' => 'App\\Entity\\Tournaments\\AwardedPrize',
        ]);
    }
}
