<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fo7DBVxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Fo7DBVx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Fo7DBVx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'deckSideboardCard' => ['privates', '.errored..service_locator.Fo7DBVx.App\\Entity\\Cards\\DeckSideboardCard', NULL, 'Cannot autowire service ".service_locator.Fo7DBVx": it needs an instance of "App\\Entity\\Cards\\DeckSideboardCard" but this type has been excluded in "config/services.yaml".'],
        ], [
            'deckSideboardCard' => 'App\\Entity\\Cards\\DeckSideboardCard',
        ]);
    }
}
