<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yy4sAMGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yy4sAMG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yy4sAMG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cardRuling' => ['privates', '.errored..service_locator.yy4sAMG.App\\Entity\\Cards\\CardRuling', NULL, 'Cannot autowire service ".service_locator.yy4sAMG": it needs an instance of "App\\Entity\\Cards\\CardRuling" but this type has been excluded in "config/services.yaml".'],
        ], [
            'cardRuling' => 'App\\Entity\\Cards\\CardRuling',
        ]);
    }
}
