<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAwardedPrizeControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5F6mFwt.App\Controller\Api\Tournaments\AwardedPrizeController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5F6mFwt.App\\Controller\\Api\\Tournaments\\AwardedPrizeController::update()'] = ($container->privates['.service_locator.5F6mFwt'] ?? $container->load('get_ServiceLocator_5F6mFwtService'))->withContext('App\\Controller\\Api\\Tournaments\\AwardedPrizeController::update()', $container);
    }
}
