<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleTagControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Content\ArticleTagController' shared autowired service.
     *
     * @return \App\Controller\Api\Content\ArticleTagController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Content/ArticleTagController.php';

        $container->services['App\\Controller\\Api\\Content\\ArticleTagController'] = $instance = new \App\Controller\Api\Content\ArticleTagController(($container->privates['App\\Repository\\Content\\ArticleTagRepository'] ?? $container->load('getArticleTagRepositoryService')), ($container->privates['validator'] ?? self::getValidatorService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\Content\\ArticleTagController', $container));

        return $instance;
    }
}
