<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..SXF0ho.App\Entity\Content\Article' shared service.
     *
     * @return \App\Entity\Content\Article
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..SXF0ho": it needs an instance of "App\\Entity\\Content\\Article" but this type has been excluded in "config/services.yaml".');
    }
}
