<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleTagService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VnBharR.App\Entity\Content\ArticleTag' shared service.
     *
     * @return \App\Entity\Content\ArticleTag
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.VnBharR": it needs an instance of "App\\Entity\\Content\\ArticleTag" but this type has been excluded in "config/services.yaml".');
    }
}
