<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAwardedPrizeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Tournaments\AwardedPrizeController' shared autowired service.
     *
     * @return \App\Controller\Api\Tournaments\AwardedPrizeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Tournaments/AwardedPrizeController.php';

        $container->services['App\\Controller\\Api\\Tournaments\\AwardedPrizeController'] = $instance = new \App\Controller\Api\Tournaments\AwardedPrizeController(($container->privates['App\\Repository\\Tournaments\\AwardedPrizeRepository'] ?? $container->load('getAwardedPrizeRepositoryService')), ($container->privates['validator'] ?? self::getValidatorService($container)), ($container->privates['App\\Repository\\Tournaments\\TournamentPrizeRepository'] ?? $container->load('getTournamentPrizeRepositoryService')), ($container->privates['App\\Repository\\Players\\PlayerRepository'] ?? $container->load('getPlayerRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\Tournaments\\AwardedPrizeController', $container));

        return $instance;
    }
}
