<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAwardedPrizeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5F6mFwt.App\Entity\Tournaments\AwardedPrize' shared service.
     *
     * @return \App\Entity\Tournaments\AwardedPrize
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.5F6mFwt": it needs an instance of "App\\Entity\\Tournaments\\AwardedPrize" but this type has been excluded in "config/services.yaml".');
    }
}
