<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..SXF0ho.App\Controller\Api\Content\ArticleController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..SXF0ho.App\\Controller\\Api\\Content\\ArticleController::update()'] = ($container->privates['.service_locator..SXF0ho'] ?? $container->load('get_ServiceLocator__SXF0hoService'))->withContext('App\\Controller\\Api\\Content\\ArticleController::update()', $container);
    }
}
