<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Cards\CardController' shared autowired service.
     *
     * @return \App\Controller\Api\Cards\CardController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Cards/CardController.php';

        $container->services['App\\Controller\\Api\\Cards\\CardController'] = $instance = new \App\Controller\Api\Cards\CardController(($container->privates['App\\Repository\\Cards\\CardRepository'] ?? $container->load('getCardRepositoryService')), ($container->privates['validator'] ?? self::getValidatorService($container)), ($container->privates['App\\Repository\\Cards\\CardSetRepository'] ?? $container->load('getCardSetRepositoryService')), ($container->privates['App\\Repository\\Cards\\CardRulingRepository'] ?? $container->load('getCardRulingRepositoryService')), ($container->privates['App\\Repository\\Cards\\CardAbilityRepository'] ?? $container->load('getCardAbilityRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\Cards\\CardController', $container));

        return $instance;
    }
}
