<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardSetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vCzFVpf.App\Entity\Cards\CardSet' shared service.
     *
     * @return \App\Entity\Cards\CardSet
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.vCzFVpf": it needs an instance of "App\\Entity\\Cards\\CardSet" but this type has been excluded in "config/services.yaml".');
    }
}
