<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCouponService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ylPAFu6.App\Entity\Marketplace\Coupon' shared service.
     *
     * @return \App\Entity\Marketplace\Coupon
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ylPAFu6": it needs an instance of "App\\Entity\\Marketplace\\Coupon" but this type has been excluded in "config/services.yaml".');
    }
}
