<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCraftingRecipeControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x1Xw1ll.App\Controller\Api\Players\CraftingRecipeController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x1Xw1ll.App\\Controller\\Api\\Players\\CraftingRecipeController::update()'] = ($container->privates['.service_locator.x1Xw1ll'] ?? $container->load('get_ServiceLocator_X1Xw1llService'))->withContext('App\\Controller\\Api\\Players\\CraftingRecipeController::update()', $container);
    }
}
