<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardSetControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vCzFVpf.App\Controller\Api\Cards\CardSetController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vCzFVpf.App\\Controller\\Api\\Cards\\CardSetController::show()'] = ($container->privates['.service_locator.vCzFVpf'] ?? $container->load('get_ServiceLocator_VCzFVpfService'))->withContext('App\\Controller\\Api\\Cards\\CardSetController::show()', $container);
    }
}
