<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCraftingIngredientControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Players\CraftingIngredientController' shared autowired service.
     *
     * @return \App\Controller\Api\Players\CraftingIngredientController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Players/CraftingIngredientController.php';

        $container->services['App\\Controller\\Api\\Players\\CraftingIngredientController'] = $instance = new \App\Controller\Api\Players\CraftingIngredientController(($container->privates['App\\Repository\\Players\\CraftingIngredientRepository'] ?? $container->load('getCraftingIngredientRepositoryService')), ($container->privates['validator'] ?? self::getValidatorService($container)), ($container->privates['App\\Repository\\Players\\CraftingRecipeRepository'] ?? $container->load('getCraftingRecipeRepositoryService')), ($container->privates['App\\Repository\\Cards\\CardRepository'] ?? $container->load('getCardRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\Players\\CraftingIngredientController', $container));

        return $instance;
    }
}
