<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeckControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Cards\DeckController' shared autowired service.
     *
     * @return \App\Controller\Api\Cards\DeckController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Cards/DeckController.php';

        $container->services['App\\Controller\\Api\\Cards\\DeckController'] = $instance = new \App\Controller\Api\Cards\DeckController(($container->privates['App\\Repository\\Cards\\DeckRepository'] ?? $container->load('getDeckRepositoryService')), ($container->privates['validator'] ?? self::getValidatorService($container)), ($container->privates['App\\Repository\\Players\\PlayerRepository'] ?? $container->load('getPlayerRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\Cards\\DeckController', $container));

        return $instance;
    }
}
