<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeckCardControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ao_Bjn..App\Controller\Api\Cards\DeckCardController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ao_Bjn..App\\Controller\\Api\\Cards\\DeckCardController::show()'] = ($container->privates['.service_locator.ao_Bjn.'] ?? $container->load('get_ServiceLocator_AoBjn_Service'))->withContext('App\\Controller\\Api\\Cards\\DeckCardController::show()', $container);
    }
}
