<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeckCardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ao_Bjn..App\Entity\Cards\DeckCard' shared service.
     *
     * @return \App\Entity\Cards\DeckCard
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ao_Bjn.": it needs an instance of "App\\Entity\\Cards\\DeckCard" but this type has been excluded in "config/services.yaml".');
    }
}
