<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeckTagAssignmentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._ulNA7Q.App\Entity\Cards\DeckTagAssignment' shared service.
     *
     * @return \App\Entity\Cards\DeckTagAssignment
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator._ulNA7Q": it needs an instance of "App\\Entity\\Cards\\DeckTagAssignment" but this type has been excluded in "config/services.yaml".');
    }
}
