<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDraftParticipantControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Content\DraftParticipantController' shared autowired service.
     *
     * @return \App\Controller\Api\Content\DraftParticipantController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Content/DraftParticipantController.php';

        $container->services['App\\Controller\\Api\\Content\\DraftParticipantController'] = $instance = new \App\Controller\Api\Content\DraftParticipantController(($container->privates['App\\Repository\\Content\\DraftParticipantRepository'] ?? $container->load('getDraftParticipantRepositoryService')), ($container->privates['validator'] ?? self::getValidatorService($container)), ($container->privates['App\\Repository\\Content\\DraftSessionRepository'] ?? $container->load('getDraftSessionRepositoryService')), ($container->privates['App\\Repository\\Players\\PlayerRepository'] ?? $container->load('getPlayerRepositoryService')), ($container->privates['App\\Repository\\Content\\DraftPickRepository'] ?? $container->load('getDraftPickRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\Content\\DraftParticipantController', $container));

        return $instance;
    }
}
