<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeckTagAssignmentControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Cards\DeckTagAssignmentController' shared autowired service.
     *
     * @return \App\Controller\Api\Cards\DeckTagAssignmentController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Cards/DeckTagAssignmentController.php';

        $container->services['App\\Controller\\Api\\Cards\\DeckTagAssignmentController'] = $instance = new \App\Controller\Api\Cards\DeckTagAssignmentController(($container->privates['App\\Repository\\Cards\\DeckTagAssignmentRepository'] ?? $container->load('getDeckTagAssignmentRepositoryService')), ($container->privates['validator'] ?? self::getValidatorService($container)), ($container->privates['App\\Repository\\Cards\\DeckRepository'] ?? $container->load('getDeckRepositoryService')), ($container->privates['App\\Repository\\Cards\\DeckTagRepository'] ?? $container->load('getDeckTagRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\Cards\\DeckTagAssignmentController', $container));

        return $instance;
    }
}
