<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeckControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.b9yc7Tj.App\Controller\Api\Cards\DeckController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.b9yc7Tj.App\\Controller\\Api\\Cards\\DeckController::update()'] = ($container->privates['.service_locator.b9yc7Tj'] ?? $container->load('get_ServiceLocator_B9yc7TjService'))->withContext('App\\Controller\\Api\\Cards\\DeckController::update()', $container);
    }
}
