<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeckTagService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.pYBAu.N.App\Entity\Cards\DeckTag' shared service.
     *
     * @return \App\Entity\Cards\DeckTag
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.pYBAu.N": it needs an instance of "App\\Entity\\Cards\\DeckTag" but this type has been excluded in "config/services.yaml".');
    }
}
