<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_TypeDescriber_TemplateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'nelmio_api_doc.type_describer.template' shared service.
     *
     * @return \Nelmio\ApiDocBundle\TypeDescriber\TemplateDescriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/api-doc-bundle/src/TypeDescriber/TypeDescriberInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/api-doc-bundle/src/TypeDescriber/TypeDescriberAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/api-doc-bundle/src/TypeDescriber/TypeDescriberAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/api-doc-bundle/src/TypeDescriber/TemplateDescriber.php';

        $a = ($container->privates['nelmio_api_doc.type_describer.chain'] ?? $container->load('getNelmioApiDoc_TypeDescriber_ChainService'));

        if (isset($container->privates['nelmio_api_doc.type_describer.template'])) {
            return $container->privates['nelmio_api_doc.type_describer.template'];
        }

        $instance = new \Nelmio\ApiDocBundle\TypeDescriber\TemplateDescriber($a);

        if (isset($container->privates['nelmio_api_doc.type_describer.template'])) {
            return $container->privates['nelmio_api_doc.type_describer.template'];
        }

        return $container->privates['nelmio_api_doc.type_describer.template'] = $instance;
    }
}
