<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderItemControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XvaGv9f.App\Controller\Api\Marketplace\OrderItemController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XvaGv9f.App\\Controller\\Api\\Marketplace\\OrderItemController::update()'] = ($container->privates['.service_locator.XvaGv9f'] ?? $container->load('get_ServiceLocator_XvaGv9fService'))->withContext('App\\Controller\\Api\\Marketplace\\OrderItemController::update()', $container);
    }
}
