<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ldzNegH.App\Controller\Api\Marketplace\OrderController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ldzNegH.App\\Controller\\Api\\Marketplace\\OrderController::delete()'] = ($container->privates['.service_locator.ldzNegH'] ?? $container->load('get_ServiceLocator_LdzNegHService'))->withContext('App\\Controller\\Api\\Marketplace\\OrderController::delete()', $container);
    }
}
