<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ldzNegH.App\Entity\Marketplace\Order' shared service.
     *
     * @return \App\Entity\Marketplace\Order
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ldzNegH": it needs an instance of "App\\Entity\\Marketplace\\Order" but this type has been excluded in "config/services.yaml".');
    }
}
