<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerCollectionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ZqunVNr.App\Entity\Players\PlayerCollection' shared service.
     *
     * @return \App\Entity\Players\PlayerCollection
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ZqunVNr": it needs an instance of "App\\Entity\\Players\\PlayerCollection" but this type has been excluded in "config/services.yaml".');
    }
}
