<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GaCqPI8.App\Controller\Api\Players\PlayerController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GaCqPI8.App\\Controller\\Api\\Players\\PlayerController::update()'] = ($container->privates['.service_locator.GaCqPI8'] ?? $container->load('get_ServiceLocator_GaCqPI8Service'))->withContext('App\\Controller\\Api\\Players\\PlayerController::update()', $container);
    }
}
