<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerAchievementControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ly8pRDZ.App\Controller\Api\Players\PlayerAchievementController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ly8pRDZ.App\\Controller\\Api\\Players\\PlayerAchievementController::delete()'] = ($container->privates['.service_locator.Ly8pRDZ'] ?? $container->load('get_ServiceLocator_Ly8pRDZService'))->withContext('App\\Controller\\Api\\Players\\PlayerAchievementController::delete()', $container);
    }
}
