<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerCollectionControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZqunVNr.App\Controller\Api\Players\PlayerCollectionController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZqunVNr.App\\Controller\\Api\\Players\\PlayerCollectionController::update()'] = ($container->privates['.service_locator.ZqunVNr'] ?? $container->load('get_ServiceLocator_ZqunVNrService'))->withContext('App\\Controller\\Api\\Players\\PlayerCollectionController::update()', $container);
    }
}
