<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerCollectionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Players\PlayerCollectionController' shared autowired service.
     *
     * @return \App\Controller\Api\Players\PlayerCollectionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Players/PlayerCollectionController.php';

        $container->services['App\\Controller\\Api\\Players\\PlayerCollectionController'] = $instance = new \App\Controller\Api\Players\PlayerCollectionController(($container->privates['App\\Repository\\Players\\PlayerCollectionRepository'] ?? $container->load('getPlayerCollectionRepositoryService')), ($container->privates['validator'] ?? self::getValidatorService($container)), ($container->privates['App\\Repository\\Players\\PlayerRepository'] ?? $container->load('getPlayerRepositoryService')), ($container->privates['App\\Repository\\Cards\\CardRepository'] ?? $container->load('getCardRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\Players\\PlayerCollectionController', $container));

        return $instance;
    }
}
