<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerAchievementControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Players\PlayerAchievementController' shared autowired service.
     *
     * @return \App\Controller\Api\Players\PlayerAchievementController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Players/PlayerAchievementController.php';

        $container->services['App\\Controller\\Api\\Players\\PlayerAchievementController'] = $instance = new \App\Controller\Api\Players\PlayerAchievementController(($container->privates['App\\Repository\\Players\\PlayerAchievementRepository'] ?? $container->load('getPlayerAchievementRepositoryService')), ($container->privates['validator'] ?? self::getValidatorService($container)), ($container->privates['App\\Repository\\Players\\PlayerRepository'] ?? $container->load('getPlayerRepositoryService')), ($container->privates['App\\Repository\\Players\\AchievementRepository'] ?? $container->load('getAchievementRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\Players\\PlayerAchievementController', $container));

        return $instance;
    }
}
