<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerSeasonStatsControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1jkEg.7.App\Controller\Api\Players\PlayerSeasonStatsController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1jkEg.7.App\\Controller\\Api\\Players\\PlayerSeasonStatsController::show()'] = ($container->privates['.service_locator.1jkEg.7'] ?? $container->load('get_ServiceLocator_1jkEg_7Service'))->withContext('App\\Controller\\Api\\Players\\PlayerSeasonStatsController::show()', $container);
    }
}
