<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTradeTransactionControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hE85Gpd.App\Controller\Api\Marketplace\TradeTransactionController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hE85Gpd.App\\Controller\\Api\\Marketplace\\TradeTransactionController::update()'] = ($container->privates['.service_locator.hE85Gpd'] ?? $container->load('get_ServiceLocator_HE85GpdService'))->withContext('App\\Controller\\Api\\Marketplace\\TradeTransactionController::update()', $container);
    }
}
