<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournamentControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Tournaments\TournamentController' shared autowired service.
     *
     * @return \App\Controller\Api\Tournaments\TournamentController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Tournaments/TournamentController.php';

        $container->services['App\\Controller\\Api\\Tournaments\\TournamentController'] = $instance = new \App\Controller\Api\Tournaments\TournamentController(($container->privates['App\\Repository\\Tournaments\\TournamentRepository'] ?? $container->load('getTournamentRepositoryService')), ($container->privates['validator'] ?? self::getValidatorService($container)), ($container->privates['App\\Repository\\Tournaments\\SeasonRepository'] ?? $container->load('getSeasonRepositoryService')), ($container->privates['App\\Repository\\Players\\PlayerRepository'] ?? $container->load('getPlayerRepositoryService')), ($container->privates['App\\Repository\\Tournaments\\TournamentRegistrationRepository'] ?? $container->load('getTournamentRegistrationRepositoryService')), ($container->privates['App\\Repository\\Tournaments\\TournamentRoundRepository'] ?? $container->load('getTournamentRoundRepositoryService')), ($container->privates['App\\Repository\\Tournaments\\TournamentPrizeRepository'] ?? $container->load('getTournamentPrizeRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\Tournaments\\TournamentController', $container));

        return $instance;
    }
}
