<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTradeTransactionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hE85Gpd.App\Entity\Marketplace\TradeTransaction' shared service.
     *
     * @return \App\Entity\Marketplace\TradeTransaction
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hE85Gpd": it needs an instance of "App\\Entity\\Marketplace\\TradeTransaction" but this type has been excluded in "config/services.yaml".');
    }
}
