<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournamentRegistrationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4lt7yIw.App\Entity\Tournaments\TournamentRegistration' shared service.
     *
     * @return \App\Entity\Tournaments\TournamentRegistration
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.4lt7yIw": it needs an instance of "App\\Entity\\Tournaments\\TournamentRegistration" but this type has been excluded in "config/services.yaml".');
    }
}
