<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTradeBidControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G0u8UH8.App\Controller\Api\Marketplace\TradeBidController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G0u8UH8.App\\Controller\\Api\\Marketplace\\TradeBidController::update()'] = ($container->privates['.service_locator.G0u8UH8'] ?? $container->load('get_ServiceLocator_G0u8UH8Service'))->withContext('App\\Controller\\Api\\Marketplace\\TradeBidController::update()', $container);
    }
}
