<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournamentRoundControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KR7cRY9.App\Controller\Api\Tournaments\TournamentRoundController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KR7cRY9.App\\Controller\\Api\\Tournaments\\TournamentRoundController::show()'] = ($container->privates['.service_locator.KR7cRY9'] ?? $container->load('get_ServiceLocator_KR7cRY9Service'))->withContext('App\\Controller\\Api\\Tournaments\\TournamentRoundController::show()', $container);
    }
}
