<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournamentRegistrationControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4lt7yIw.App\Controller\Api\Tournaments\TournamentRegistrationController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4lt7yIw.App\\Controller\\Api\\Tournaments\\TournamentRegistrationController::delete()'] = ($container->privates['.service_locator.4lt7yIw'] ?? $container->load('get_ServiceLocator_4lt7yIwService'))->withContext('App\\Controller\\Api\\Tournaments\\TournamentRegistrationController::delete()', $container);
    }
}
