<?php

namespace ContainerBux4PNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournamentRoundService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KR7cRY9.App\Entity\Tournaments\TournamentRound' shared service.
     *
     * @return \App\Entity\Tournaments\TournamentRound
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.KR7cRY9": it needs an instance of "App\\Entity\\Tournaments\\TournamentRound" but this type has been excluded in "config/services.yaml".');
    }
}
