# Generated by Django 5.0.14 on 2026-05-07 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('card_type', models.CharField(choices=[('Creature', 'Creature'), ('Spell', 'Spell'), ('Land', 'Land'), ('Artifact', 'Artifact'), ('Enchantment', 'Enchantment'), ('Planeswalker', 'Planeswalker')], default='Creature', max_length=20)),
                ('rarity', models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('MythicRare', 'Mythicrare'), ('Legendary', 'Legendary')], default='Common', max_length=20)),
                ('mana_cost', models.IntegerField(default=0)),
                ('mana_colors', models.CharField(choices=[('White', 'White'), ('Blue', 'Blue'), ('Black', 'Black'), ('Red', 'Red'), ('Green', 'Green'), ('Colorless', 'Colorless')], max_length=20)),
                ('attack', models.IntegerField(blank=True, null=True)),
                ('defense', models.IntegerField(blank=True, null=True)),
                ('loyalty', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('flavor_text', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('artist_name', models.CharField(blank=True, max_length=100, null=True)),
                ('legal_formats', models.CharField(choices=[('Standard', 'Standard'), ('Extended', 'Extended'), ('Legacy', 'Legacy'), ('Vintage', 'Vintage'), ('Commander', 'Commander'), ('Draft', 'Draft')], max_length=20)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_restricted', models.BooleanField(default=False)),
                ('power_level', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10)),
                ('release_date', models.DateField()),
                ('set_type', models.CharField(choices=[('Core', 'Core'), ('Expansion', 'Expansion'), ('Supplemental', 'Supplemental'), ('Masters', 'Masters'), ('Draft', 'Draft')], default='Expansion', max_length=20)),
                ('total_cards', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Card Set',
                'verbose_name_plural': 'Card Sets',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('format', models.CharField(choices=[('Standard', 'Standard'), ('Extended', 'Extended'), ('Legacy', 'Legacy'), ('Vintage', 'Vintage'), ('Commander', 'Commander'), ('Draft', 'Draft')], default='Standard', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('is_tournament_legal', models.BooleanField(default=False)),
                ('archetype', models.CharField(blank=True, choices=[('Aggro', 'Aggro'), ('Control', 'Control'), ('Midrange', 'Midrange'), ('Combo', 'Combo'), ('Prison', 'Prison'), ('Tempo', 'Tempo')], max_length=20, null=True)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Deck',
                'verbose_name_plural': 'Decks',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('is_commander', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Deck Card',
                'verbose_name_plural': 'Deck Cards',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DeckSideboardCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Deck Sideboard Card',
                'verbose_name_plural': 'Deck Sideboard Cards',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DeckTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Deck Tag',
                'verbose_name_plural': 'Deck Tags',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DeckTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Deck Tag Assignment',
                'verbose_name_plural': 'Deck Tag Assignments',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CardAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_type', models.CharField(choices=[('Keyword', 'Keyword'), ('Activated', 'Activated'), ('Triggered', 'Triggered'), ('Static', 'Static')], default='Keyword', max_length=20)),
                ('keyword', models.CharField(blank=True, max_length=100, null=True)),
                ('ability_text', models.TextField()),
                ('timing', models.CharField(blank=True, choices=[('Any', 'Any'), ('Sorcery', 'Sorcery'), ('Instant', 'Instant'), ('Combat', 'Combat')], max_length=20, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
            ],
            options={
                'verbose_name': 'Card Ability',
                'verbose_name_plural': 'Card Abilities',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='abilities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.cardability'),
        ),
        migrations.CreateModel(
            name='CardRuling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruling_text', models.TextField()),
                ('published_at', models.DateField()),
                ('source', models.CharField(max_length=200)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
            ],
            options={
                'verbose_name': 'Card Ruling',
                'verbose_name_plural': 'Card Rulings',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='rulings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.cardruling'),
        ),
        migrations.AddField(
            model_name='card',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.cardset'),
        ),
    ]
