# Generated by Django 5.0.14 on 2026-05-07 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='players.player'),
        ),
        migrations.AddField(
            model_name='deckcard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_cards', to='cards.card'),
        ),
        migrations.AddField(
            model_name='deckcard',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_cards', to='cards.deck'),
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(related_name='decks', through='cards.DeckCard', to='cards.card'),
        ),
        migrations.AddField(
            model_name='decksideboardcard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sideboard_decks', to='cards.card'),
        ),
        migrations.AddField(
            model_name='decksideboardcard',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.deck'),
        ),
        migrations.AddField(
            model_name='deck',
            name='sideboard_cards',
            field=models.ManyToManyField(related_name='sideboard_decks', through='cards.DeckSideboardCard', to='cards.card'),
        ),
        migrations.AddField(
            model_name='decktagassignment',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='cards.deck'),
        ),
        migrations.AddField(
            model_name='decktagassignment',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_assignments', to='cards.decktag'),
        ),
        migrations.AddField(
            model_name='deck',
            name='tags',
            field=models.ManyToManyField(through='cards.DeckTagAssignment', to='cards.decktag'),
        ),
    ]
