(* Migration runner — creates all tables *)
let () =
  let db = Sqlite3.db_open "cards_project.db" in
  let exec sql =
    match Sqlite3.exec db sql with
    | Sqlite3.Rc.OK -> ()
    | rc -> failwith (Printf.sprintf "Migration error [%s]: %s" (Sqlite3.Rc.to_string rc) sql)
  in
  (* table: user *)
  exec "CREATE TABLE IF NOT EXISTS users (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  username TEXT NOT NULL,\n  email TEXT NOT NULL UNIQUE,\n  hashed_password TEXT,\n  is_active INTEGER NOT NULL DEFAULT 1,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: card *)
  exec "CREATE TABLE IF NOT EXISTS cards (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  name TEXT NOT NULL,\n  card_type TEXT NOT NULL DEFAULT 'Creature',\n  rarity TEXT NOT NULL DEFAULT 'Common',\n  mana_cost INTEGER NOT NULL DEFAULT 0,\n  mana_colors TEXT NOT NULL,\n  attack INTEGER,\n  defense INTEGER,\n  loyalty INTEGER,\n  description TEXT NOT NULL,\n  flavor_text TEXT,\n  image_url TEXT,\n  artist_name TEXT,\n  legal_formats TEXT NOT NULL,\n  is_banned INTEGER NOT NULL DEFAULT 0,\n  is_restricted INTEGER NOT NULL DEFAULT 0,\n  power_level INTEGER NOT NULL DEFAULT 1,\n  set_id INTEGER NOT NULL REFERENCES card_sets(id) ON DELETE RESTRICT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: card_set *)
  exec "CREATE TABLE IF NOT EXISTS card_sets (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  name TEXT NOT NULL,\n  code TEXT NOT NULL UNIQUE,\n  release_date TEXT NOT NULL,\n  rotation_date TEXT,\n  set_type TEXT NOT NULL DEFAULT 'Expansion',\n  total_cards INTEGER NOT NULL,\n  is_rotated INTEGER NOT NULL DEFAULT 0,\n  description TEXT,\n  logo_url TEXT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: card_ruling *)
  exec "CREATE TABLE IF NOT EXISTS card_rulings (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  ruling_text TEXT NOT NULL,\n  published_at TEXT NOT NULL,\n  source TEXT NOT NULL,\n  card_id INTEGER NOT NULL REFERENCES cards(id) ON DELETE CASCADE,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: card_ability *)
  exec "CREATE TABLE IF NOT EXISTS card_abilities (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  ability_type TEXT NOT NULL DEFAULT 'Keyword',\n  keyword TEXT,\n  ability_text TEXT NOT NULL,\n  timing TEXT,\n  card_id INTEGER NOT NULL REFERENCES cards(id) ON DELETE CASCADE,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: deck *)
  exec "CREATE TABLE IF NOT EXISTS decks (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  name TEXT NOT NULL,\n  description TEXT,\n  format TEXT NOT NULL DEFAULT 'Standard',\n  is_public INTEGER NOT NULL DEFAULT 0,\n  is_tournament_legal INTEGER NOT NULL DEFAULT 0,\n  archetype TEXT,\n  wins INTEGER NOT NULL DEFAULT 0,\n  losses INTEGER NOT NULL DEFAULT 0,\n  draws INTEGER NOT NULL DEFAULT 0,\n  player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: deck_card *)
  exec "CREATE TABLE IF NOT EXISTS deck_cards (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  quantity INTEGER NOT NULL DEFAULT 1,\n  is_commander INTEGER NOT NULL DEFAULT 0,\n  deck_id INTEGER NOT NULL REFERENCES decks(id) ON DELETE CASCADE,\n  card_id INTEGER NOT NULL REFERENCES cards(id) ON DELETE RESTRICT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: deck_sideboard_card *)
  exec "CREATE TABLE IF NOT EXISTS deck_sideboard_cards (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  quantity INTEGER NOT NULL DEFAULT 1,\n  deck_id INTEGER NOT NULL REFERENCES decks(id) ON DELETE CASCADE,\n  card_id INTEGER NOT NULL REFERENCES cards(id) ON DELETE RESTRICT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: deck_tag *)
  exec "CREATE TABLE IF NOT EXISTS deck_tags (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  name TEXT NOT NULL,\n  color TEXT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: deck_tag_assignment *)
  exec "CREATE TABLE IF NOT EXISTS deck_tag_assignments (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  deck_id INTEGER NOT NULL REFERENCES decks(id) ON DELETE CASCADE,\n  tag_id INTEGER NOT NULL REFERENCES deck_tags(id) ON DELETE CASCADE,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: player *)
  exec "CREATE TABLE IF NOT EXISTS players (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  display_name TEXT NOT NULL UNIQUE,\n  rank TEXT NOT NULL DEFAULT 'Bronze',\n  rating INTEGER NOT NULL DEFAULT 1000,\n  peak_rating INTEGER NOT NULL DEFAULT 1000,\n  bio TEXT,\n  country_code TEXT,\n  avatar_url TEXT,\n  preferred_format TEXT,\n  is_verified INTEGER NOT NULL DEFAULT 0,\n  last_active_at TEXT,\n  user_id INTEGER UNIQUE REFERENCES users(id) ON DELETE CASCADE,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: player_season_stats *)
  exec "CREATE TABLE IF NOT EXISTS player_season_statses (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  wins INTEGER NOT NULL DEFAULT 0,\n  losses INTEGER NOT NULL DEFAULT 0,\n  draws INTEGER NOT NULL DEFAULT 0,\n  tournament_wins INTEGER NOT NULL DEFAULT 0,\n  highest_rank TEXT,\n  season_points INTEGER NOT NULL DEFAULT 0,\n  player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,\n  season_id INTEGER NOT NULL REFERENCES seasons(id) ON DELETE CASCADE,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: player_collection *)
  exec "CREATE TABLE IF NOT EXISTS player_collections (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  quantity INTEGER NOT NULL DEFAULT 1,\n  foil INTEGER NOT NULL DEFAULT 0,\n  condition TEXT NOT NULL DEFAULT 'Mint',\n  acquired_at TEXT NOT NULL,\n  acquired_via TEXT NOT NULL DEFAULT 'Purchase',\n  player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,\n  card_id INTEGER NOT NULL REFERENCES cards(id) ON DELETE RESTRICT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: friendship *)
  exec "CREATE TABLE IF NOT EXISTS friendships (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  status TEXT NOT NULL DEFAULT 'Pending',\n  requester_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,\n  receiver_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: achievement *)
  exec "CREATE TABLE IF NOT EXISTS achievements (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  name TEXT NOT NULL,\n  description TEXT NOT NULL,\n  icon_url TEXT,\n  points INTEGER NOT NULL DEFAULT 10,\n  rarity TEXT NOT NULL DEFAULT 'Common',\n  is_hidden INTEGER NOT NULL DEFAULT 0,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: player_achievement *)
  exec "CREATE TABLE IF NOT EXISTS player_achievements (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  earned_at TEXT NOT NULL,\n  progress INTEGER NOT NULL DEFAULT 0,\n  is_completed INTEGER NOT NULL DEFAULT 0,\n  player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,\n  achievement_id INTEGER NOT NULL REFERENCES achievements(id) ON DELETE RESTRICT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: crafting_recipe *)
  exec "CREATE TABLE IF NOT EXISTS crafting_recipes (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  dust_cost INTEGER NOT NULL,\n  is_available INTEGER NOT NULL DEFAULT 1,\n  result_card_id INTEGER NOT NULL REFERENCES cards(id) ON DELETE RESTRICT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: crafting_ingredient *)
  exec "CREATE TABLE IF NOT EXISTS crafting_ingredients (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  quantity INTEGER NOT NULL DEFAULT 1,\n  recipe_id INTEGER NOT NULL REFERENCES crafting_recipes(id) ON DELETE CASCADE,\n  card_id INTEGER NOT NULL REFERENCES cards(id) ON DELETE RESTRICT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: season *)
  exec "CREATE TABLE IF NOT EXISTS seasons (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  name TEXT NOT NULL,\n  start_date TEXT NOT NULL,\n  end_date TEXT NOT NULL,\n  format TEXT NOT NULL DEFAULT 'Standard',\n  is_active INTEGER NOT NULL DEFAULT 0,\n  reward_description TEXT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: tournament *)
  exec "CREATE TABLE IF NOT EXISTS tournaments (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  name TEXT NOT NULL,\n  description TEXT,\n  status TEXT NOT NULL DEFAULT 'Draft',\n  format TEXT NOT NULL DEFAULT 'Standard',\n  tournament_type TEXT NOT NULL DEFAULT 'Swiss',\n  max_players INTEGER NOT NULL,\n  entry_fee REAL NOT NULL DEFAULT 0,\n  prize_pool REAL NOT NULL DEFAULT 0,\n  start_time TEXT NOT NULL,\n  end_time TEXT,\n  is_online INTEGER NOT NULL DEFAULT 1,\n  location TEXT,\n  rules_text TEXT,\n  season_id INTEGER NOT NULL REFERENCES seasons(id) ON DELETE RESTRICT,\n  organizer_id INTEGER NOT NULL REFERENCES players(id) ON DELETE RESTRICT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: tournament_judge *)
  exec "CREATE TABLE IF NOT EXISTS tournament_judges (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  role TEXT NOT NULL DEFAULT 'Judge',\n  tournament_id INTEGER NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,\n  player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE RESTRICT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: tournament_registration *)
  exec "CREATE TABLE IF NOT EXISTS tournament_registrations (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  status TEXT NOT NULL DEFAULT 'Registered',\n  seed INTEGER,\n  final_standing INTEGER,\n  points_earned INTEGER NOT NULL DEFAULT 0,\n  registered_at TEXT NOT NULL,\n  tournament_id INTEGER NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,\n  player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE RESTRICT,\n  deck_id INTEGER NOT NULL REFERENCES decks(id) ON DELETE RESTRICT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: tournament_round *)
  exec "CREATE TABLE IF NOT EXISTS tournament_rounds (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  round_number INTEGER NOT NULL,\n  status TEXT NOT NULL DEFAULT 'Pending',\n  started_at TEXT,\n  ended_at TEXT,\n  time_limit_minutes INTEGER NOT NULL DEFAULT 50,\n  tournament_id INTEGER NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: match *)
  exec "CREATE TABLE IF NOT EXISTS matches (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  table_number INTEGER,\n  status TEXT NOT NULL DEFAULT 'Pending',\n  player1_wins INTEGER NOT NULL DEFAULT 0,\n  player2_wins INTEGER NOT NULL DEFAULT 0,\n  started_at TEXT,\n  ended_at TEXT,\n  result_notes TEXT,\n  round_id INTEGER NOT NULL REFERENCES tournament_rounds(id) ON DELETE CASCADE,\n  player1_id INTEGER NOT NULL REFERENCES players(id) ON DELETE RESTRICT,\n  player2_id INTEGER REFERENCES players(id) ON DELETE SET NULL,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: game *)
  exec "CREATE TABLE IF NOT EXISTS games (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  game_number INTEGER NOT NULL,\n  winner_side TEXT,\n  turns_played INTEGER,\n  duration_seconds INTEGER,\n  ended_by TEXT,\n  replay_url TEXT,\n  match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,\n  winner_id INTEGER REFERENCES players(id) ON DELETE SET NULL,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: tournament_prize *)
  exec "CREATE TABLE IF NOT EXISTS tournament_prizes (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  placement_from INTEGER NOT NULL,\n  placement_to INTEGER NOT NULL,\n  prize_type TEXT NOT NULL,\n  amount REAL NOT NULL DEFAULT 0,\n  description TEXT,\n  packs_count INTEGER,\n  season_points INTEGER NOT NULL DEFAULT 0,\n  tournament_id INTEGER NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: awarded_prize *)
  exec "CREATE TABLE IF NOT EXISTS awarded_prizes (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  final_placement INTEGER NOT NULL,\n  awarded_at TEXT NOT NULL,\n  claimed INTEGER NOT NULL DEFAULT 0,\n  claimed_at TEXT,\n  prize_id INTEGER NOT NULL REFERENCES tournament_prizes(id) ON DELETE RESTRICT,\n  player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE RESTRICT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: product *)
  exec "CREATE TABLE IF NOT EXISTS products (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  name TEXT NOT NULL,\n  product_type TEXT NOT NULL DEFAULT 'SingleCard',\n  price REAL NOT NULL,\n  stock INTEGER NOT NULL DEFAULT 0,\n  active INTEGER NOT NULL DEFAULT 1,\n  discount_percent INTEGER NOT NULL DEFAULT 0,\n  description TEXT,\n  image_url TEXT,\n  featured INTEGER NOT NULL DEFAULT 0,\n  card_id INTEGER UNIQUE REFERENCES cards(id) ON DELETE SET NULL,\n  card_set_id INTEGER REFERENCES card_sets(id) ON DELETE SET NULL,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: order *)
  exec "CREATE TABLE IF NOT EXISTS orders (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  status TEXT NOT NULL DEFAULT 'Pending',\n  total REAL NOT NULL DEFAULT 0,\n  discount_applied REAL NOT NULL DEFAULT 0,\n  currency TEXT NOT NULL DEFAULT 'USD',\n  payment_method TEXT,\n  payment_reference TEXT,\n  shipping_address TEXT,\n  tracking_number TEXT,\n  paid_at TEXT,\n  shipped_at TEXT,\n  player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE RESTRICT,\n  coupon_id INTEGER REFERENCES coupons(id) ON DELETE SET NULL,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: order_item *)
  exec "CREATE TABLE IF NOT EXISTS order_items (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  quantity INTEGER NOT NULL,\n  price_at_purchase REAL NOT NULL,\n  foil INTEGER NOT NULL DEFAULT 0,\n  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,\n  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE RESTRICT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: coupon *)
  exec "CREATE TABLE IF NOT EXISTS coupons (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  code TEXT NOT NULL UNIQUE,\n  discount_type TEXT NOT NULL DEFAULT 'Percent',\n  discount_value REAL NOT NULL,\n  min_order_value REAL NOT NULL DEFAULT 0,\n  max_uses INTEGER,\n  uses_count INTEGER NOT NULL DEFAULT 0,\n  valid_from TEXT NOT NULL,\n  valid_until TEXT NOT NULL,\n  is_active INTEGER NOT NULL DEFAULT 1,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: trade_listing *)
  exec "CREATE TABLE IF NOT EXISTS trade_listings (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  status TEXT NOT NULL DEFAULT 'Active',\n  listing_type TEXT NOT NULL DEFAULT 'FixedPrice',\n  asking_price REAL,\n  auction_start_price REAL,\n  auction_current_bid REAL,\n  auction_end_time TEXT,\n  foil INTEGER NOT NULL DEFAULT 0,\n  condition TEXT NOT NULL DEFAULT 'Mint',\n  quantity INTEGER NOT NULL DEFAULT 1,\n  description TEXT,\n  expires_at TEXT,\n  seller_id INTEGER NOT NULL REFERENCES players(id) ON DELETE RESTRICT,\n  card_id INTEGER NOT NULL REFERENCES cards(id) ON DELETE RESTRICT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: trade_bid *)
  exec "CREATE TABLE IF NOT EXISTS trade_bids (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  amount REAL NOT NULL,\n  placed_at TEXT NOT NULL,\n  is_winning INTEGER NOT NULL DEFAULT 0,\n  listing_id INTEGER NOT NULL REFERENCES trade_listings(id) ON DELETE CASCADE,\n  bidder_id INTEGER NOT NULL REFERENCES players(id) ON DELETE RESTRICT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: trade_transaction *)
  exec "CREATE TABLE IF NOT EXISTS trade_transactions (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  final_price REAL NOT NULL,\n  platform_fee REAL NOT NULL,\n  status TEXT NOT NULL DEFAULT 'Pending',\n  completed_at TEXT,\n  listing_id INTEGER NOT NULL UNIQUE REFERENCES trade_listings(id) ON DELETE RESTRICT,\n  buyer_id INTEGER NOT NULL REFERENCES players(id) ON DELETE RESTRICT,\n  seller_id INTEGER NOT NULL REFERENCES players(id) ON DELETE RESTRICT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: card_price_history *)
  exec "CREATE TABLE IF NOT EXISTS card_price_histories (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  price_date TEXT NOT NULL,\n  avg_price REAL NOT NULL,\n  min_price REAL NOT NULL,\n  max_price REAL NOT NULL,\n  volume INTEGER NOT NULL,\n  foil INTEGER NOT NULL DEFAULT 0,\n  card_id INTEGER NOT NULL REFERENCES cards(id) ON DELETE CASCADE,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: trade_dispute *)
  exec "CREATE TABLE IF NOT EXISTS trade_disputes (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  status TEXT NOT NULL DEFAULT 'Open',\n  reason TEXT NOT NULL,\n  description TEXT NOT NULL,\n  resolution TEXT,\n  opened_at TEXT NOT NULL,\n  resolved_at TEXT,\n  transaction_id INTEGER NOT NULL UNIQUE REFERENCES trade_transactions(id) ON DELETE CASCADE,\n  opened_by_id INTEGER NOT NULL REFERENCES players(id) ON DELETE RESTRICT,\n  resolved_by_id INTEGER REFERENCES players(id) ON DELETE SET NULL,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: draft_session *)
  exec "CREATE TABLE IF NOT EXISTS draft_sessions (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  status TEXT NOT NULL DEFAULT 'WaitingForPlayers',\n  draft_type TEXT NOT NULL DEFAULT 'Booster',\n  seats INTEGER NOT NULL DEFAULT 8,\n  time_per_pick_seconds INTEGER NOT NULL DEFAULT 30,\n  completed_at TEXT,\n  card_set_id INTEGER NOT NULL REFERENCES card_sets(id) ON DELETE RESTRICT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: draft_participant *)
  exec "CREATE TABLE IF NOT EXISTS draft_participants (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  seat_number INTEGER NOT NULL,\n  joined_at TEXT NOT NULL,\n  session_id INTEGER NOT NULL REFERENCES draft_sessions(id) ON DELETE CASCADE,\n  player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE RESTRICT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: draft_pick *)
  exec "CREATE TABLE IF NOT EXISTS draft_picks (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  pick_number INTEGER NOT NULL,\n  pack_number INTEGER NOT NULL,\n  picked_at TEXT NOT NULL,\n  participant_id INTEGER NOT NULL REFERENCES draft_participants(id) ON DELETE CASCADE,\n  card_id INTEGER NOT NULL REFERENCES cards(id) ON DELETE RESTRICT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: article *)
  exec "CREATE TABLE IF NOT EXISTS articles (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  title TEXT NOT NULL,\n  slug TEXT NOT NULL UNIQUE,\n  body TEXT NOT NULL,\n  excerpt TEXT,\n  cover_image_url TEXT,\n  status TEXT NOT NULL DEFAULT 'Draft',\n  article_type TEXT NOT NULL DEFAULT 'Guide',\n  language TEXT NOT NULL DEFAULT 'EN',\n  view_count INTEGER NOT NULL DEFAULT 0,\n  likes_count INTEGER NOT NULL DEFAULT 0,\n  is_featured INTEGER NOT NULL DEFAULT 0,\n  published_at TEXT,\n  author_id INTEGER NOT NULL REFERENCES players(id) ON DELETE RESTRICT,\n  featured_deck_id INTEGER REFERENCES decks(id) ON DELETE SET NULL,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: article_tag *)
  exec "CREATE TABLE IF NOT EXISTS article_tags (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  name TEXT NOT NULL,\n  slug TEXT NOT NULL UNIQUE,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: article_tag_assignment *)
  exec "CREATE TABLE IF NOT EXISTS article_tag_assignments (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  article_id INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE,\n  tag_id INTEGER NOT NULL REFERENCES article_tags(id) ON DELETE CASCADE,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: article_comment *)
  exec "CREATE TABLE IF NOT EXISTS article_comments (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  body TEXT NOT NULL,\n  is_hidden INTEGER NOT NULL DEFAULT 0,\n  article_id INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE,\n  author_id INTEGER NOT NULL REFERENCES players(id) ON DELETE RESTRICT,\n  parent_comment_id INTEGER REFERENCES article_comments(id) ON DELETE SET NULL,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  (* table: stream *)
  exec "CREATE TABLE IF NOT EXISTS streams (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  title TEXT NOT NULL,\n  stream_url TEXT NOT NULL,\n  status TEXT NOT NULL DEFAULT 'Scheduled',\n  platform TEXT NOT NULL DEFAULT 'Twitch',\n  language TEXT NOT NULL DEFAULT 'EN',\n  is_official INTEGER NOT NULL DEFAULT 0,\n  viewer_count_peak INTEGER NOT NULL DEFAULT 0,\n  scheduled_start TEXT NOT NULL,\n  actual_start TEXT,\n  ended_at TEXT,\n  vod_url TEXT,\n  tournament_id INTEGER REFERENCES tournaments(id) ON DELETE SET NULL,\n  streamer_id INTEGER NOT NULL REFERENCES players(id) ON DELETE RESTRICT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);";
  ignore (Sqlite3.db_close db);
  print_endline "Migrations complete."
