<?php

namespace App\Controller\Api;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/api', name: 'api_')]
class ApiIndexController extends AbstractController
{
    #[Route('', name: 'index', methods: ['GET'])]
    #[Route('/', name: 'index_slash', methods: ['GET'])]
    public function index(): JsonResponse
    {
        return $this->json([
            'status'    => 'ok',
            'docs'      => '/api/doc',
            'endpoints' => [
            ['resource' => 'Card', 'list' => '/api/cards', 'detail' => '/api/cards/{id}'],
            ['resource' => 'CardSet', 'list' => '/api/card_sets', 'detail' => '/api/card_sets/{id}'],
            ['resource' => 'CardRuling', 'list' => '/api/card_rulings', 'detail' => '/api/card_rulings/{id}'],
            ['resource' => 'CardAbility', 'list' => '/api/card_abilities', 'detail' => '/api/card_abilities/{id}'],
            ['resource' => 'Deck', 'list' => '/api/decks', 'detail' => '/api/decks/{id}'],
            ['resource' => 'DeckCard', 'list' => '/api/deck_cards', 'detail' => '/api/deck_cards/{id}'],
            ['resource' => 'DeckSideboardCard', 'list' => '/api/deck_sideboard_cards', 'detail' => '/api/deck_sideboard_cards/{id}'],
            ['resource' => 'DeckTag', 'list' => '/api/deck_tags', 'detail' => '/api/deck_tags/{id}'],
            ['resource' => 'DeckTagAssignment', 'list' => '/api/deck_tag_assignments', 'detail' => '/api/deck_tag_assignments/{id}'],
            ['resource' => 'Player', 'list' => '/api/players', 'detail' => '/api/players/{id}'],
            ['resource' => 'PlayerSeasonStats', 'list' => '/api/player_season_statses', 'detail' => '/api/player_season_statses/{id}'],
            ['resource' => 'PlayerCollection', 'list' => '/api/player_collections', 'detail' => '/api/player_collections/{id}'],
            ['resource' => 'Friendship', 'list' => '/api/friendships', 'detail' => '/api/friendships/{id}'],
            ['resource' => 'Achievement', 'list' => '/api/achievements', 'detail' => '/api/achievements/{id}'],
            ['resource' => 'PlayerAchievement', 'list' => '/api/player_achievements', 'detail' => '/api/player_achievements/{id}'],
            ['resource' => 'CraftingRecipe', 'list' => '/api/crafting_recipes', 'detail' => '/api/crafting_recipes/{id}'],
            ['resource' => 'CraftingIngredient', 'list' => '/api/crafting_ingredients', 'detail' => '/api/crafting_ingredients/{id}'],
            ['resource' => 'Season', 'list' => '/api/seasons', 'detail' => '/api/seasons/{id}'],
            ['resource' => 'Tournament', 'list' => '/api/tournaments', 'detail' => '/api/tournaments/{id}'],
            ['resource' => 'TournamentJudge', 'list' => '/api/tournament_judges', 'detail' => '/api/tournament_judges/{id}'],
            ['resource' => 'TournamentRegistration', 'list' => '/api/tournament_registrations', 'detail' => '/api/tournament_registrations/{id}'],
            ['resource' => 'TournamentRound', 'list' => '/api/tournament_rounds', 'detail' => '/api/tournament_rounds/{id}'],
            ['resource' => 'Match', 'list' => '/api/matches', 'detail' => '/api/matches/{id}'],
            ['resource' => 'Game', 'list' => '/api/games', 'detail' => '/api/games/{id}'],
            ['resource' => 'TournamentPrize', 'list' => '/api/tournament_prizes', 'detail' => '/api/tournament_prizes/{id}'],
            ['resource' => 'AwardedPrize', 'list' => '/api/awarded_prizes', 'detail' => '/api/awarded_prizes/{id}'],
            ['resource' => 'Product', 'list' => '/api/products', 'detail' => '/api/products/{id}'],
            ['resource' => 'Order', 'list' => '/api/orders', 'detail' => '/api/orders/{id}'],
            ['resource' => 'OrderItem', 'list' => '/api/order_items', 'detail' => '/api/order_items/{id}'],
            ['resource' => 'Coupon', 'list' => '/api/coupons', 'detail' => '/api/coupons/{id}'],
            ['resource' => 'Tradelisting', 'list' => '/api/tradelistings', 'detail' => '/api/tradelistings/{id}'],
            ['resource' => 'TradeBid', 'list' => '/api/trade_bids', 'detail' => '/api/trade_bids/{id}'],
            ['resource' => 'TradeTransaction', 'list' => '/api/trade_transactions', 'detail' => '/api/trade_transactions/{id}'],
            ['resource' => 'CardPriceHistory', 'list' => '/api/card_price_histories', 'detail' => '/api/card_price_histories/{id}'],
            ['resource' => 'TradeDispute', 'list' => '/api/trade_disputes', 'detail' => '/api/trade_disputes/{id}'],
            ['resource' => 'DraftSession', 'list' => '/api/draft_sessions', 'detail' => '/api/draft_sessions/{id}'],
            ['resource' => 'DraftParticipant', 'list' => '/api/draft_participants', 'detail' => '/api/draft_participants/{id}'],
            ['resource' => 'DraftPick', 'list' => '/api/draft_picks', 'detail' => '/api/draft_picks/{id}'],
            ['resource' => 'Article', 'list' => '/api/articles', 'detail' => '/api/articles/{id}'],
            ['resource' => 'ArticleTag', 'list' => '/api/article_tags', 'detail' => '/api/article_tags/{id}'],
            ['resource' => 'ArticleTagAssignment', 'list' => '/api/article_tag_assignments', 'detail' => '/api/article_tag_assignments/{id}'],
            ['resource' => 'ArticleComment', 'list' => '/api/article_comments', 'detail' => '/api/article_comments/{id}'],
            ['resource' => 'Stream', 'list' => '/api/streams', 'detail' => '/api/streams/{id}'],
            ],
        ]);
    }

    #[Route('/doc', name: 'doc_ui', methods: ['GET'])]
    public function docUi(): Response
    {
        return new Response(<<<HTML
<!DOCTYPE html><html><head>
<title>API Documentation</title>
<meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css">
</head><body>
<div id="swagger-ui"></div>
<script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
<script>
SwaggerUIBundle({url:"/api/doc.json",dom_id:"#swagger-ui",deepLinking:true,
presets:[SwaggerUIBundle.presets.apis,SwaggerUIBundle.SwaggerUIStandalonePreset],
layout:"StandaloneLayout"});
</script></body></html>
HTML, 200, ['Content-Type' => 'text/html']);
    }

    #[Route('/doc.json', name: 'doc_json', methods: ['GET'])]
    public function docJson(): JsonResponse
    {
        return $this->json([
            'openapi' => '3.0.0',
            'info'    => ['title' => 'API', 'version' => '1.0.0'],
            'paths'   => [
            '/api/cards' => ['get' => ['tags'=>['cards'],'summary'=>'List Card','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['cards'],'summary'=>'Create Card','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/cards/{id}' => ['get' => ['tags'=>['cards'],'summary'=>'Get Card','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['cards'],'summary'=>'Update Card','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['cards'],'summary'=>'Delete Card','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/card_sets' => ['get' => ['tags'=>['cards'],'summary'=>'List CardSet','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['cards'],'summary'=>'Create CardSet','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/card_sets/{id}' => ['get' => ['tags'=>['cards'],'summary'=>'Get CardSet','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['cards'],'summary'=>'Update CardSet','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['cards'],'summary'=>'Delete CardSet','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/card_rulings' => ['get' => ['tags'=>['cards'],'summary'=>'List CardRuling','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['cards'],'summary'=>'Create CardRuling','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/card_rulings/{id}' => ['get' => ['tags'=>['cards'],'summary'=>'Get CardRuling','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['cards'],'summary'=>'Update CardRuling','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['cards'],'summary'=>'Delete CardRuling','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/card_abilities' => ['get' => ['tags'=>['cards'],'summary'=>'List CardAbility','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['cards'],'summary'=>'Create CardAbility','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/card_abilities/{id}' => ['get' => ['tags'=>['cards'],'summary'=>'Get CardAbility','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['cards'],'summary'=>'Update CardAbility','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['cards'],'summary'=>'Delete CardAbility','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/decks' => ['get' => ['tags'=>['cards'],'summary'=>'List Deck','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['cards'],'summary'=>'Create Deck','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/decks/{id}' => ['get' => ['tags'=>['cards'],'summary'=>'Get Deck','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['cards'],'summary'=>'Update Deck','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['cards'],'summary'=>'Delete Deck','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/deck_cards' => ['get' => ['tags'=>['cards'],'summary'=>'List DeckCard','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['cards'],'summary'=>'Create DeckCard','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/deck_cards/{id}' => ['get' => ['tags'=>['cards'],'summary'=>'Get DeckCard','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['cards'],'summary'=>'Update DeckCard','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['cards'],'summary'=>'Delete DeckCard','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/deck_sideboard_cards' => ['get' => ['tags'=>['cards'],'summary'=>'List DeckSideboardCard','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['cards'],'summary'=>'Create DeckSideboardCard','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/deck_sideboard_cards/{id}' => ['get' => ['tags'=>['cards'],'summary'=>'Get DeckSideboardCard','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['cards'],'summary'=>'Update DeckSideboardCard','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['cards'],'summary'=>'Delete DeckSideboardCard','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/deck_tags' => ['get' => ['tags'=>['cards'],'summary'=>'List DeckTag','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['cards'],'summary'=>'Create DeckTag','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/deck_tags/{id}' => ['get' => ['tags'=>['cards'],'summary'=>'Get DeckTag','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['cards'],'summary'=>'Update DeckTag','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['cards'],'summary'=>'Delete DeckTag','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/deck_tag_assignments' => ['get' => ['tags'=>['cards'],'summary'=>'List DeckTagAssignment','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['cards'],'summary'=>'Create DeckTagAssignment','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/deck_tag_assignments/{id}' => ['get' => ['tags'=>['cards'],'summary'=>'Get DeckTagAssignment','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['cards'],'summary'=>'Update DeckTagAssignment','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['cards'],'summary'=>'Delete DeckTagAssignment','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/players' => ['get' => ['tags'=>['players'],'summary'=>'List Player','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['players'],'summary'=>'Create Player','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/players/{id}' => ['get' => ['tags'=>['players'],'summary'=>'Get Player','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['players'],'summary'=>'Update Player','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['players'],'summary'=>'Delete Player','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/player_season_statses' => ['get' => ['tags'=>['players'],'summary'=>'List PlayerSeasonStats','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['players'],'summary'=>'Create PlayerSeasonStats','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/player_season_statses/{id}' => ['get' => ['tags'=>['players'],'summary'=>'Get PlayerSeasonStats','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['players'],'summary'=>'Update PlayerSeasonStats','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['players'],'summary'=>'Delete PlayerSeasonStats','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/player_collections' => ['get' => ['tags'=>['players'],'summary'=>'List PlayerCollection','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['players'],'summary'=>'Create PlayerCollection','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/player_collections/{id}' => ['get' => ['tags'=>['players'],'summary'=>'Get PlayerCollection','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['players'],'summary'=>'Update PlayerCollection','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['players'],'summary'=>'Delete PlayerCollection','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/friendships' => ['get' => ['tags'=>['players'],'summary'=>'List Friendship','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['players'],'summary'=>'Create Friendship','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/friendships/{id}' => ['get' => ['tags'=>['players'],'summary'=>'Get Friendship','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['players'],'summary'=>'Update Friendship','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['players'],'summary'=>'Delete Friendship','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/achievements' => ['get' => ['tags'=>['players'],'summary'=>'List Achievement','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['players'],'summary'=>'Create Achievement','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/achievements/{id}' => ['get' => ['tags'=>['players'],'summary'=>'Get Achievement','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['players'],'summary'=>'Update Achievement','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['players'],'summary'=>'Delete Achievement','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/player_achievements' => ['get' => ['tags'=>['players'],'summary'=>'List PlayerAchievement','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['players'],'summary'=>'Create PlayerAchievement','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/player_achievements/{id}' => ['get' => ['tags'=>['players'],'summary'=>'Get PlayerAchievement','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['players'],'summary'=>'Update PlayerAchievement','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['players'],'summary'=>'Delete PlayerAchievement','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/crafting_recipes' => ['get' => ['tags'=>['players'],'summary'=>'List CraftingRecipe','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['players'],'summary'=>'Create CraftingRecipe','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/crafting_recipes/{id}' => ['get' => ['tags'=>['players'],'summary'=>'Get CraftingRecipe','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['players'],'summary'=>'Update CraftingRecipe','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['players'],'summary'=>'Delete CraftingRecipe','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/crafting_ingredients' => ['get' => ['tags'=>['players'],'summary'=>'List CraftingIngredient','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['players'],'summary'=>'Create CraftingIngredient','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/crafting_ingredients/{id}' => ['get' => ['tags'=>['players'],'summary'=>'Get CraftingIngredient','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['players'],'summary'=>'Update CraftingIngredient','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['players'],'summary'=>'Delete CraftingIngredient','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/seasons' => ['get' => ['tags'=>['tournaments'],'summary'=>'List Season','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['tournaments'],'summary'=>'Create Season','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/seasons/{id}' => ['get' => ['tags'=>['tournaments'],'summary'=>'Get Season','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['tournaments'],'summary'=>'Update Season','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['tournaments'],'summary'=>'Delete Season','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/tournaments' => ['get' => ['tags'=>['tournaments'],'summary'=>'List Tournament','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['tournaments'],'summary'=>'Create Tournament','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/tournaments/{id}' => ['get' => ['tags'=>['tournaments'],'summary'=>'Get Tournament','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['tournaments'],'summary'=>'Update Tournament','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['tournaments'],'summary'=>'Delete Tournament','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/tournament_judges' => ['get' => ['tags'=>['tournaments'],'summary'=>'List TournamentJudge','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['tournaments'],'summary'=>'Create TournamentJudge','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/tournament_judges/{id}' => ['get' => ['tags'=>['tournaments'],'summary'=>'Get TournamentJudge','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['tournaments'],'summary'=>'Update TournamentJudge','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['tournaments'],'summary'=>'Delete TournamentJudge','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/tournament_registrations' => ['get' => ['tags'=>['tournaments'],'summary'=>'List TournamentRegistration','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['tournaments'],'summary'=>'Create TournamentRegistration','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/tournament_registrations/{id}' => ['get' => ['tags'=>['tournaments'],'summary'=>'Get TournamentRegistration','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['tournaments'],'summary'=>'Update TournamentRegistration','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['tournaments'],'summary'=>'Delete TournamentRegistration','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/tournament_rounds' => ['get' => ['tags'=>['tournaments'],'summary'=>'List TournamentRound','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['tournaments'],'summary'=>'Create TournamentRound','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/tournament_rounds/{id}' => ['get' => ['tags'=>['tournaments'],'summary'=>'Get TournamentRound','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['tournaments'],'summary'=>'Update TournamentRound','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['tournaments'],'summary'=>'Delete TournamentRound','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/matches' => ['get' => ['tags'=>['tournaments'],'summary'=>'List Match','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['tournaments'],'summary'=>'Create Match','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/matches/{id}' => ['get' => ['tags'=>['tournaments'],'summary'=>'Get Match','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['tournaments'],'summary'=>'Update Match','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['tournaments'],'summary'=>'Delete Match','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/games' => ['get' => ['tags'=>['tournaments'],'summary'=>'List Game','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['tournaments'],'summary'=>'Create Game','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/games/{id}' => ['get' => ['tags'=>['tournaments'],'summary'=>'Get Game','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['tournaments'],'summary'=>'Update Game','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['tournaments'],'summary'=>'Delete Game','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/tournament_prizes' => ['get' => ['tags'=>['tournaments'],'summary'=>'List TournamentPrize','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['tournaments'],'summary'=>'Create TournamentPrize','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/tournament_prizes/{id}' => ['get' => ['tags'=>['tournaments'],'summary'=>'Get TournamentPrize','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['tournaments'],'summary'=>'Update TournamentPrize','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['tournaments'],'summary'=>'Delete TournamentPrize','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/awarded_prizes' => ['get' => ['tags'=>['tournaments'],'summary'=>'List AwardedPrize','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['tournaments'],'summary'=>'Create AwardedPrize','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/awarded_prizes/{id}' => ['get' => ['tags'=>['tournaments'],'summary'=>'Get AwardedPrize','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['tournaments'],'summary'=>'Update AwardedPrize','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['tournaments'],'summary'=>'Delete AwardedPrize','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/products' => ['get' => ['tags'=>['marketplace'],'summary'=>'List Product','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['marketplace'],'summary'=>'Create Product','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/products/{id}' => ['get' => ['tags'=>['marketplace'],'summary'=>'Get Product','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['marketplace'],'summary'=>'Update Product','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['marketplace'],'summary'=>'Delete Product','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/orders' => ['get' => ['tags'=>['marketplace'],'summary'=>'List Order','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['marketplace'],'summary'=>'Create Order','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/orders/{id}' => ['get' => ['tags'=>['marketplace'],'summary'=>'Get Order','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['marketplace'],'summary'=>'Update Order','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['marketplace'],'summary'=>'Delete Order','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/order_items' => ['get' => ['tags'=>['marketplace'],'summary'=>'List OrderItem','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['marketplace'],'summary'=>'Create OrderItem','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/order_items/{id}' => ['get' => ['tags'=>['marketplace'],'summary'=>'Get OrderItem','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['marketplace'],'summary'=>'Update OrderItem','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['marketplace'],'summary'=>'Delete OrderItem','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/coupons' => ['get' => ['tags'=>['marketplace'],'summary'=>'List Coupon','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['marketplace'],'summary'=>'Create Coupon','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/coupons/{id}' => ['get' => ['tags'=>['marketplace'],'summary'=>'Get Coupon','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['marketplace'],'summary'=>'Update Coupon','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['marketplace'],'summary'=>'Delete Coupon','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/tradelistings' => ['get' => ['tags'=>['marketplace'],'summary'=>'List Tradelisting','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['marketplace'],'summary'=>'Create Tradelisting','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/tradelistings/{id}' => ['get' => ['tags'=>['marketplace'],'summary'=>'Get Tradelisting','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['marketplace'],'summary'=>'Update Tradelisting','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['marketplace'],'summary'=>'Delete Tradelisting','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/trade_bids' => ['get' => ['tags'=>['marketplace'],'summary'=>'List TradeBid','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['marketplace'],'summary'=>'Create TradeBid','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/trade_bids/{id}' => ['get' => ['tags'=>['marketplace'],'summary'=>'Get TradeBid','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['marketplace'],'summary'=>'Update TradeBid','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['marketplace'],'summary'=>'Delete TradeBid','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/trade_transactions' => ['get' => ['tags'=>['marketplace'],'summary'=>'List TradeTransaction','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['marketplace'],'summary'=>'Create TradeTransaction','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/trade_transactions/{id}' => ['get' => ['tags'=>['marketplace'],'summary'=>'Get TradeTransaction','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['marketplace'],'summary'=>'Update TradeTransaction','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['marketplace'],'summary'=>'Delete TradeTransaction','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/card_price_histories' => ['get' => ['tags'=>['marketplace'],'summary'=>'List CardPriceHistory','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['marketplace'],'summary'=>'Create CardPriceHistory','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/card_price_histories/{id}' => ['get' => ['tags'=>['marketplace'],'summary'=>'Get CardPriceHistory','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['marketplace'],'summary'=>'Update CardPriceHistory','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['marketplace'],'summary'=>'Delete CardPriceHistory','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/trade_disputes' => ['get' => ['tags'=>['marketplace'],'summary'=>'List TradeDispute','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['marketplace'],'summary'=>'Create TradeDispute','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/trade_disputes/{id}' => ['get' => ['tags'=>['marketplace'],'summary'=>'Get TradeDispute','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['marketplace'],'summary'=>'Update TradeDispute','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['marketplace'],'summary'=>'Delete TradeDispute','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/draft_sessions' => ['get' => ['tags'=>['content'],'summary'=>'List DraftSession','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['content'],'summary'=>'Create DraftSession','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/draft_sessions/{id}' => ['get' => ['tags'=>['content'],'summary'=>'Get DraftSession','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['content'],'summary'=>'Update DraftSession','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['content'],'summary'=>'Delete DraftSession','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/draft_participants' => ['get' => ['tags'=>['content'],'summary'=>'List DraftParticipant','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['content'],'summary'=>'Create DraftParticipant','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/draft_participants/{id}' => ['get' => ['tags'=>['content'],'summary'=>'Get DraftParticipant','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['content'],'summary'=>'Update DraftParticipant','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['content'],'summary'=>'Delete DraftParticipant','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/draft_picks' => ['get' => ['tags'=>['content'],'summary'=>'List DraftPick','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['content'],'summary'=>'Create DraftPick','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/draft_picks/{id}' => ['get' => ['tags'=>['content'],'summary'=>'Get DraftPick','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['content'],'summary'=>'Update DraftPick','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['content'],'summary'=>'Delete DraftPick','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/articles' => ['get' => ['tags'=>['content'],'summary'=>'List Article','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['content'],'summary'=>'Create Article','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/articles/{id}' => ['get' => ['tags'=>['content'],'summary'=>'Get Article','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['content'],'summary'=>'Update Article','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['content'],'summary'=>'Delete Article','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/article_tags' => ['get' => ['tags'=>['content'],'summary'=>'List ArticleTag','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['content'],'summary'=>'Create ArticleTag','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/article_tags/{id}' => ['get' => ['tags'=>['content'],'summary'=>'Get ArticleTag','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['content'],'summary'=>'Update ArticleTag','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['content'],'summary'=>'Delete ArticleTag','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/article_tag_assignments' => ['get' => ['tags'=>['content'],'summary'=>'List ArticleTagAssignment','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['content'],'summary'=>'Create ArticleTagAssignment','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/article_tag_assignments/{id}' => ['get' => ['tags'=>['content'],'summary'=>'Get ArticleTagAssignment','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['content'],'summary'=>'Update ArticleTagAssignment','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['content'],'summary'=>'Delete ArticleTagAssignment','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/article_comments' => ['get' => ['tags'=>['content'],'summary'=>'List ArticleComment','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['content'],'summary'=>'Create ArticleComment','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/article_comments/{id}' => ['get' => ['tags'=>['content'],'summary'=>'Get ArticleComment','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['content'],'summary'=>'Update ArticleComment','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['content'],'summary'=>'Delete ArticleComment','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            '/api/streams' => ['get' => ['tags'=>['content'],'summary'=>'List Stream','responses'=>['200'=>['description'=>'OK']]],'post' => ['tags'=>['content'],'summary'=>'Create Stream','requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['201'=>['description'=>'Created']]]],
            '/api/streams/{id}' => ['get' => ['tags'=>['content'],'summary'=>'Get Stream','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['200'=>['description'=>'OK']]],'patch' => ['tags'=>['content'],'summary'=>'Update Stream','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'requestBody'=>['required'=>true,'content'=>['application/json'=>['schema'=>['type'=>'object']]]],'responses'=>['200'=>['description'=>'OK']]],'delete' => ['tags'=>['content'],'summary'=>'Delete Stream','parameters'=>[['name'=>'id','in'=>'path','required'=>true,'schema'=>['type'=>'integer']]],'responses'=>['204'=>['description'=>'No Content']]]],
            ],
        ]);
    }
}
