Rails.application.routes.draw do
  namespace :api do
    resources :cards, module: 'cards'
    resources :card_sets, module: 'cards'
    resources :card_rulings, module: 'cards'
    resources :card_abilities, module: 'cards'
    resources :decks, module: 'cards'
    resources :deck_cards, module: 'cards'
    resources :deck_sideboard_cards, module: 'cards'
    resources :deck_tags, module: 'cards'
    resources :deck_tag_assignments, module: 'cards'
    resources :players, module: 'players'
    resources :player_season_statses, module: 'players'
    resources :player_collections, module: 'players'
    resources :friendships, module: 'players'
    resources :achievements, module: 'players'
    resources :player_achievements, module: 'players'
    resources :crafting_recipes, module: 'players'
    resources :crafting_ingredients, module: 'players'
    resources :seasons, module: 'tournaments'
    resources :tournaments, module: 'tournaments'
    resources :tournament_judges, module: 'tournaments'
    resources :tournament_registrations, module: 'tournaments'
    resources :tournament_rounds, module: 'tournaments'
    resources :matches, module: 'tournaments'
    resources :games, module: 'tournaments'
    resources :tournament_prizes, module: 'tournaments'
    resources :awarded_prizes, module: 'tournaments'
    resources :products, module: 'marketplace'
    resources :orders, module: 'marketplace'
    resources :order_items, module: 'marketplace'
    resources :coupons, module: 'marketplace'
    resources :tradelistings, module: 'marketplace'
    resources :trade_bids, module: 'marketplace'
    resources :trade_transactions, module: 'marketplace'
    resources :card_price_histories, module: 'marketplace'
    resources :trade_disputes, module: 'marketplace'
    resources :draft_sessions, module: 'content'
    resources :draft_participants, module: 'content'
    resources :draft_picks, module: 'content'
    resources :articles, module: 'content'
    resources :article_tags, module: 'content'
    resources :article_tag_assignments, module: 'content'
    resources :article_comments, module: 'content'
    resources :streams, module: 'content'
  end
end
