package CardsProject;
use Mojo::Base 'Mojolicious', -signatures;
use CardsProject::Schema;

sub startup ($self) {
  my $dsn = $ENV{TEST_DATABASE_URL} || ('dbi:SQLite:dbname=' . $self->app->home->child('cards_project.db'));
  my $schema = CardsProject::Schema->connect(
    $dsn, '', '',
    { AutoCommit => 1, RaiseError => 1, sqlite_use_immediate_transaction => 1,
      on_connect_do => 'PRAGMA busy_timeout = 5000' }
  );
  eval { $schema->deploy({ add_drop_table => 0, ignore_errors => 1 }) };
  warn "deploy warning: $@" if $@ && $@ !~ /already exists/i;

  $self->helper(schema => sub { $schema });

  $self->plugin('DefaultHelpers');

  my $r = $self->routes;
  my $card = $r->any('/api/cards');
  $card->get->to('cards-card#list');
  $card->post->to('cards-card#create');
  my $card_item = $r->any('/api/cards/:id');
  $card_item->get->to('cards-card#show');
  $card_item->put->to('cards-card#update');
  $card_item->patch->to('cards-card#update');
  $r->any('/api/cards/:id/ban')->post->to('cards-card#ban');
  $r->any('/api/cards/:id/unban')->post->to('cards-card#unban');
  $r->any('/api/cards/:id/restrict')->post->to('cards-card#restrict');
  $r->any('/api/cards/:id/unrestrict')->post->to('cards-card#unrestrict');
  $r->any('/api/cards/:id/calculate_value')->get->to('cards-card#calculate_value');
  $r->any('/api/cards/:id/apply_rarity_bonus')->post->to('cards-card#apply_rarity_bonus');
  $r->any('/api/cards/:id/is_legal_in_format')->get->to('cards-card#is_legal_in_format');
  my $cardSet = $r->any('/api/card_sets');
  $cardSet->get->to('cards-card_set#list');
  $cardSet->post->to('cards-card_set#create');
  my $cardSet_item = $r->any('/api/card_sets/:id');
  $cardSet_item->get->to('cards-card_set#show');
  $cardSet_item->put->to('cards-card_set#update');
  $cardSet_item->patch->to('cards-card_set#update');
  $r->any('/api/card_sets/:id/is_legal_in_standard')->get->to('cards-card_set#is_legal_in_standard');
  $r->any('/api/card_sets/:id/is_legal_in_format')->get->to('cards-card_set#is_legal_in_format');
  $r->any('/api/card_sets/:id/card_count_by_rarity')->get->to('cards-card_set#card_count_by_rarity');
  $r->any('/api/card_sets/:id/rotate_out')->post->to('cards-card_set#rotate_out');
  my $cardRuling = $r->any('/api/card_rulings');
  $cardRuling->get->to('cards-card_ruling#list');
  $cardRuling->post->to('cards-card_ruling#create');
  my $cardRuling_item = $r->any('/api/card_rulings/:id');
  $cardRuling_item->get->to('cards-card_ruling#show');
  $cardRuling_item->delete->to('cards-card_ruling#delete');
  $r->any('/api/card_rulings/:id/is_current')->get->to('cards-card_ruling#is_current');
  $r->any('/api/card_rulings/:id/supersedes_previous')->get->to('cards-card_ruling#supersedes_previous');
  my $cardAbility = $r->any('/api/card_abilities');
  $cardAbility->get->to('cards-card_ability#list');
  $cardAbility->post->to('cards-card_ability#create');
  my $cardAbility_item = $r->any('/api/card_abilities/:id');
  $cardAbility_item->get->to('cards-card_ability#show');
  $cardAbility_item->put->to('cards-card_ability#update');
  $cardAbility_item->patch->to('cards-card_ability#update');
  $cardAbility_item->delete->to('cards-card_ability#delete');
  $r->any('/api/card_abilities/:id/is_usable_at')->get->to('cards-card_ability#is_usable_at');
  $r->any('/api/card_abilities/:id/describe')->get->to('cards-card_ability#describe');
  my $deck = $r->any('/api/decks');
  $deck->get->to('cards-deck#list');
  $deck->post->to('cards-deck#create');
  my $deck_item = $r->any('/api/decks/:id');
  $deck_item->get->to('cards-deck#show');
  $deck_item->put->to('cards-deck#update');
  $deck_item->patch->to('cards-deck#update');
  $deck_item->delete->to('cards-deck#delete');
  $r->any('/api/decks/:id/validate_size')->get->to('cards-deck#validate_size');
  $r->any('/api/decks/:id/add_card')->post->to('cards-deck#add_card');
  $r->any('/api/decks/:id/remove_card')->delete->to('cards-deck#remove_card');
  $r->any('/api/decks/:id/win_rate')->get->to('cards-deck#win_rate');
  $r->any('/api/decks/:id/clone')->post->to('cards-deck#clone');
  $r->any('/api/decks/:id/publish')->post->to('cards-deck#publish');
  $r->any('/api/decks/:id/unpublish')->post->to('cards-deck#unpublish');
  $r->any('/api/decks/:id/certify_tournament_legal')->post->to('cards-deck#certify_tournament_legal');
  my $deckCard = $r->any('/api/deck_cards');
  $deckCard->get->to('cards-deck_card#list');
  $deckCard->post->to('cards-deck_card#create');
  my $deckCard_item = $r->any('/api/deck_cards/:id');
  $deckCard_item->get->to('cards-deck_card#show');
  $deckCard_item->put->to('cards-deck_card#update');
  $deckCard_item->patch->to('cards-deck_card#update');
  $deckCard_item->delete->to('cards-deck_card#delete');
  $r->any('/api/deck_cards/:id/increment')->post->to('cards-deck_card#increment');
  $r->any('/api/deck_cards/:id/decrement')->post->to('cards-deck_card#decrement');
  my $deckSideboardCard = $r->any('/api/deck_sideboard_cards');
  $deckSideboardCard->get->to('cards-deck_sideboard_card#list');
  $deckSideboardCard->post->to('cards-deck_sideboard_card#create');
  my $deckSideboardCard_item = $r->any('/api/deck_sideboard_cards/:id');
  $deckSideboardCard_item->get->to('cards-deck_sideboard_card#show');
  $deckSideboardCard_item->put->to('cards-deck_sideboard_card#update');
  $deckSideboardCard_item->patch->to('cards-deck_sideboard_card#update');
  $deckSideboardCard_item->delete->to('cards-deck_sideboard_card#delete');
  $r->any('/api/deck_sideboard_cards/:id/increment')->post->to('cards-deck_sideboard_card#increment');
  $r->any('/api/deck_sideboard_cards/:id/decrement')->post->to('cards-deck_sideboard_card#decrement');
  my $deckTag = $r->any('/api/deck_tags');
  $deckTag->get->to('cards-deck_tag#list');
  $deckTag->post->to('cards-deck_tag#create');
  my $deckTag_item = $r->any('/api/deck_tags/:id');
  $deckTag_item->get->to('cards-deck_tag#show');
  $deckTag_item->put->to('cards-deck_tag#update');
  $deckTag_item->patch->to('cards-deck_tag#update');
  $deckTag_item->delete->to('cards-deck_tag#delete');
  $r->any('/api/deck_tags/:id/rename')->post->to('cards-deck_tag#rename');
  $r->any('/api/deck_tags/:id/merge_into')->post->to('cards-deck_tag#merge_into');
  my $deckTagAssignment = $r->any('/api/deck_tag_assignments');
  $deckTagAssignment->get->to('cards-deck_tag_assignment#list');
  $deckTagAssignment->post->to('cards-deck_tag_assignment#create');
  my $deckTagAssignment_item = $r->any('/api/deck_tag_assignments/:id');
  $deckTagAssignment_item->get->to('cards-deck_tag_assignment#show');
  $deckTagAssignment_item->delete->to('cards-deck_tag_assignment#delete');
  my $player = $r->any('/api/players');
  $player->get->to('players-player#list');
  $player->post->to('players-player#create');
  my $player_item = $r->any('/api/players/:id');
  $player_item->get->to('players-player#show');
  $player_item->put->to('players-player#update');
  $player_item->patch->to('players-player#update');
  $r->any('/api/players/:id/promote')->post->to('players-player#promote');
  $r->any('/api/players/:id/demote')->post->to('players-player#demote');
  $r->any('/api/players/:id/record_win')->post->to('players-player#record_win');
  $r->any('/api/players/:id/record_loss')->post->to('players-player#record_loss');
  $r->any('/api/players/:id/win_rate')->get->to('players-player#win_rate');
  $r->any('/api/players/:id/verify')->post->to('players-player#verify');
  $r->any('/api/players/:id/update_rating')->post->to('players-player#update_rating');
  my $playerSeasonStats = $r->any('/api/player_season_statses');
  $playerSeasonStats->get->to('players-player_season_stats#list');
  my $playerSeasonStats_item = $r->any('/api/player_season_statses/:id');
  $playerSeasonStats_item->get->to('players-player_season_stats#show');
  $r->any('/api/player_season_statses/:id/win_rate')->get->to('players-player_season_stats#win_rate');
  $r->any('/api/player_season_statses/:id/add_points')->post->to('players-player_season_stats#add_points');
  $r->any('/api/player_season_statses/:id/record_tournament_win')->post->to('players-player_season_stats#record_tournament_win');
  my $playerCollection = $r->any('/api/player_collections');
  $playerCollection->get->to('players-player_collection#list');
  $playerCollection->post->to('players-player_collection#create');
  my $playerCollection_item = $r->any('/api/player_collections/:id');
  $playerCollection_item->get->to('players-player_collection#show');
  $playerCollection_item->put->to('players-player_collection#update');
  $playerCollection_item->patch->to('players-player_collection#update');
  $playerCollection_item->delete->to('players-player_collection#delete');
  $r->any('/api/player_collections/:id/add')->post->to('players-player_collection#add');
  $r->any('/api/player_collections/:id/remove')->post->to('players-player_collection#remove');
  $r->any('/api/player_collections/:id/estimated_value')->get->to('players-player_collection#estimated_value');
  my $friendship = $r->any('/api/friendships');
  $friendship->get->to('players-friendship#list');
  $friendship->post->to('players-friendship#create');
  my $friendship_item = $r->any('/api/friendships/:id');
  $friendship_item->get->to('players-friendship#show');
  $friendship_item->delete->to('players-friendship#delete');
  $r->any('/api/friendships/:id/accept')->post->to('players-friendship#accept');
  $r->any('/api/friendships/:id/decline')->post->to('players-friendship#decline');
  $r->any('/api/friendships/:id/block')->post->to('players-friendship#block');
  my $achievement = $r->any('/api/achievements');
  $achievement->get->to('players-achievement#list');
  $achievement->post->to('players-achievement#create');
  my $achievement_item = $r->any('/api/achievements/:id');
  $achievement_item->get->to('players-achievement#show');
  $achievement_item->put->to('players-achievement#update');
  $achievement_item->patch->to('players-achievement#update');
  $r->any('/api/achievements/:id/point_value')->get->to('players-achievement#point_value');
  $r->any('/api/achievements/:id/reveal')->post->to('players-achievement#reveal');
  my $playerAchievement = $r->any('/api/player_achievements');
  $playerAchievement->get->to('players-player_achievement#list');
  my $playerAchievement_item = $r->any('/api/player_achievements/:id');
  $playerAchievement_item->get->to('players-player_achievement#show');
  $r->any('/api/player_achievements/:id/increment_progress')->post->to('players-player_achievement#increment_progress');
  $r->any('/api/player_achievements/:id/complete')->post->to('players-player_achievement#complete');
  my $craftingRecipe = $r->any('/api/crafting_recipes');
  $craftingRecipe->get->to('players-crafting_recipe#list');
  $craftingRecipe->post->to('players-crafting_recipe#create');
  my $craftingRecipe_item = $r->any('/api/crafting_recipes/:id');
  $craftingRecipe_item->get->to('players-crafting_recipe#show');
  $craftingRecipe_item->put->to('players-crafting_recipe#update');
  $craftingRecipe_item->patch->to('players-crafting_recipe#update');
  $r->any('/api/crafting_recipes/:id/can_craft')->get->to('players-crafting_recipe#can_craft');
  $r->any('/api/crafting_recipes/:id/execute_craft')->post->to('players-crafting_recipe#execute_craft');
  $r->any('/api/crafting_recipes/:id/disable')->post->to('players-crafting_recipe#disable');
  $r->any('/api/crafting_recipes/:id/enable')->post->to('players-crafting_recipe#enable');
  my $craftingIngredient = $r->any('/api/crafting_ingredients');
  $craftingIngredient->get->to('players-crafting_ingredient#list');
  $craftingIngredient->post->to('players-crafting_ingredient#create');
  my $craftingIngredient_item = $r->any('/api/crafting_ingredients/:id');
  $craftingIngredient_item->get->to('players-crafting_ingredient#show');
  $craftingIngredient_item->delete->to('players-crafting_ingredient#delete');
  my $season = $r->any('/api/seasons');
  $season->get->to('tournaments-season#list');
  $season->post->to('tournaments-season#create');
  my $season_item = $r->any('/api/seasons/:id');
  $season_item->get->to('tournaments-season#show');
  $season_item->put->to('tournaments-season#update');
  $season_item->patch->to('tournaments-season#update');
  $r->any('/api/seasons/:id/activate')->post->to('tournaments-season#activate');
  $r->any('/api/seasons/:id/deactivate')->post->to('tournaments-season#deactivate');
  $r->any('/api/seasons/:id/finalize_rewards')->post->to('tournaments-season#finalize_rewards');
  $r->any('/api/seasons/:id/is_ongoing')->get->to('tournaments-season#is_ongoing');
  my $tournament = $r->any('/api/tournaments');
  $tournament->get->to('tournaments-tournament#list');
  $tournament->post->to('tournaments-tournament#create');
  my $tournament_item = $r->any('/api/tournaments/:id');
  $tournament_item->get->to('tournaments-tournament#show');
  $tournament_item->put->to('tournaments-tournament#update');
  $tournament_item->patch->to('tournaments-tournament#update');
  $r->any('/api/tournaments/:id/start')->post->to('tournaments-tournament#start');
  $r->any('/api/tournaments/:id/cancel')->post->to('tournaments-tournament#cancel');
  $r->any('/api/tournaments/:id/complete')->post->to('tournaments-tournament#complete');
  $r->any('/api/tournaments/:id/generate_round')->post->to('tournaments-tournament#generate_round');
  $r->any('/api/tournaments/:id/calculate_prize_distribution')->get->to('tournaments-tournament#calculate_prize_distribution');
  $r->any('/api/tournaments/:id/register_player')->post->to('tournaments-tournament#register_player');
  $r->any('/api/tournaments/:id/is_full')->get->to('tournaments-tournament#is_full');
  $r->patch('/api/tournaments/:id/transitions/draft-to-registration')->to('tournaments-tournament#transition_draft_to_registration');
  $r->patch('/api/tournaments/:id/transitions/registration-to-ongoing')->to('tournaments-tournament#transition_registration_to_ongoing');
  $r->patch('/api/tournaments/:id/transitions/registration-to-cancelled')->to('tournaments-tournament#transition_registration_to_cancelled');
  $r->patch('/api/tournaments/:id/transitions/ongoing-to-completed')->to('tournaments-tournament#transition_ongoing_to_completed');
  $r->patch('/api/tournaments/:id/transitions/ongoing-to-cancelled')->to('tournaments-tournament#transition_ongoing_to_cancelled');
  $r->patch('/api/tournaments/:id/transitions/completed-to-draft')->to('tournaments-tournament#transition_completed_to_draft');
  $r->patch('/api/tournaments/:id/transitions/cancelled-to-draft')->to('tournaments-tournament#transition_cancelled_to_draft');
  my $tournamentJudge = $r->any('/api/tournament_judges');
  $tournamentJudge->get->to('tournaments-tournament_judge#list');
  $tournamentJudge->post->to('tournaments-tournament_judge#create');
  my $tournamentJudge_item = $r->any('/api/tournament_judges/:id');
  $tournamentJudge_item->get->to('tournaments-tournament_judge#show');
  $tournamentJudge_item->delete->to('tournaments-tournament_judge#delete');
  $r->any('/api/tournament_judges/:id/promote_to_head')->post->to('tournaments-tournament_judge#promote_to_head');
  $r->any('/api/tournament_judges/:id/remove')->delete->to('tournaments-tournament_judge#remove');
  my $tournamentRegistration = $r->any('/api/tournament_registrations');
  $tournamentRegistration->get->to('tournaments-tournament_registration#list');
  $tournamentRegistration->post->to('tournaments-tournament_registration#create');
  my $tournamentRegistration_item = $r->any('/api/tournament_registrations/:id');
  $tournamentRegistration_item->get->to('tournaments-tournament_registration#show');
  $r->any('/api/tournament_registrations/:id/withdraw')->post->to('tournaments-tournament_registration#withdraw');
  $r->any('/api/tournament_registrations/:id/disqualify')->post->to('tournaments-tournament_registration#disqualify');
  $r->any('/api/tournament_registrations/:id/promote_from_waitlist')->post->to('tournaments-tournament_registration#promote_from_waitlist');
  my $tournamentRound = $r->any('/api/tournament_rounds');
  $tournamentRound->get->to('tournaments-tournament_round#list');
  $tournamentRound->post->to('tournaments-tournament_round#create');
  my $tournamentRound_item = $r->any('/api/tournament_rounds/:id');
  $tournamentRound_item->get->to('tournaments-tournament_round#show');
  $r->any('/api/tournament_rounds/:id/start')->post->to('tournaments-tournament_round#start');
  $r->any('/api/tournament_rounds/:id/complete')->post->to('tournaments-tournament_round#complete');
  $r->any('/api/tournament_rounds/:id/generate_pairings')->post->to('tournaments-tournament_round#generate_pairings');
  $r->any('/api/tournament_rounds/:id/is_time_expired')->get->to('tournaments-tournament_round#is_time_expired');
  my $match = $r->any('/api/matches');
  $match->get->to('tournaments-match#list');
  $match->post->to('tournaments-match#create');
  my $match_item = $r->any('/api/matches/:id');
  $match_item->get->to('tournaments-match#show');
  $r->any('/api/matches/:id/record_result')->post->to('tournaments-match#record_result');
  $r->any('/api/matches/:id/finalize_result')->post->to('tournaments-match#finalize_result');
  $r->any('/api/matches/:id/determine_winner')->get->to('tournaments-match#determine_winner');
  $r->any('/api/matches/:id/concede')->post->to('tournaments-match#concede');
  $r->any('/api/matches/:id/draw')->post->to('tournaments-match#draw');
  $r->patch('/api/matches/:id/transitions/pending-to-active')->to('tournaments-match#transition_pending_to_active');
  $r->patch('/api/matches/:id/transitions/active-to-completed')->to('tournaments-match#transition_active_to_completed');
  $r->patch('/api/matches/:id/transitions/active-to-draw')->to('tournaments-match#transition_active_to_draw');
  $r->patch('/api/matches/:id/transitions/pending-to-b_y_e')->to('tournaments-match#transition_pending_to_b_y_e');
  $r->patch('/api/matches/:id/transitions/completed-to-active')->to('tournaments-match#transition_completed_to_active');
  $r->patch('/api/matches/:id/transitions/draw-to-active')->to('tournaments-match#transition_draw_to_active');
  $r->patch('/api/matches/:id/transitions/b_y_e-to-active')->to('tournaments-match#transition_b_y_e_to_active');
  my $game = $r->any('/api/games');
  $game->get->to('tournaments-game#list');
  $game->post->to('tournaments-game#create');
  my $game_item = $r->any('/api/games/:id');
  $game_item->get->to('tournaments-game#show');
  $r->any('/api/games/:id/record_winner')->post->to('tournaments-game#record_winner');
  $r->any('/api/games/:id/duration_minutes')->get->to('tournaments-game#duration_minutes');
  my $tournamentPrize = $r->any('/api/tournament_prizes');
  $tournamentPrize->get->to('tournaments-tournament_prize#list');
  $tournamentPrize->post->to('tournaments-tournament_prize#create');
  my $tournamentPrize_item = $r->any('/api/tournament_prizes/:id');
  $tournamentPrize_item->get->to('tournaments-tournament_prize#show');
  $tournamentPrize_item->put->to('tournaments-tournament_prize#update');
  $tournamentPrize_item->patch->to('tournaments-tournament_prize#update');
  $tournamentPrize_item->delete->to('tournaments-tournament_prize#delete');
  $r->any('/api/tournament_prizes/:id/applies_to_placement')->get->to('tournaments-tournament_prize#applies_to_placement');
  $r->any('/api/tournament_prizes/:id/award_to_player')->post->to('tournaments-tournament_prize#award_to_player');
  my $awardedPrize = $r->any('/api/awarded_prizes');
  $awardedPrize->get->to('tournaments-awarded_prize#list');
  my $awardedPrize_item = $r->any('/api/awarded_prizes/:id');
  $awardedPrize_item->get->to('tournaments-awarded_prize#show');
  $r->any('/api/awarded_prizes/:id/claim')->post->to('tournaments-awarded_prize#claim');
  my $product = $r->any('/api/products');
  $product->get->to('marketplace-product#list');
  $product->post->to('marketplace-product#create');
  my $product_item = $r->any('/api/products/:id');
  $product_item->get->to('marketplace-product#show');
  $product_item->put->to('marketplace-product#update');
  $product_item->patch->to('marketplace-product#update');
  $r->any('/api/products/:id/activate')->post->to('marketplace-product#activate');
  $r->any('/api/products/:id/deactivate')->post->to('marketplace-product#deactivate');
  $r->any('/api/products/:id/apply_discount')->post->to('marketplace-product#apply_discount');
  $r->any('/api/products/:id/restock')->post->to('marketplace-product#restock');
  $r->any('/api/products/:id/effective_price')->get->to('marketplace-product#effective_price');
  $r->any('/api/products/:id/is_in_stock')->get->to('marketplace-product#is_in_stock');
  my $order = $r->any('/api/orders');
  $order->get->to('marketplace-order#list');
  $order->post->to('marketplace-order#create');
  my $order_item = $r->any('/api/orders/:id');
  $order_item->get->to('marketplace-order#show');
  $r->any('/api/orders/:id/cancel')->delete->to('marketplace-order#cancel');
  $r->any('/api/orders/:id/pay')->post->to('marketplace-order#pay');
  $r->any('/api/orders/:id/process_payment')->post->to('marketplace-order#process_payment');
  $r->any('/api/orders/:id/calculate_total')->get->to('marketplace-order#calculate_total');
  $r->any('/api/orders/:id/apply_discount')->post->to('marketplace-order#apply_discount');
  $r->any('/api/orders/:id/refund')->post->to('marketplace-order#refund');
  $r->patch('/api/orders/:id/transitions/pending-to-paid')->to('marketplace-order#transition_pending_to_paid');
  $r->patch('/api/orders/:id/transitions/paid-to-processing')->to('marketplace-order#transition_paid_to_processing');
  $r->patch('/api/orders/:id/transitions/processing-to-shipped')->to('marketplace-order#transition_processing_to_shipped');
  $r->patch('/api/orders/:id/transitions/shipped-to-completed')->to('marketplace-order#transition_shipped_to_completed');
  $r->patch('/api/orders/:id/transitions/pending-to-cancelled')->to('marketplace-order#transition_pending_to_cancelled');
  $r->patch('/api/orders/:id/transitions/paid-to-cancelled')->to('marketplace-order#transition_paid_to_cancelled');
  $r->patch('/api/orders/:id/transitions/completed-to-refunded')->to('marketplace-order#transition_completed_to_refunded');
  $r->patch('/api/orders/:id/transitions/refunded-to-completed')->to('marketplace-order#transition_refunded_to_completed');
  $r->patch('/api/orders/:id/transitions/completed-to-cancelled')->to('marketplace-order#transition_completed_to_cancelled');
  my $orderItem = $r->any('/api/order_items');
  $orderItem->get->to('marketplace-order_item#list');
  $orderItem->post->to('marketplace-order_item#create');
  my $orderItem_item = $r->any('/api/order_items/:id');
  $orderItem_item->get->to('marketplace-order_item#show');
  $orderItem_item->delete->to('marketplace-order_item#delete');
  $r->any('/api/order_items/:id/line_total')->get->to('marketplace-order_item#line_total');
  my $coupon = $r->any('/api/coupons');
  $coupon->get->to('marketplace-coupon#list');
  $coupon->post->to('marketplace-coupon#create');
  my $coupon_item = $r->any('/api/coupons/:id');
  $coupon_item->get->to('marketplace-coupon#show');
  $coupon_item->put->to('marketplace-coupon#update');
  $coupon_item->patch->to('marketplace-coupon#update');
  $r->any('/api/coupons/:id/is_valid')->get->to('marketplace-coupon#is_valid');
  $r->any('/api/coupons/:id/is_applicable_to_order')->get->to('marketplace-coupon#is_applicable_to_order');
  $r->any('/api/coupons/:id/redeem')->post->to('marketplace-coupon#redeem');
  $r->any('/api/coupons/:id/deactivate')->post->to('marketplace-coupon#deactivate');
  my $tradeListing = $r->any('/api/trade_listings');
  $tradeListing->get->to('marketplace-trade_listing#list');
  $tradeListing->post->to('marketplace-trade_listing#create');
  my $tradeListing_item = $r->any('/api/trade_listings/:id');
  $tradeListing_item->get->to('marketplace-trade_listing#show');
  $tradeListing_item->put->to('marketplace-trade_listing#update');
  $tradeListing_item->patch->to('marketplace-trade_listing#update');
  $r->any('/api/trade_listings/:id/close')->post->to('marketplace-trade_listing#close');
  $r->any('/api/trade_listings/:id/extend')->post->to('marketplace-trade_listing#extend');
  $r->any('/api/trade_listings/:id/cancel')->delete->to('marketplace-trade_listing#cancel');
  $r->any('/api/trade_listings/:id/is_expired')->get->to('marketplace-trade_listing#is_expired');
  $r->any('/api/trade_listings/:id/finalize_auction')->post->to('marketplace-trade_listing#finalize_auction');
  $r->patch('/api/trade_listings/:id/transitions/pending-to-active')->to('marketplace-trade_listing#transition_pending_to_active');
  $r->patch('/api/trade_listings/:id/transitions/active-to-sold')->to('marketplace-trade_listing#transition_active_to_sold');
  $r->patch('/api/trade_listings/:id/transitions/active-to-expired')->to('marketplace-trade_listing#transition_active_to_expired');
  $r->patch('/api/trade_listings/:id/transitions/active-to-cancelled')->to('marketplace-trade_listing#transition_active_to_cancelled');
  $r->patch('/api/trade_listings/:id/transitions/sold-to-active')->to('marketplace-trade_listing#transition_sold_to_active');
  $r->patch('/api/trade_listings/:id/transitions/expired-to-active')->to('marketplace-trade_listing#transition_expired_to_active');
  my $tradeBid = $r->any('/api/trade_bids');
  $tradeBid->get->to('marketplace-trade_bid#list');
  $tradeBid->post->to('marketplace-trade_bid#create');
  my $tradeBid_item = $r->any('/api/trade_bids/:id');
  $tradeBid_item->get->to('marketplace-trade_bid#show');
  $r->any('/api/trade_bids/:id/outbid_by')->get->to('marketplace-trade_bid#outbid_by');
  $r->any('/api/trade_bids/:id/retract')->delete->to('marketplace-trade_bid#retract');
  my $tradeTransaction = $r->any('/api/trade_transactions');
  $tradeTransaction->get->to('marketplace-trade_transaction#list');
  my $tradeTransaction_item = $r->any('/api/trade_transactions/:id');
  $tradeTransaction_item->get->to('marketplace-trade_transaction#show');
  $r->any('/api/trade_transactions/:id/complete')->post->to('marketplace-trade_transaction#complete');
  $r->any('/api/trade_transactions/:id/refund')->post->to('marketplace-trade_transaction#refund');
  $r->any('/api/trade_transactions/:id/open_dispute')->post->to('marketplace-trade_transaction#open_dispute');
  $r->any('/api/trade_transactions/:id/seller_net')->get->to('marketplace-trade_transaction#seller_net');
  my $cardPriceHistory = $r->any('/api/card_price_histories');
  $cardPriceHistory->get->to('marketplace-card_price_history#list');
  my $cardPriceHistory_item = $r->any('/api/card_price_histories/:id');
  $cardPriceHistory_item->get->to('marketplace-card_price_history#show');
  $r->any('/api/card_price_histories/:id/price_change_percent')->get->to('marketplace-card_price_history#price_change_percent');
  $r->any('/api/card_price_histories/:id/is_price_spike')->get->to('marketplace-card_price_history#is_price_spike');
  my $tradeDispute = $r->any('/api/trade_disputes');
  $tradeDispute->get->to('marketplace-trade_dispute#list');
  $tradeDispute->post->to('marketplace-trade_dispute#create');
  my $tradeDispute_item = $r->any('/api/trade_disputes/:id');
  $tradeDispute_item->get->to('marketplace-trade_dispute#show');
  $r->any('/api/trade_disputes/:id/escalate')->post->to('marketplace-trade_dispute#escalate');
  $r->any('/api/trade_disputes/:id/resolve')->post->to('marketplace-trade_dispute#resolve');
  $r->any('/api/trade_disputes/:id/close_resolved')->post->to('marketplace-trade_dispute#close_resolved');
  $r->any('/api/trade_disputes/:id/review')->post->to('marketplace-trade_dispute#review');
  $r->patch('/api/trade_disputes/:id/transitions/open-to-under_review')->to('marketplace-trade_dispute#transition_open_to_under_review');
  $r->patch('/api/trade_disputes/:id/transitions/under_review-to-resolved')->to('marketplace-trade_dispute#transition_under_review_to_resolved');
  $r->patch('/api/trade_disputes/:id/transitions/under_review-to-escalated')->to('marketplace-trade_dispute#transition_under_review_to_escalated');
  $r->patch('/api/trade_disputes/:id/transitions/escalated-to-resolved')->to('marketplace-trade_dispute#transition_escalated_to_resolved');
  $r->patch('/api/trade_disputes/:id/transitions/resolved-to-open')->to('marketplace-trade_dispute#transition_resolved_to_open');
  my $draftSession = $r->any('/api/draft_sessions');
  $draftSession->get->to('content-draft_session#list');
  $draftSession->post->to('content-draft_session#create');
  my $draftSession_item = $r->any('/api/draft_sessions/:id');
  $draftSession_item->get->to('content-draft_session#show');
  $r->any('/api/draft_sessions/:id/start')->post->to('content-draft_session#start');
  $r->any('/api/draft_sessions/:id/abandon')->post->to('content-draft_session#abandon');
  $r->any('/api/draft_sessions/:id/complete')->post->to('content-draft_session#complete');
  $r->any('/api/draft_sessions/:id/is_full')->get->to('content-draft_session#is_full');
  $r->patch('/api/draft_sessions/:id/transitions/waiting_for_players-to-drafting')->to('content-draft_session#transition_waiting_for_players_to_drafting');
  $r->patch('/api/draft_sessions/:id/transitions/drafting-to-completed')->to('content-draft_session#transition_drafting_to_completed');
  $r->patch('/api/draft_sessions/:id/transitions/drafting-to-abandoned')->to('content-draft_session#transition_drafting_to_abandoned');
  $r->patch('/api/draft_sessions/:id/transitions/waiting_for_players-to-abandoned')->to('content-draft_session#transition_waiting_for_players_to_abandoned');
  $r->patch('/api/draft_sessions/:id/transitions/completed-to-drafting')->to('content-draft_session#transition_completed_to_drafting');
  $r->patch('/api/draft_sessions/:id/transitions/abandoned-to-drafting')->to('content-draft_session#transition_abandoned_to_drafting');
  my $draftParticipant = $r->any('/api/draft_participants');
  $draftParticipant->get->to('content-draft_participant#list');
  $draftParticipant->post->to('content-draft_participant#create');
  my $draftParticipant_item = $r->any('/api/draft_participants/:id');
  $draftParticipant_item->get->to('content-draft_participant#show');
  $r->any('/api/draft_participants/:id/pick_card')->post->to('content-draft_participant#pick_card');
  $r->any('/api/draft_participants/:id/drafted_card_count')->get->to('content-draft_participant#drafted_card_count');
  my $draftPick = $r->any('/api/draft_picks');
  $draftPick->get->to('content-draft_pick#list');
  my $draftPick_item = $r->any('/api/draft_picks/:id');
  $draftPick_item->get->to('content-draft_pick#show');
  $r->any('/api/draft_picks/:id/is_first_pick')->get->to('content-draft_pick#is_first_pick');
  my $article = $r->any('/api/articles');
  $article->get->to('content-article#list');
  $article->post->to('content-article#create');
  my $article_item = $r->any('/api/articles/:id');
  $article_item->get->to('content-article#show');
  $article_item->put->to('content-article#update');
  $article_item->patch->to('content-article#update');
  $r->any('/api/articles/:id/publish')->post->to('content-article#publish');
  $r->any('/api/articles/:id/archive')->post->to('content-article#archive');
  $r->any('/api/articles/:id/increment_view')->post->to('content-article#increment_view');
  $r->any('/api/articles/:id/like')->post->to('content-article#like');
  $r->any('/api/articles/:id/unlike')->delete->to('content-article#unlike');
  $r->any('/api/articles/:id/reading_time_minutes')->get->to('content-article#reading_time_minutes');
  $r->patch('/api/articles/:id/transitions/draft-to-published')->to('content-article#transition_draft_to_published');
  $r->patch('/api/articles/:id/transitions/published-to-archived')->to('content-article#transition_published_to_archived');
  $r->patch('/api/articles/:id/transitions/archived-to-draft')->to('content-article#transition_archived_to_draft');
  $r->patch('/api/articles/:id/transitions/published-to-draft')->to('content-article#transition_published_to_draft');
  my $articleTag = $r->any('/api/article_tags');
  $articleTag->get->to('content-article_tag#list');
  $articleTag->post->to('content-article_tag#create');
  my $articleTag_item = $r->any('/api/article_tags/:id');
  $articleTag_item->get->to('content-article_tag#show');
  $articleTag_item->put->to('content-article_tag#update');
  $articleTag_item->patch->to('content-article_tag#update');
  $articleTag_item->delete->to('content-article_tag#delete');
  $r->any('/api/article_tags/:id/rename')->post->to('content-article_tag#rename');
  $r->any('/api/article_tags/:id/article_count')->get->to('content-article_tag#article_count');
  my $articleTagAssignment = $r->any('/api/article_tag_assignments');
  $articleTagAssignment->get->to('content-article_tag_assignment#list');
  $articleTagAssignment->post->to('content-article_tag_assignment#create');
  my $articleTagAssignment_item = $r->any('/api/article_tag_assignments/:id');
  $articleTagAssignment_item->get->to('content-article_tag_assignment#show');
  $articleTagAssignment_item->delete->to('content-article_tag_assignment#delete');
  my $articleComment = $r->any('/api/article_comments');
  $articleComment->get->to('content-article_comment#list');
  $articleComment->post->to('content-article_comment#create');
  my $articleComment_item = $r->any('/api/article_comments/:id');
  $articleComment_item->get->to('content-article_comment#show');
  $articleComment_item->delete->to('content-article_comment#delete');
  $r->any('/api/article_comments/:id/hide')->post->to('content-article_comment#hide');
  $r->any('/api/article_comments/:id/unhide')->post->to('content-article_comment#unhide');
  $r->any('/api/article_comments/:id/is_reply')->get->to('content-article_comment#is_reply');
  my $stream = $r->any('/api/streams');
  $stream->get->to('content-stream#list');
  $stream->post->to('content-stream#create');
  my $stream_item = $r->any('/api/streams/:id');
  $stream_item->get->to('content-stream#show');
  $stream_item->put->to('content-stream#update');
  $stream_item->patch->to('content-stream#update');
  $r->any('/api/streams/:id/go_live')->post->to('content-stream#go_live');
  $r->any('/api/streams/:id/end')->post->to('content-stream#end');
  $r->any('/api/streams/:id/update_viewer_peak')->post->to('content-stream#update_viewer_peak');
  $r->any('/api/streams/:id/duration_minutes')->get->to('content-stream#duration_minutes');
  $r->patch('/api/streams/:id/transitions/scheduled-to-live')->to('content-stream#transition_scheduled_to_live');
  $r->patch('/api/streams/:id/transitions/live-to-ended')->to('content-stream#transition_live_to_ended');
  $r->patch('/api/streams/:id/transitions/ended-to-live')->to('content-stream#transition_ended_to_live');
}

1;
