<?php

namespace Proxies\__CG__\App\Entity\Tournaments;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Season extends \App\Entity\Tournaments\Season implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'endDate' => [parent::class, 'endDate', null, 16],
        "\0".parent::class."\0".'format' => [parent::class, 'format', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'rewardDescription' => [parent::class, 'rewardDescription', null, 16],
        "\0".parent::class."\0".'startDate' => [parent::class, 'startDate', null, 16],
        'endDate' => [parent::class, 'endDate', null, 16],
        'format' => [parent::class, 'format', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isActive' => [parent::class, 'isActive', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'rewardDescription' => [parent::class, 'rewardDescription', null, 16],
        'startDate' => [parent::class, 'startDate', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
