<?php

namespace Proxies\__CG__\App\Entity\Players;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CraftingRecipe extends \App\Entity\Players\CraftingRecipe implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dustCost' => [parent::class, 'dustCost', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isAvailable' => [parent::class, 'isAvailable', null, 16],
        "\0".parent::class."\0".'requiredCards' => [parent::class, 'requiredCards', null, 16],
        "\0".parent::class."\0".'resultCard' => [parent::class, 'resultCard', null, 16],
        'dustCost' => [parent::class, 'dustCost', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isAvailable' => [parent::class, 'isAvailable', null, 16],
        'requiredCards' => [parent::class, 'requiredCards', null, 16],
        'resultCard' => [parent::class, 'resultCard', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
