<?php

namespace Proxies\__CG__\App\Entity\Content;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ArticleComment extends \App\Entity\Content\ArticleComment implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'article' => [parent::class, 'article', null, 16],
        "\0".parent::class."\0".'author' => [parent::class, 'author', null, 16],
        "\0".parent::class."\0".'body' => [parent::class, 'body', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isHidden' => [parent::class, 'isHidden', null, 16],
        "\0".parent::class."\0".'parentComment' => [parent::class, 'parentComment', null, 16],
        'article' => [parent::class, 'article', null, 16],
        'author' => [parent::class, 'author', null, 16],
        'body' => [parent::class, 'body', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isHidden' => [parent::class, 'isHidden', null, 16],
        'parentComment' => [parent::class, 'parentComment', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
