<?php

namespace Proxies\__CG__\App\Entity\Cards;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Card extends \App\Entity\Cards\Card implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'abilities' => [parent::class, 'abilities', null, 16],
        "\0".parent::class."\0".'artistName' => [parent::class, 'artistName', null, 16],
        "\0".parent::class."\0".'attack' => [parent::class, 'attack', null, 16],
        "\0".parent::class."\0".'cardType' => [parent::class, 'cardType', null, 16],
        "\0".parent::class."\0".'defense' => [parent::class, 'defense', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'flavorText' => [parent::class, 'flavorText', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'imageUrl' => [parent::class, 'imageUrl', null, 16],
        "\0".parent::class."\0".'isBanned' => [parent::class, 'isBanned', null, 16],
        "\0".parent::class."\0".'isRestricted' => [parent::class, 'isRestricted', null, 16],
        "\0".parent::class."\0".'legalFormats' => [parent::class, 'legalFormats', null, 16],
        "\0".parent::class."\0".'loyalty' => [parent::class, 'loyalty', null, 16],
        "\0".parent::class."\0".'manaColors' => [parent::class, 'manaColors', null, 16],
        "\0".parent::class."\0".'manaCost' => [parent::class, 'manaCost', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'powerLevel' => [parent::class, 'powerLevel', null, 16],
        "\0".parent::class."\0".'rarity' => [parent::class, 'rarity', null, 16],
        "\0".parent::class."\0".'rulings' => [parent::class, 'rulings', null, 16],
        "\0".parent::class."\0".'set' => [parent::class, 'set', null, 16],
        'abilities' => [parent::class, 'abilities', null, 16],
        'artistName' => [parent::class, 'artistName', null, 16],
        'attack' => [parent::class, 'attack', null, 16],
        'cardType' => [parent::class, 'cardType', null, 16],
        'defense' => [parent::class, 'defense', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'flavorText' => [parent::class, 'flavorText', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'imageUrl' => [parent::class, 'imageUrl', null, 16],
        'isBanned' => [parent::class, 'isBanned', null, 16],
        'isRestricted' => [parent::class, 'isRestricted', null, 16],
        'legalFormats' => [parent::class, 'legalFormats', null, 16],
        'loyalty' => [parent::class, 'loyalty', null, 16],
        'manaColors' => [parent::class, 'manaColors', null, 16],
        'manaCost' => [parent::class, 'manaCost', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'powerLevel' => [parent::class, 'powerLevel', null, 16],
        'rarity' => [parent::class, 'rarity', null, 16],
        'rulings' => [parent::class, 'rulings', null, 16],
        'set' => [parent::class, 'set', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
