<?php

namespace Proxies\__CG__\App\Entity\Tournaments;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MatchRecord extends \App\Entity\Tournaments\MatchRecord implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'endedAt' => [parent::class, 'endedAt', null, 16],
        "\0".parent::class."\0".'games' => [parent::class, 'games', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'player1' => [parent::class, 'player1', null, 16],
        "\0".parent::class."\0".'player1Wins' => [parent::class, 'player1Wins', null, 16],
        "\0".parent::class."\0".'player2' => [parent::class, 'player2', null, 16],
        "\0".parent::class."\0".'player2Wins' => [parent::class, 'player2Wins', null, 16],
        "\0".parent::class."\0".'resultNotes' => [parent::class, 'resultNotes', null, 16],
        "\0".parent::class."\0".'round' => [parent::class, 'round', null, 16],
        "\0".parent::class."\0".'startedAt' => [parent::class, 'startedAt', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'tableNumber' => [parent::class, 'tableNumber', null, 16],
        'endedAt' => [parent::class, 'endedAt', null, 16],
        'games' => [parent::class, 'games', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'player1' => [parent::class, 'player1', null, 16],
        'player1Wins' => [parent::class, 'player1Wins', null, 16],
        'player2' => [parent::class, 'player2', null, 16],
        'player2Wins' => [parent::class, 'player2Wins', null, 16],
        'resultNotes' => [parent::class, 'resultNotes', null, 16],
        'round' => [parent::class, 'round', null, 16],
        'startedAt' => [parent::class, 'startedAt', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'tableNumber' => [parent::class, 'tableNumber', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
