<?php

namespace Proxies\__CG__\App\Entity\Players;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Player extends \App\Entity\Players\Player implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'achievements' => [parent::class, 'achievements', null, 16],
        "\0".parent::class."\0".'avatarUrl' => [parent::class, 'avatarUrl', null, 16],
        "\0".parent::class."\0".'bio' => [parent::class, 'bio', null, 16],
        "\0".parent::class."\0".'countryCode' => [parent::class, 'countryCode', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'displayName' => [parent::class, 'displayName', null, 16],
        "\0".parent::class."\0".'friends' => [parent::class, 'friends', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isVerified' => [parent::class, 'isVerified', null, 16],
        "\0".parent::class."\0".'lastActiveAt' => [parent::class, 'lastActiveAt', null, 16],
        "\0".parent::class."\0".'peakRating' => [parent::class, 'peakRating', null, 16],
        "\0".parent::class."\0".'preferredFormat' => [parent::class, 'preferredFormat', null, 16],
        "\0".parent::class."\0".'rank' => [parent::class, 'rank', null, 16],
        "\0".parent::class."\0".'rating' => [parent::class, 'rating', null, 16],
        "\0".parent::class."\0".'seasonStats' => [parent::class, 'seasonStats', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'achievements' => [parent::class, 'achievements', null, 16],
        'avatarUrl' => [parent::class, 'avatarUrl', null, 16],
        'bio' => [parent::class, 'bio', null, 16],
        'countryCode' => [parent::class, 'countryCode', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'displayName' => [parent::class, 'displayName', null, 16],
        'friends' => [parent::class, 'friends', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isVerified' => [parent::class, 'isVerified', null, 16],
        'lastActiveAt' => [parent::class, 'lastActiveAt', null, 16],
        'peakRating' => [parent::class, 'peakRating', null, 16],
        'preferredFormat' => [parent::class, 'preferredFormat', null, 16],
        'rank' => [parent::class, 'rank', null, 16],
        'rating' => [parent::class, 'rating', null, 16],
        'seasonStats' => [parent::class, 'seasonStats', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
