<?php

namespace Proxies\__CG__\App\Entity\Cards;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CardSet extends \App\Entity\Cards\CardSet implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'code' => [parent::class, 'code', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'logoUrl' => [parent::class, 'logoUrl', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'releaseDate' => [parent::class, 'releaseDate', null, 16],
        "\0".parent::class."\0".'setType' => [parent::class, 'setType', null, 16],
        "\0".parent::class."\0".'totalCards' => [parent::class, 'totalCards', null, 16],
        'code' => [parent::class, 'code', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'logoUrl' => [parent::class, 'logoUrl', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'releaseDate' => [parent::class, 'releaseDate', null, 16],
        'setType' => [parent::class, 'setType', null, 16],
        'totalCards' => [parent::class, 'totalCards', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
