<?php

namespace Proxies\__CG__\App\Entity\Tournaments;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tournament extends \App\Entity\Tournaments\Tournament implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'endTime' => [parent::class, 'endTime', null, 16],
        "\0".parent::class."\0".'entryFee' => [parent::class, 'entryFee', null, 16],
        "\0".parent::class."\0".'format' => [parent::class, 'format', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isOnline' => [parent::class, 'isOnline', null, 16],
        "\0".parent::class."\0".'judges' => [parent::class, 'judges', null, 16],
        "\0".parent::class."\0".'location' => [parent::class, 'location', null, 16],
        "\0".parent::class."\0".'maxPlayers' => [parent::class, 'maxPlayers', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'organizer' => [parent::class, 'organizer', null, 16],
        "\0".parent::class."\0".'prizePool' => [parent::class, 'prizePool', null, 16],
        "\0".parent::class."\0".'prizes' => [parent::class, 'prizes', null, 16],
        "\0".parent::class."\0".'registrations' => [parent::class, 'registrations', null, 16],
        "\0".parent::class."\0".'rounds' => [parent::class, 'rounds', null, 16],
        "\0".parent::class."\0".'rulesText' => [parent::class, 'rulesText', null, 16],
        "\0".parent::class."\0".'season' => [parent::class, 'season', null, 16],
        "\0".parent::class."\0".'startTime' => [parent::class, 'startTime', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'tournamentType' => [parent::class, 'tournamentType', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'endTime' => [parent::class, 'endTime', null, 16],
        'entryFee' => [parent::class, 'entryFee', null, 16],
        'format' => [parent::class, 'format', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isOnline' => [parent::class, 'isOnline', null, 16],
        'judges' => [parent::class, 'judges', null, 16],
        'location' => [parent::class, 'location', null, 16],
        'maxPlayers' => [parent::class, 'maxPlayers', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'organizer' => [parent::class, 'organizer', null, 16],
        'prizePool' => [parent::class, 'prizePool', null, 16],
        'prizes' => [parent::class, 'prizes', null, 16],
        'registrations' => [parent::class, 'registrations', null, 16],
        'rounds' => [parent::class, 'rounds', null, 16],
        'rulesText' => [parent::class, 'rulesText', null, 16],
        'season' => [parent::class, 'season', null, 16],
        'startTime' => [parent::class, 'startTime', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'tournamentType' => [parent::class, 'tournamentType', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
