<?php

namespace Proxies\__CG__\App\Entity\Cards;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Deck extends \App\Entity\Cards\Deck implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'archetype' => [parent::class, 'archetype', null, 16],
        "\0".parent::class."\0".'cards' => [parent::class, 'cards', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'format' => [parent::class, 'format', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isPublic' => [parent::class, 'isPublic', null, 16],
        "\0".parent::class."\0".'isTournamentLegal' => [parent::class, 'isTournamentLegal', null, 16],
        "\0".parent::class."\0".'losses' => [parent::class, 'losses', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'player' => [parent::class, 'player', null, 16],
        "\0".parent::class."\0".'sideboardCards' => [parent::class, 'sideboardCards', null, 16],
        "\0".parent::class."\0".'tags' => [parent::class, 'tags', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'wins' => [parent::class, 'wins', null, 16],
        'archetype' => [parent::class, 'archetype', null, 16],
        'cards' => [parent::class, 'cards', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'format' => [parent::class, 'format', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isPublic' => [parent::class, 'isPublic', null, 16],
        'isTournamentLegal' => [parent::class, 'isTournamentLegal', null, 16],
        'losses' => [parent::class, 'losses', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'player' => [parent::class, 'player', null, 16],
        'sideboardCards' => [parent::class, 'sideboardCards', null, 16],
        'tags' => [parent::class, 'tags', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'wins' => [parent::class, 'wins', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
