<?php

namespace Proxies\__CG__\App\Entity\Players;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Achievement extends \App\Entity\Players\Achievement implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'iconUrl' => [parent::class, 'iconUrl', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isHidden' => [parent::class, 'isHidden', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'points' => [parent::class, 'points', null, 16],
        "\0".parent::class."\0".'rarity' => [parent::class, 'rarity', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'iconUrl' => [parent::class, 'iconUrl', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isHidden' => [parent::class, 'isHidden', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'points' => [parent::class, 'points', null, 16],
        'rarity' => [parent::class, 'rarity', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
