<?php

namespace Proxies\__CG__\App\Entity\Marketplace;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TradeTransaction extends \App\Entity\Marketplace\TradeTransaction implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'buyer' => [parent::class, 'buyer', null, 16],
        "\0".parent::class."\0".'completedAt' => [parent::class, 'completedAt', null, 16],
        "\0".parent::class."\0".'finalPrice' => [parent::class, 'finalPrice', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'listing' => [parent::class, 'listing', null, 16],
        "\0".parent::class."\0".'platformFee' => [parent::class, 'platformFee', null, 16],
        "\0".parent::class."\0".'seller' => [parent::class, 'seller', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        'buyer' => [parent::class, 'buyer', null, 16],
        'completedAt' => [parent::class, 'completedAt', null, 16],
        'finalPrice' => [parent::class, 'finalPrice', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'listing' => [parent::class, 'listing', null, 16],
        'platformFee' => [parent::class, 'platformFee', null, 16],
        'seller' => [parent::class, 'seller', null, 16],
        'status' => [parent::class, 'status', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
