<?php

namespace Proxies\__CG__\App\Entity\Marketplace;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tradelisting extends \App\Entity\Marketplace\Tradelisting implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'askingPrice' => [parent::class, 'askingPrice', null, 16],
        "\0".parent::class."\0".'auctionCurrentBid' => [parent::class, 'auctionCurrentBid', null, 16],
        "\0".parent::class."\0".'auctionEndTime' => [parent::class, 'auctionEndTime', null, 16],
        "\0".parent::class."\0".'auctionStartPrice' => [parent::class, 'auctionStartPrice', null, 16],
        "\0".parent::class."\0".'bids' => [parent::class, 'bids', null, 16],
        "\0".parent::class."\0".'card' => [parent::class, 'card', null, 16],
        "\0".parent::class."\0".'condition' => [parent::class, 'condition', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'expiresAt' => [parent::class, 'expiresAt', null, 16],
        "\0".parent::class."\0".'foil' => [parent::class, 'foil', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'listingType' => [parent::class, 'listingType', null, 16],
        "\0".parent::class."\0".'quantity' => [parent::class, 'quantity', null, 16],
        "\0".parent::class."\0".'seller' => [parent::class, 'seller', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        'askingPrice' => [parent::class, 'askingPrice', null, 16],
        'auctionCurrentBid' => [parent::class, 'auctionCurrentBid', null, 16],
        'auctionEndTime' => [parent::class, 'auctionEndTime', null, 16],
        'auctionStartPrice' => [parent::class, 'auctionStartPrice', null, 16],
        'bids' => [parent::class, 'bids', null, 16],
        'card' => [parent::class, 'card', null, 16],
        'condition' => [parent::class, 'condition', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'expiresAt' => [parent::class, 'expiresAt', null, 16],
        'foil' => [parent::class, 'foil', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'listingType' => [parent::class, 'listingType', null, 16],
        'quantity' => [parent::class, 'quantity', null, 16],
        'seller' => [parent::class, 'seller', null, 16],
        'status' => [parent::class, 'status', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
