<?php

namespace Proxies\__CG__\App\Entity\Content;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Article extends \App\Entity\Content\Article implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'articleType' => [parent::class, 'articleType', null, 16],
        "\0".parent::class."\0".'author' => [parent::class, 'author', null, 16],
        "\0".parent::class."\0".'body' => [parent::class, 'body', null, 16],
        "\0".parent::class."\0".'comments' => [parent::class, 'comments', null, 16],
        "\0".parent::class."\0".'coverImageUrl' => [parent::class, 'coverImageUrl', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'excerpt' => [parent::class, 'excerpt', null, 16],
        "\0".parent::class."\0".'featuredDeck' => [parent::class, 'featuredDeck', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'publishedAt' => [parent::class, 'publishedAt', null, 16],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'tags' => [parent::class, 'tags', null, 16],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'viewCount' => [parent::class, 'viewCount', null, 16],
        'articleType' => [parent::class, 'articleType', null, 16],
        'author' => [parent::class, 'author', null, 16],
        'body' => [parent::class, 'body', null, 16],
        'comments' => [parent::class, 'comments', null, 16],
        'coverImageUrl' => [parent::class, 'coverImageUrl', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'excerpt' => [parent::class, 'excerpt', null, 16],
        'featuredDeck' => [parent::class, 'featuredDeck', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'publishedAt' => [parent::class, 'publishedAt', null, 16],
        'slug' => [parent::class, 'slug', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'tags' => [parent::class, 'tags', null, 16],
        'title' => [parent::class, 'title', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'viewCount' => [parent::class, 'viewCount', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
