<?php

namespace Proxies\__CG__\App\Entity\Players;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PlayerSeasonStats extends \App\Entity\Players\PlayerSeasonStats implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'draws' => [parent::class, 'draws', null, 16],
        "\0".parent::class."\0".'highestRank' => [parent::class, 'highestRank', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'losses' => [parent::class, 'losses', null, 16],
        "\0".parent::class."\0".'player' => [parent::class, 'player', null, 16],
        "\0".parent::class."\0".'season' => [parent::class, 'season', null, 16],
        "\0".parent::class."\0".'seasonPoints' => [parent::class, 'seasonPoints', null, 16],
        "\0".parent::class."\0".'tournamentWins' => [parent::class, 'tournamentWins', null, 16],
        "\0".parent::class."\0".'wins' => [parent::class, 'wins', null, 16],
        'draws' => [parent::class, 'draws', null, 16],
        'highestRank' => [parent::class, 'highestRank', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'losses' => [parent::class, 'losses', null, 16],
        'player' => [parent::class, 'player', null, 16],
        'season' => [parent::class, 'season', null, 16],
        'seasonPoints' => [parent::class, 'seasonPoints', null, 16],
        'tournamentWins' => [parent::class, 'tournamentWins', null, 16],
        'wins' => [parent::class, 'wins', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
