<?php

namespace Proxies\__CG__\App\Entity\Marketplace;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Coupon extends \App\Entity\Marketplace\Coupon implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'code' => [parent::class, 'code', null, 16],
        "\0".parent::class."\0".'discountType' => [parent::class, 'discountType', null, 16],
        "\0".parent::class."\0".'discountValue' => [parent::class, 'discountValue', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null, 16],
        "\0".parent::class."\0".'maxUses' => [parent::class, 'maxUses', null, 16],
        "\0".parent::class."\0".'minOrderValue' => [parent::class, 'minOrderValue', null, 16],
        "\0".parent::class."\0".'usesCount' => [parent::class, 'usesCount', null, 16],
        "\0".parent::class."\0".'validFrom' => [parent::class, 'validFrom', null, 16],
        "\0".parent::class."\0".'validUntil' => [parent::class, 'validUntil', null, 16],
        'code' => [parent::class, 'code', null, 16],
        'discountType' => [parent::class, 'discountType', null, 16],
        'discountValue' => [parent::class, 'discountValue', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isActive' => [parent::class, 'isActive', null, 16],
        'maxUses' => [parent::class, 'maxUses', null, 16],
        'minOrderValue' => [parent::class, 'minOrderValue', null, 16],
        'usesCount' => [parent::class, 'usesCount', null, 16],
        'validFrom' => [parent::class, 'validFrom', null, 16],
        'validUntil' => [parent::class, 'validUntil', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
