<?php

namespace Proxies\__CG__\App\Entity\Content;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DraftParticipant extends \App\Entity\Content\DraftParticipant implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'draftedCards' => [parent::class, 'draftedCards', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'joinedAt' => [parent::class, 'joinedAt', null, 16],
        "\0".parent::class."\0".'player' => [parent::class, 'player', null, 16],
        "\0".parent::class."\0".'seatNumber' => [parent::class, 'seatNumber', null, 16],
        "\0".parent::class."\0".'session' => [parent::class, 'session', null, 16],
        'draftedCards' => [parent::class, 'draftedCards', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'joinedAt' => [parent::class, 'joinedAt', null, 16],
        'player' => [parent::class, 'player', null, 16],
        'seatNumber' => [parent::class, 'seatNumber', null, 16],
        'session' => [parent::class, 'session', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
