# Generated by Django 5.0.14 on 2026-05-07 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount_type', models.CharField(choices=[('Percent', 'Percent'), ('Fixed', 'Fixed')], default='Percent', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('uses_count', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foil', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('SingleCard', 'Singlecard'), ('BoosterPack', 'Boosterpack'), ('Bundle', 'Bundle'), ('PreconstructedDeck', 'Preconstructeddeck'), ('Accessory', 'Accessory')], default='SingleCard', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('discount_percent', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TradeBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('placed_at', models.DateTimeField()),
                ('is_winning', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Trade Bid',
                'verbose_name_plural': 'Trade Bids',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TradeDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('ItemNotReceived', 'Itemnotreceived'), ('ItemNotAsDescribed', 'Itemnotasdescribed'), ('FraudSuspected', 'Fraudsuspected'), ('Other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('UnderReview', 'Underreview'), ('Resolved', 'Resolved'), ('Escalated', 'Escalated')], default='Open', max_length=20)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('opened_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Trade Dispute',
                'verbose_name_plural': 'Trade Disputes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tradelisting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('FixedPrice', 'Fixedprice'), ('Auction', 'Auction'), ('TradeOffer', 'Tradeoffer')], default='FixedPrice', max_length=20)),
                ('asking_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('auction_start_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('auction_current_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('auction_end_time', models.DateTimeField(blank=True, null=True)),
                ('foil', models.BooleanField(default=False)),
                ('condition', models.CharField(choices=[('Mint', 'Mint'), ('NearMint', 'Nearmint'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Played', 'Played')], default='Mint', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Sold', 'Sold'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='Active', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tradelisting',
                'verbose_name_plural': 'Tradelistings',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TradeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Disputed', 'Disputed'), ('Refunded', 'Refunded')], default='Pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Trade Transaction',
                'verbose_name_plural': 'Trade Transactions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CardPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateField()),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.IntegerField()),
                ('foil', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='cards.card')),
            ],
            options={
                'verbose_name': 'Card Price History',
                'verbose_name_plural': 'Card Price Histories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Pending', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(blank=True, choices=[('Card', 'Card'), ('PayPal', 'Paypal'), ('Crypto', 'Crypto'), ('PlatformCredits', 'Platformcredits')], max_length=20, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='marketplace.coupon')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-id'],
            },
        ),
    ]
