# Generated by Django 5.0.14 on 2026-05-07 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('format', models.CharField(choices=[('Standard', 'Standard'), ('Extended', 'Extended'), ('Legacy', 'Legacy'), ('Vintage', 'Vintage'), ('Commander', 'Commander'), ('Draft', 'Draft')], default='Standard', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('reward_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.IntegerField()),
                ('winner_side', models.CharField(blank=True, choices=[('Player1', 'Player1'), ('Player2', 'Player2'), ('Draw', 'Draw')], max_length=20, null=True)),
                ('turns_played', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('ended_by', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Timeout', 'Timeout'), ('Concession', 'Concession'), ('DrawOffer', 'Drawoffer')], max_length=20, null=True)),
                ('replay_url', models.URLField(blank=True, null=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_games', to='players.player')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Completed', 'Completed'), ('BYE', 'Bye'), ('Draw', 'Draw')], default='Pending', max_length=20)),
                ('player1_wins', models.IntegerField(default=0)),
                ('player2_wins', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('result_notes', models.TextField(blank=True, null=True)),
                ('games', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.game')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to='players.player')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='players.player')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.match'),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('format', models.CharField(choices=[('Standard', 'Standard'), ('Extended', 'Extended'), ('Legacy', 'Legacy'), ('Vintage', 'Vintage'), ('Commander', 'Commander'), ('Draft', 'Draft')], default='Standard', max_length=20)),
                ('tournament_type', models.CharField(choices=[('Swiss', 'Swiss'), ('SingleElimination', 'Singleelimination'), ('DoubleElimination', 'Doubleelimination'), ('RoundRobin', 'Roundrobin')], default='Swiss', max_length=20)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Registration', 'Registration'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('max_players', models.IntegerField()),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('rules_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_tournaments', to='players.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='tournaments.season')),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TournamentJudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HeadJudge', 'Headjudge'), ('Judge', 'Judge'), ('ScorekeeperJudge', 'Scorekeeperjudge')], default='Judge', max_length=20)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_roles', to='players.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Tournament Judge',
                'verbose_name_plural': 'Tournament Judges',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='judges',
            field=models.ManyToManyField(related_name='judged_tournaments', through='tournaments.TournamentJudge', to='players.player'),
        ),
        migrations.CreateModel(
            name='TournamentPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_from', models.IntegerField()),
                ('placement_to', models.IntegerField()),
                ('prize_type', models.CharField(choices=[('Currency', 'Currency'), ('Cards', 'Cards'), ('BoosterPacks', 'Boosterpacks'), ('Trophy', 'Trophy'), ('SeasonPoints', 'Seasonpoints'), ('Mixed', 'Mixed')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('packs_count', models.IntegerField(blank=True, null=True)),
                ('season_points', models.IntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Tournament Prize',
                'verbose_name_plural': 'Tournament Prizes',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='prizes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentprize'),
        ),
        migrations.CreateModel(
            name='AwardedPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_placement', models.IntegerField()),
                ('awarded_at', models.DateTimeField()),
                ('claimed', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_prizes', to='players.player')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_prizes', to='tournaments.tournamentprize')),
            ],
            options={
                'verbose_name': 'Awarded Prize',
                'verbose_name_plural': 'Awarded Prizes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('Waitlisted', 'Waitlisted'), ('Withdrawn', 'Withdrawn'), ('Disqualified', 'Disqualified')], default='Registered', max_length=20)),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('final_standing', models.IntegerField(blank=True, null=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('registered_at', models.DateTimeField()),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to='cards.deck')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to='players.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Tournament Registration',
                'verbose_name_plural': 'Tournament Registrations',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='registrations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentregistration'),
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('time_limit_minutes', models.IntegerField(default=50)),
                ('matches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.match')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Tournament Round',
                'verbose_name_plural': 'Tournament Rounds',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='rounds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentround'),
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentround'),
        ),
    ]
