<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ly8pRDZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ly8pRDZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ly8pRDZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'playerAchievement' => ['privates', '.errored..service_locator.Ly8pRDZ.App\\Entity\\Players\\PlayerAchievement', NULL, 'Cannot autowire service ".service_locator.Ly8pRDZ": it needs an instance of "App\\Entity\\Players\\PlayerAchievement" but this type has been excluded in "config/services.yaml".'],
        ], [
            'playerAchievement' => 'App\\Entity\\Players\\PlayerAchievement',
        ]);
    }
}
