<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BPtWLmwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BPtWLmw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BPtWLmw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'articleComment' => ['privates', '.errored..service_locator.BPtWLmw.App\\Entity\\Content\\ArticleComment', NULL, 'Cannot autowire service ".service_locator.BPtWLmw": it needs an instance of "App\\Entity\\Content\\ArticleComment" but this type has been excluded in "config/services.yaml".'],
        ], [
            'articleComment' => 'App\\Entity\\Content\\ArticleComment',
        ]);
    }
}
