<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X1Xw1llService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x1Xw1ll' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x1Xw1ll'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'craftingRecipe' => ['privates', '.errored..service_locator.x1Xw1ll.App\\Entity\\Players\\CraftingRecipe', NULL, 'Cannot autowire service ".service_locator.x1Xw1ll": it needs an instance of "App\\Entity\\Players\\CraftingRecipe" but this type has been excluded in "config/services.yaml".'],
        ], [
            'craftingRecipe' => 'App\\Entity\\Players\\CraftingRecipe',
        ]);
    }
}
