<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B9yc7TjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.b9yc7Tj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.b9yc7Tj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'deck' => ['privates', '.errored..service_locator.b9yc7Tj.App\\Entity\\Cards\\Deck', NULL, 'Cannot autowire service ".service_locator.b9yc7Tj": it needs an instance of "App\\Entity\\Cards\\Deck" but this type has been excluded in "config/services.yaml".'],
        ], [
            'deck' => 'App\\Entity\\Cards\\Deck',
        ]);
    }
}
