<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__70rJ0RService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..70rJ0R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sync' => ['privates', 'messenger.transport.sync', 'getMessenger_Transport_SyncService', true],
            'messenger.transport.sync' => ['privates', 'messenger.transport.sync', 'getMessenger_Transport_SyncService', true],
        ], [
            'sync' => '?',
            'messenger.transport.sync' => '?',
        ]);

        if (isset($container->privates['.service_locator..70rJ0R'])) {
            return $container->privates['.service_locator..70rJ0R'];
        }

        return $container->privates['.service_locator..70rJ0R'] = $instance;
    }
}
