<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HE85GpdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hE85Gpd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hE85Gpd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tradeTransaction' => ['privates', '.errored..service_locator.hE85Gpd.App\\Entity\\Marketplace\\TradeTransaction', NULL, 'Cannot autowire service ".service_locator.hE85Gpd": it needs an instance of "App\\Entity\\Marketplace\\TradeTransaction" but this type has been excluded in "config/services.yaml".'],
        ], [
            'tradeTransaction' => 'App\\Entity\\Marketplace\\TradeTransaction',
        ]);
    }
}
