<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AUEPMPXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AUEPMPX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AUEPMPX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'articleTagAssignment' => ['privates', '.errored..service_locator.AUEPMPX.App\\Entity\\Content\\ArticleTagAssignment', NULL, 'Cannot autowire service ".service_locator.AUEPMPX": it needs an instance of "App\\Entity\\Content\\ArticleTagAssignment" but this type has been excluded in "config/services.yaml".'],
        ], [
            'articleTagAssignment' => 'App\\Entity\\Content\\ArticleTagAssignment',
        ]);
    }
}
