<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RpQ9gEGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rpQ9gEG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rpQ9gEG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tournamentPrize' => ['privates', '.errored..service_locator.rpQ9gEG.App\\Entity\\Tournaments\\TournamentPrize', NULL, 'Cannot autowire service ".service_locator.rpQ9gEG": it needs an instance of "App\\Entity\\Tournaments\\TournamentPrize" but this type has been excluded in "config/services.yaml".'],
        ], [
            'tournamentPrize' => 'App\\Entity\\Tournaments\\TournamentPrize',
        ]);
    }
}
