<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_APuDad6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aPuDad6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aPuDad6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'craftingIngredient' => ['privates', '.errored..service_locator.aPuDad6.App\\Entity\\Players\\CraftingIngredient', NULL, 'Cannot autowire service ".service_locator.aPuDad6": it needs an instance of "App\\Entity\\Players\\CraftingIngredient" but this type has been excluded in "config/services.yaml".'],
        ], [
            'craftingIngredient' => 'App\\Entity\\Players\\CraftingIngredient',
        ]);
    }
}
