<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VnBharRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VnBharR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VnBharR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'articleTag' => ['privates', '.errored..service_locator.VnBharR.App\\Entity\\Content\\ArticleTag', NULL, 'Cannot autowire service ".service_locator.VnBharR": it needs an instance of "App\\Entity\\Content\\ArticleTag" but this type has been excluded in "config/services.yaml".'],
        ], [
            'articleTag' => 'App\\Entity\\Content\\ArticleTag',
        ]);
    }
}
