<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OMOzoFBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oMOzoFB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oMOzoFB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cardAbility' => ['privates', '.errored..service_locator.oMOzoFB.App\\Entity\\Cards\\CardAbility', NULL, 'Cannot autowire service ".service_locator.oMOzoFB": it needs an instance of "App\\Entity\\Cards\\CardAbility" but this type has been excluded in "config/services.yaml".'],
        ], [
            'cardAbility' => 'App\\Entity\\Cards\\CardAbility',
        ]);
    }
}
