<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KR7cRY9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KR7cRY9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KR7cRY9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tournamentRound' => ['privates', '.errored..service_locator.KR7cRY9.App\\Entity\\Tournaments\\TournamentRound', NULL, 'Cannot autowire service ".service_locator.KR7cRY9": it needs an instance of "App\\Entity\\Tournaments\\TournamentRound" but this type has been excluded in "config/services.yaml".'],
        ], [
            'tournamentRound' => 'App\\Entity\\Tournaments\\TournamentRound',
        ]);
    }
}
