<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PYBAu_NService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pYBAu.N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pYBAu.N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'deckTag' => ['privates', '.errored..service_locator.pYBAu.N.App\\Entity\\Cards\\DeckTag', NULL, 'Cannot autowire service ".service_locator.pYBAu.N": it needs an instance of "App\\Entity\\Cards\\DeckTag" but this type has been excluded in "config/services.yaml".'],
        ], [
            'deckTag' => 'App\\Entity\\Cards\\DeckTag',
        ]);
    }
}
