<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G0u8UH8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G0u8UH8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G0u8UH8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tradeBid' => ['privates', '.errored..service_locator.G0u8UH8.App\\Entity\\Marketplace\\TradeBid', NULL, 'Cannot autowire service ".service_locator.G0u8UH8": it needs an instance of "App\\Entity\\Marketplace\\TradeBid" but this type has been excluded in "config/services.yaml".'],
        ], [
            'tradeBid' => 'App\\Entity\\Marketplace\\TradeBid',
        ]);
    }
}
