<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UlNA7QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._ulNA7Q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._ulNA7Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'deckTagAssignment' => ['privates', '.errored..service_locator._ulNA7Q.App\\Entity\\Cards\\DeckTagAssignment', NULL, 'Cannot autowire service ".service_locator._ulNA7Q": it needs an instance of "App\\Entity\\Cards\\DeckTagAssignment" but this type has been excluded in "config/services.yaml".'],
        ], [
            'deckTagAssignment' => 'App\\Entity\\Cards\\DeckTagAssignment',
        ]);
    }
}
