<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bdy8RU9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Bdy8RU9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Bdy8RU9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tradeDispute' => ['privates', '.errored..service_locator.Bdy8RU9.App\\Entity\\Marketplace\\TradeDispute', NULL, 'Cannot autowire service ".service_locator.Bdy8RU9": it needs an instance of "App\\Entity\\Marketplace\\TradeDispute" but this type has been excluded in "config/services.yaml".'],
        ], [
            'tradeDispute' => 'App\\Entity\\Marketplace\\TradeDispute',
        ]);
    }
}
