<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U0F2H3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u0F2_H3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u0F2_H3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tradelisting' => ['privates', '.errored..service_locator.u0F2_H3.App\\Entity\\Marketplace\\Tradelisting', NULL, 'Cannot autowire service ".service_locator.u0F2_H3": it needs an instance of "App\\Entity\\Marketplace\\Tradelisting" but this type has been excluded in "config/services.yaml".'],
        ], [
            'tradelisting' => 'App\\Entity\\Marketplace\\Tradelisting',
        ]);
    }
}
