<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LdzNegHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ldzNegH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ldzNegH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'order' => ['privates', '.errored..service_locator.ldzNegH.App\\Entity\\Marketplace\\Order', NULL, 'Cannot autowire service ".service_locator.ldzNegH": it needs an instance of "App\\Entity\\Marketplace\\Order" but this type has been excluded in "config/services.yaml".'],
        ], [
            'order' => 'App\\Entity\\Marketplace\\Order',
        ]);
    }
}
