<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleCommentControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Content\ArticleCommentController' shared autowired service.
     *
     * @return \App\Controller\Api\Content\ArticleCommentController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Content/ArticleCommentController.php';

        $a = ($container->privates['App\\Repository\\Content\\ArticleCommentRepository'] ?? $container->load('getArticleCommentRepositoryService'));

        $container->services['App\\Controller\\Api\\Content\\ArticleCommentController'] = $instance = new \App\Controller\Api\Content\ArticleCommentController($a, ($container->privates['validator'] ?? self::getValidatorService($container)), ($container->privates['App\\Repository\\Content\\ArticleRepository'] ?? $container->load('getArticleRepositoryService')), ($container->privates['App\\Repository\\Players\\PlayerRepository'] ?? $container->load('getPlayerRepositoryService')), $a);

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\Content\\ArticleCommentController', $container));

        return $instance;
    }
}
