<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAchievementControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OS6i8aR.App\Controller\Api\Players\AchievementController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OS6i8aR.App\\Controller\\Api\\Players\\AchievementController::delete()'] = ($container->privates['.service_locator.OS6i8aR'] ?? $container->load('get_ServiceLocator_OS6i8aRService'))->withContext('App\\Controller\\Api\\Players\\AchievementController::delete()', $container);
    }
}
