<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleTagAssignmentControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AUEPMPX.App\Controller\Api\Content\ArticleTagAssignmentController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AUEPMPX.App\\Controller\\Api\\Content\\ArticleTagAssignmentController::delete()'] = ($container->privates['.service_locator.AUEPMPX'] ?? $container->load('get_ServiceLocator_AUEPMPXService'))->withContext('App\\Controller\\Api\\Content\\ArticleTagAssignmentController::delete()', $container);
    }
}
