<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleTagAssignmentControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Content\ArticleTagAssignmentController' shared autowired service.
     *
     * @return \App\Controller\Api\Content\ArticleTagAssignmentController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Content/ArticleTagAssignmentController.php';

        $container->services['App\\Controller\\Api\\Content\\ArticleTagAssignmentController'] = $instance = new \App\Controller\Api\Content\ArticleTagAssignmentController(($container->privates['App\\Repository\\Content\\ArticleTagAssignmentRepository'] ?? $container->load('getArticleTagAssignmentRepositoryService')), ($container->privates['validator'] ?? self::getValidatorService($container)), ($container->privates['App\\Repository\\Content\\ArticleRepository'] ?? $container->load('getArticleRepositoryService')), ($container->privates['App\\Repository\\Content\\ArticleTagRepository'] ?? $container->load('getArticleTagRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\Content\\ArticleTagAssignmentController', $container));

        return $instance;
    }
}
