<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCouponControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ylPAFu6.App\Controller\Api\Marketplace\CouponController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ylPAFu6.App\\Controller\\Api\\Marketplace\\CouponController::update()'] = ($container->privates['.service_locator.ylPAFu6'] ?? $container->load('get_ServiceLocator_YlPAFu6Service'))->withContext('App\\Controller\\Api\\Marketplace\\CouponController::update()', $container);
    }
}
