<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCraftingRecipeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.x1Xw1ll.App\Entity\Players\CraftingRecipe' shared service.
     *
     * @return \App\Entity\Players\CraftingRecipe
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.x1Xw1ll": it needs an instance of "App\\Entity\\Players\\CraftingRecipe" but this type has been excluded in "config/services.yaml".');
    }
}
