<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardPriceHistoryControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Marketplace\CardPriceHistoryController' shared autowired service.
     *
     * @return \App\Controller\Api\Marketplace\CardPriceHistoryController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Marketplace/CardPriceHistoryController.php';

        $container->services['App\\Controller\\Api\\Marketplace\\CardPriceHistoryController'] = $instance = new \App\Controller\Api\Marketplace\CardPriceHistoryController(($container->privates['App\\Repository\\Marketplace\\CardPriceHistoryRepository'] ?? $container->load('getCardPriceHistoryRepositoryService')), ($container->privates['validator'] ?? self::getValidatorService($container)), ($container->privates['App\\Repository\\Cards\\CardRepository'] ?? $container->load('getCardRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\Marketplace\\CardPriceHistoryController', $container));

        return $instance;
    }
}
