<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardRulingControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yy4sAMG.App\Controller\Api\Cards\CardRulingController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yy4sAMG.App\\Controller\\Api\\Cards\\CardRulingController::update()'] = ($container->privates['.service_locator.yy4sAMG'] ?? $container->load('get_ServiceLocator_Yy4sAMGService'))->withContext('App\\Controller\\Api\\Cards\\CardRulingController::update()', $container);
    }
}
