<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardPriceHistoryControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vYnVyKf.App\Controller\Api\Marketplace\CardPriceHistoryController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vYnVyKf.App\\Controller\\Api\\Marketplace\\CardPriceHistoryController::update()'] = ($container->privates['.service_locator.vYnVyKf'] ?? $container->load('get_ServiceLocator_VYnVyKfService'))->withContext('App\\Controller\\Api\\Marketplace\\CardPriceHistoryController::update()', $container);
    }
}
