<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCraftingIngredientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.aPuDad6.App\Entity\Players\CraftingIngredient' shared service.
     *
     * @return \App\Entity\Players\CraftingIngredient
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.aPuDad6": it needs an instance of "App\\Entity\\Players\\CraftingIngredient" but this type has been excluded in "config/services.yaml".');
    }
}
