<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1NRXpfM.App\Controller\Api\Cards\CardController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1NRXpfM.App\\Controller\\Api\\Cards\\CardController::delete()'] = ($container->privates['.service_locator.1NRXpfM'] ?? $container->load('get_ServiceLocator_1NRXpfMService'))->withContext('App\\Controller\\Api\\Cards\\CardController::delete()', $container);
    }
}
