<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardRulingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.yy4sAMG.App\Entity\Cards\CardRuling' shared service.
     *
     * @return \App\Entity\Cards\CardRuling
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.yy4sAMG": it needs an instance of "App\\Entity\\Cards\\CardRuling" but this type has been excluded in "config/services.yaml".');
    }
}
