<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCouponControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Marketplace\CouponController' shared autowired service.
     *
     * @return \App\Controller\Api\Marketplace\CouponController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Marketplace/CouponController.php';

        $container->services['App\\Controller\\Api\\Marketplace\\CouponController'] = $instance = new \App\Controller\Api\Marketplace\CouponController(($container->privates['App\\Repository\\Marketplace\\CouponRepository'] ?? $container->load('getCouponRepositoryService')), ($container->privates['validator'] ?? self::getValidatorService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\Marketplace\\CouponController', $container));

        return $instance;
    }
}
