<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDraftSessionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Content\DraftSessionController' shared autowired service.
     *
     * @return \App\Controller\Api\Content\DraftSessionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Content/DraftSessionController.php';

        $container->services['App\\Controller\\Api\\Content\\DraftSessionController'] = $instance = new \App\Controller\Api\Content\DraftSessionController(($container->privates['App\\Repository\\Content\\DraftSessionRepository'] ?? $container->load('getDraftSessionRepositoryService')), ($container->privates['validator'] ?? self::getValidatorService($container)), ($container->privates['App\\Repository\\Cards\\CardSetRepository'] ?? $container->load('getCardSetRepositoryService')), ($container->privates['App\\Repository\\Content\\DraftParticipantRepository'] ?? $container->load('getDraftParticipantRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\Content\\DraftSessionController', $container));

        return $instance;
    }
}
