<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeckSideboardCardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Fo7DBVx.App\Entity\Cards\DeckSideboardCard' shared service.
     *
     * @return \App\Entity\Cards\DeckSideboardCard
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Fo7DBVx": it needs an instance of "App\\Entity\\Cards\\DeckSideboardCard" but this type has been excluded in "config/services.yaml".');
    }
}
