<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeckSideboardCardControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Fo7DBVx.App\Controller\Api\Cards\DeckSideboardCardController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Fo7DBVx.App\\Controller\\Api\\Cards\\DeckSideboardCardController::delete()'] = ($container->privates['.service_locator.Fo7DBVx'] ?? $container->load('get_ServiceLocator_Fo7DBVxService'))->withContext('App\\Controller\\Api\\Cards\\DeckSideboardCardController::delete()', $container);
    }
}
