<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDraftParticipantControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..7xBimd.App\Controller\Api\Content\DraftParticipantController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..7xBimd.App\\Controller\\Api\\Content\\DraftParticipantController::delete()'] = ($container->privates['.service_locator..7xBimd'] ?? $container->load('get_ServiceLocator__7xBimdService'))->withContext('App\\Controller\\Api\\Content\\DraftParticipantController::delete()', $container);
    }
}
