<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFriendshipService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._EaXnVg.App\Entity\Players\Friendship' shared service.
     *
     * @return \App\Entity\Players\Friendship
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator._EaXnVg": it needs an instance of "App\\Entity\\Players\\Friendship" but this type has been excluded in "config/services.yaml".');
    }
}
