<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGameControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VV2FQBT.App\Controller\Api\Tournaments\GameController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VV2FQBT.App\\Controller\\Api\\Tournaments\\GameController::delete()'] = ($container->privates['.service_locator.VV2FQBT'] ?? $container->load('get_ServiceLocator_VV2FQBTService'))->withContext('App\\Controller\\Api\\Tournaments\\GameController::delete()', $container);
    }
}
