<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMatchRecordControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AI3lAU3.App\Controller\Api\Tournaments\MatchRecordController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AI3lAU3.App\\Controller\\Api\\Tournaments\\MatchRecordController::delete()'] = ($container->privates['.service_locator.AI3lAU3'] ?? $container->load('get_ServiceLocator_AI3lAU3Service'))->withContext('App\\Controller\\Api\\Tournaments\\MatchRecordController::delete()', $container);
    }
}
