<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Marketplace\OrderController' shared autowired service.
     *
     * @return \App\Controller\Api\Marketplace\OrderController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Marketplace/OrderController.php';

        $container->services['App\\Controller\\Api\\Marketplace\\OrderController'] = $instance = new \App\Controller\Api\Marketplace\OrderController(($container->privates['App\\Repository\\Marketplace\\OrderRepository'] ?? $container->load('getOrderRepositoryService')), ($container->privates['validator'] ?? self::getValidatorService($container)), ($container->privates['App\\Repository\\Players\\PlayerRepository'] ?? $container->load('getPlayerRepositoryService')), ($container->privates['App\\Repository\\Marketplace\\OrderItemRepository'] ?? $container->load('getOrderItemRepositoryService')), ($container->privates['App\\Repository\\Marketplace\\CouponRepository'] ?? $container->load('getCouponRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\Marketplace\\OrderController', $container));

        return $instance;
    }
}
