<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderItemService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.XvaGv9f.App\Entity\Marketplace\OrderItem' shared service.
     *
     * @return \App\Entity\Marketplace\OrderItem
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.XvaGv9f": it needs an instance of "App\\Entity\\Marketplace\\OrderItem" but this type has been excluded in "config/services.yaml".');
    }
}
