<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerAchievementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Ly8pRDZ.App\Entity\Players\PlayerAchievement' shared service.
     *
     * @return \App\Entity\Players\PlayerAchievement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Ly8pRDZ": it needs an instance of "App\\Entity\\Players\\PlayerAchievement" but this type has been excluded in "config/services.yaml".');
    }
}
