<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.px7wq6a.App\Controller\Api\Marketplace\ProductController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.px7wq6a.App\\Controller\\Api\\Marketplace\\ProductController::delete()'] = ($container->privates['.service_locator.px7wq6a'] ?? $container->load('get_ServiceLocator_Px7wq6aService'))->withContext('App\\Controller\\Api\\Marketplace\\ProductController::delete()', $container);
    }
}
