<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeasonControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F1KWirM.App\Controller\Api\Tournaments\SeasonController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F1KWirM.App\\Controller\\Api\\Tournaments\\SeasonController::update()'] = ($container->privates['.service_locator.F1KWirM'] ?? $container->load('get_ServiceLocator_F1KWirMService'))->withContext('App\\Controller\\Api\\Tournaments\\SeasonController::update()', $container);
    }
}
