<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeasonService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.F1KWirM.App\Entity\Tournaments\Season' shared service.
     *
     * @return \App\Entity\Tournaments\Season
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.F1KWirM": it needs an instance of "App\\Entity\\Tournaments\\Season" but this type has been excluded in "config/services.yaml".');
    }
}
