<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStreamService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SzWXwXJ.App\Entity\Content\Stream' shared service.
     *
     * @return \App\Entity\Content\Stream
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.SzWXwXJ": it needs an instance of "App\\Entity\\Content\\Stream" but this type has been excluded in "config/services.yaml".');
    }
}
