<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournamentPrizeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Tournaments\TournamentPrizeController' shared autowired service.
     *
     * @return \App\Controller\Api\Tournaments\TournamentPrizeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Tournaments/TournamentPrizeController.php';

        $container->services['App\\Controller\\Api\\Tournaments\\TournamentPrizeController'] = $instance = new \App\Controller\Api\Tournaments\TournamentPrizeController(($container->privates['App\\Repository\\Tournaments\\TournamentPrizeRepository'] ?? $container->load('getTournamentPrizeRepositoryService')), ($container->privates['validator'] ?? self::getValidatorService($container)), ($container->privates['App\\Repository\\Tournaments\\TournamentRepository'] ?? $container->load('getTournamentRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\Tournaments\\TournamentPrizeController', $container));

        return $instance;
    }
}
