<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTradeTransactionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Marketplace\TradeTransactionController' shared autowired service.
     *
     * @return \App\Controller\Api\Marketplace\TradeTransactionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Marketplace/TradeTransactionController.php';

        $container->services['App\\Controller\\Api\\Marketplace\\TradeTransactionController'] = $instance = new \App\Controller\Api\Marketplace\TradeTransactionController(($container->privates['App\\Repository\\Marketplace\\TradeTransactionRepository'] ?? $container->load('getTradeTransactionRepositoryService')), ($container->privates['validator'] ?? self::getValidatorService($container)), ($container->privates['App\\Repository\\Marketplace\\TradelistingRepository'] ?? $container->load('getTradelistingRepositoryService')), ($container->privates['App\\Repository\\Players\\PlayerRepository'] ?? $container->load('getPlayerRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\Marketplace\\TradeTransactionController', $container));

        return $instance;
    }
}
