<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTradelistingControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u0F2_H3.App\Controller\Api\Marketplace\TradelistingController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u0F2_H3.App\\Controller\\Api\\Marketplace\\TradelistingController::delete()'] = ($container->privates['.service_locator.u0F2_H3'] ?? $container->load('get_ServiceLocator_U0F2H3Service'))->withContext('App\\Controller\\Api\\Marketplace\\TradelistingController::delete()', $container);
    }
}
