<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTradelistingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.u0F2_H3.App\Entity\Marketplace\Tradelisting' shared service.
     *
     * @return \App\Entity\Marketplace\Tradelisting
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.u0F2_H3": it needs an instance of "App\\Entity\\Marketplace\\Tradelisting" but this type has been excluded in "config/services.yaml".');
    }
}
