<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournamentRegistrationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Tournaments\TournamentRegistrationController' shared autowired service.
     *
     * @return \App\Controller\Api\Tournaments\TournamentRegistrationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Tournaments/TournamentRegistrationController.php';

        $container->services['App\\Controller\\Api\\Tournaments\\TournamentRegistrationController'] = $instance = new \App\Controller\Api\Tournaments\TournamentRegistrationController(($container->privates['App\\Repository\\Tournaments\\TournamentRegistrationRepository'] ?? $container->load('getTournamentRegistrationRepositoryService')), ($container->privates['validator'] ?? self::getValidatorService($container)), ($container->privates['App\\Repository\\Tournaments\\TournamentRepository'] ?? $container->load('getTournamentRepositoryService')), ($container->privates['App\\Repository\\Players\\PlayerRepository'] ?? $container->load('getPlayerRepositoryService')), ($container->privates['App\\Repository\\Cards\\DeckRepository'] ?? $container->load('getDeckRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\Tournaments\\TournamentRegistrationController', $container));

        return $instance;
    }
}
