<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournamentJudgeControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4qIwCKD.App\Controller\Api\Tournaments\TournamentJudgeController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4qIwCKD.App\\Controller\\Api\\Tournaments\\TournamentJudgeController::delete()'] = ($container->privates['.service_locator.4qIwCKD'] ?? $container->load('get_ServiceLocator_4qIwCKDService'))->withContext('App\\Controller\\Api\\Tournaments\\TournamentJudgeController::delete()', $container);
    }
}
