<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTradeDisputeControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Bdy8RU9.App\Controller\Api\Marketplace\TradeDisputeController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Bdy8RU9.App\\Controller\\Api\\Marketplace\\TradeDisputeController::delete()'] = ($container->privates['.service_locator.Bdy8RU9'] ?? $container->load('get_ServiceLocator_Bdy8RU9Service'))->withContext('App\\Controller\\Api\\Marketplace\\TradeDisputeController::delete()', $container);
    }
}
