<?php

namespace ContainerI282wLJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTradeDisputeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Marketplace\TradeDisputeController' shared autowired service.
     *
     * @return \App\Controller\Api\Marketplace\TradeDisputeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Marketplace/TradeDisputeController.php';

        $container->services['App\\Controller\\Api\\Marketplace\\TradeDisputeController'] = $instance = new \App\Controller\Api\Marketplace\TradeDisputeController(($container->privates['App\\Repository\\Marketplace\\TradeDisputeRepository'] ?? $container->load('getTradeDisputeRepositoryService')), ($container->privates['validator'] ?? self::getValidatorService($container)), ($container->privates['App\\Repository\\Marketplace\\TradeTransactionRepository'] ?? $container->load('getTradeTransactionRepositoryService')), ($container->privates['App\\Repository\\Players\\PlayerRepository'] ?? $container->load('getPlayerRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\Marketplace\\TradeDisputeController', $container));

        return $instance;
    }
}
