spring.datasource.url=jdbc:sqlite:cards_project.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
springdoc.swagger-ui.path=/swagger-ui.html
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.jpa.open-in-view=false
