source "https://rubygems.org"

ruby ">= 3.1"

gem "rails", "~> 7.2"
gem "zeitwerk", "~> 2.7.0"
gem "sqlite3", ">= 1.4"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "devise"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
end

group :test do
  gem "shoulda-matchers"
end
